### ISSUE TITLE
从2.8.0升级到beta2出现无法连接服务器的问题

### ISSUE THREAD

**Issue by 668477** [altairwei/WizNotePlus#101]
2.8.0升级到beta2.原来是登录状态，进入beta2也是登录的状态，但是无法同步。
注销后，beta2登录界面显示license出错。
wireshark抓包，发现beta2未发出任何网络请求。
windows防火墙已经关闭。

回退到2.8.0版本后能正常使用。
btw：是连接到docker的wiz服务器。

**Comment by altairwei** [comment]
提供一下消息控制台的日志信息呢。

**Comment by 668477** [comment]
重新解压了一份，想复现，发现可以正常连接服务器了。
