### ISSUE TITLE
在公司电脑上使用beta2，被杀毒软件干掉了

### ISSUE THREAD

**Issue by jjtenger** [altairwei/WizNotePlus#102]
杀毒软件报警提示：
![微信截图_20200401092902](https://user-images.githubusercontent.com/20854253/78089920-4c299300-73fb-11ea-849a-171f4d7a9157.png)

之前beta1使用好像是正常的。

**Comment by altairwei** [comment]
你看一下 “目标” 里面的是什么文件。

**Comment by jjtenger** [comment]
> 你看一下 “目标” 里面的是什么文件。

第二次安装打开后，变成这个了......

![微信截图_20200401111821](https://user-images.githubusercontent.com/20854253/78096263-bc401500-740b-11ea-8cc4-89a875d6cf90.png)

**Comment by altairwei** [comment]
这次的 “违例” 是啥？

**Comment by jjtenger** [comment]
“恶意软件行为阻止”，公司的杀毒软件太搓了，我已经申请加入白名单了。

**Comment by jjtenger** [comment]
> 你看一下 “目标” 里面的是什么文件。

这次看到了，貌似是头像图片？

![image](https://user-images.githubusercontent.com/20854253/78105164-27e1ac80-7423-11ea-86f8-5cf221291ea6.png)

**Comment by altairwei** [comment]
这个杀毒系统太敏感了？还是说针对 C 盘的监控力度太大？
