### ISSUE TITLE
图片在上传后地址仍然为C盘下临时目录的url

### ISSUE THREAD

**Issue by 668477** [altairwei/WizNotePlus#106]
用的docker的服务端。
本地客户端内用复制粘贴的方式增加图片后。
从服务器web版本和其他机器的wiznoteplus同步后看图片都不显示，看图片的url为
file:///C:/Users/XXXXX/AppData/Local/Temp/WizNote/下面的图片。

用wireshark抓了客户端上传笔记本的http报文。放在百度网盘上
链接: https://pan.baidu.com/s/1kh9Be1_wXmwprkNbXWCDrQ 提取码: eg9w

**Comment by 668477** [comment]
尝试审查元素的时候把绝对路径改成相对路径，其他端就能正常显示图片了。

**Comment by altairwei** [comment]
OK，确认是客户端 BUG

**Comment by altairwei** [comment]
已修复，可以尝试 https://github.com/altairwei/WizNotePlus/actions/runs/99767994 下载对应的 Artifacts 测试。
