### ISSUE TITLE
Linux下删除换行导致下一行被错误删除

### ISSUE THREAD

**Issue by edpsun** [altairwei/WizNotePlus#112]
Platform:  Manjaro Linux
Version:  2.8.0 Beta3

新建普通node，如下数据，删除123后的换行符会导致456也被删除。
123
456
789

删除123后的换行符之后：
123
789
希望这个问题能重现。 如果需要日志，请告诉如何查看日志。

**Comment by altairwei** [comment]
内部富文本编辑器因为源代码没有开源，所以 BUG 修起来比较麻烦。这个 BUG 我先记录下来，什么时候能够修复我不能保证。

**Comment by edpsun** [comment]
没有关系，暂时切换到Wiznote 2.85了。
如果有定期的把上游代码合并进来， 下次可能就已经自动修复了。

**Comment by altairwei** [comment]
已经不可能同步 WizQTClient 了。WizNotePlus 变化太大了，合并 WizQTClient 只会导致更多的 BUG 产生。

**Comment by altairwei** [comment]
这是 Qt 5.12.8 的 BUG，我在考虑是否将依赖升级到 Qt 5.14 。

**Comment by altairwei** [comment]
正式版将会基于 Qt 5.14.2 构建，这个问题应该会消失。
