### ISSUE TITLE
希望linux版可以恢复“显示子文件夹笔记”的功能

### ISSUE THREAD

**Issue by LTzunan** [altairwei/WizNotePlus#113]

**Comment by altairwei** [comment]
这是什么功能来着？你描述一下？

**Comment by LTzunan** [comment]
> 这是什么功能来着？你描述一下？

就是这个，可以在根目录中直接浏览子目录中的笔记，第一张图片是wiznoteplus的，第二张图片是官方linux版的效果
![微信图片_20200520224613](https://user-images.githubusercontent.com/60066337/82461410-fd3fd600-9aec-11ea-9302-3557b3b02359.jpg)
![微信图片_20200520224639](https://user-images.githubusercontent.com/60066337/82461519-1c3e6800-9aed-11ea-80c3-17451dcaf97c.jpg)

**Comment by altairwei** [comment]
从你的图片看，WizNotePlus 的界面字体是不是要比官方版本小一些？

**Comment by LTzunan** [comment]
> 从你的图片看，WizNotePlus 的界面字体是不是要比官方版本小一些？

是有一点，但我觉得问题不是很大

**Comment by altairwei** [comment]
“显示子文件夹笔记” 的消失有可能是 BUG，我不记得我取消过这个功能。

**Comment by LTzunan** [comment]
> “显示子文件夹笔记” 的消失有可能是 BUG，我不记得我取消过这个功能。

好的，谢谢，麻烦你了

**Comment by altairwei** [comment]
这属于官方的新特征，后面我会跟进的。

**Comment by altairwei** [comment]
v2.9.0 已实现此功能。
