### ISSUE TITLE
某些网页使用MaoXian Web Clipper剪辑到WizNotePlus会导致程序崩溃

### ISSUE THREAD

**Issue by adamhj** [altairwei/WizNotePlus#115]
WizNotePlus-windows-v2.8.0-beta.3版本，使用火狐版的MaoXian Web Clipper，MaoXian Web Clipper的storage选为WizNotePlus，剪辑[这个页面](https://blog.riskivy.com/2020%e6%94%bb%e9%98%b2%e6%bc%94%e7%bb%83%e5%bc%b9%e8%8d%af%e5%ba%93-%e6%82%a8%e6%9c%89%e4%b8%bb%e6%9c%ba%e4%b8%8a%e7%ba%bf%e8%af%b7%e6%b3%a8%e6%84%8f/?from=timeline&isappinstalled=0)中间的主体文章部分时，会导致WizNotePlus崩溃，报错“wiznote.exe已停止工作”

顺带一提，用chrome版的MaoXian Web Clipper剪这个页面就不会出现这个问题

**Comment by altairwei** [comment]
MaoXian Web Clipper 的版本是多少？

**Comment by adamhj** [comment]
MaoXian Web Clipper 0.1.56
Firefox 76.0.1 (64-bit)

顺便刚才发现剪这个网页也会崩
https://blogs.igalia.com/dpino/2016/04/10/network-namespaces/

**Comment by altairwei** [comment]
剪裁格式是 HTML 还是 Markdown ？我没重复出你这个问题

**Comment by adamhj** [comment]
是HTML格式
更新到v2.8.0-rc.1后问题消失了
