### ISSUE TITLE
希望linux版也可以简单地在文本中插入上下标

### ISSUE THREAD

**Issue by LTzunan** [altairwei/WizNotePlus#116]
此外，发现linux版本的插入表格只有在编辑状态下才能打勾，不知道算不算小bug

**Comment by altairwei** [comment]
> > 此外，发现linux版本的插入表格只有在编辑状态下才能打勾，不知道算不算小bug
> 
> 这里的打勾是指清单打勾？最新版本清单打勾无论是否在编辑状态都可以进行，在表格中添加清单之后打勾也没问题

这个清单的 bug 已经修复了，在阅读状态下也能 check

**Comment by altairwei** [comment]
已在 v2.9.2 中实现。
