### ISSUE TITLE
beta3版本复制文本bug

### ISSUE THREAD

**Issue by hzmming** [altairwei/WizNotePlus#117]
1. 复制后文本格式丢失
复现：复制上一篇笔记的“加黑文本”，在另一篇笔记粘贴，结果格式丢失

2. 多行无法复制

![image](https://user-images.githubusercontent.com/15829377/82774912-b5b4a380-9e78-11ea-9d91-ef61bdfc3cfc.png)

我记得之前的版本应该是没有这些问题的

**Comment by altairwei** [comment]
有点麻烦，我测试了下这是 Qt 5.12.8 的 BUG。如果升级到 Qt 5.14.2 的话，有些老旧系统的用户就用不了 WizNotePlus 了。

**Comment by altairwei** [comment]
正式版将会基于 Qt 5.14.2 构建，这个问题应该会消失。
