### ISSUE TITLE
可以不使用百度网盘下载不 ,慢的一批

### ISSUE THREAD

**Issue by MerlinFeng** [altairwei/WizNotePlus#119]
可以不使用百度网盘下载不 ,慢的一批

**Comment by altairwei** [comment]
Release Notes 上写了啊

百度网盘：https://pan.baidu.com/s/1QfkbiZGz7_mOLnlcysuelA

**Comment by altairwei** [comment]
你可以翻到 Assets 从 GitHub 下载
