### ISSUE TITLE
debian 9.3启动报错

### ISSUE THREAD

**Issue by wai4y** [altairwei/WizNotePlus#12]
![screenshot from 2018-11-04 20-59-19](https://user-images.githubusercontent.com/9801268/47973894-bdcda800-e074-11e8-82fd-e663fa6d8e25.png)

**Comment by altairwei** [comment]
你 Debian 里的 zlib 和 glibc 是不是太老了？？检查这两个库版本，如果太老请升级它们。

**Comment by altairwei** [comment]
目前预编译的 AppImage GLIBC 最低要求为 GLIBC_2.17
