### ISSUE TITLE
能否增加最近打开记录的功能

### ISSUE THREAD

**Issue by AriaLyy** [altairwei/WizNotePlus#121]
类似于官方windows版本的历史打开记录，感觉这个功能还是很实用的

**Comment by altairwei** [comment]
历史打开什么？文档吗？

**Comment by AriaLyy** [comment]
这个
![image](https://user-images.githubusercontent.com/10437293/86006244-436f4a00-ba48-11ea-86a2-ed96c3a220e5.png)

**Comment by altairwei** [comment]
已经做出来了，等下一个版本发布。只是呢，没有 Windows 版本好看。

**Comment by AriaLyy** [comment]
能用就行了，总比官方那残废版的好，弱弱问一句，https://github.com/altairwei/WizNotePlus/issues/71#issuecomment-545960416 除了勾选富文本这个有没有好点的解决办法？
