### ISSUE TITLE
睡眠模式网络断开情况下 WizNotePlus 依然尝试同步

### ISSUE THREAD

**Issue by AriaLyy** [altairwei/WizNotePlus#122]
我合上了盖子，并且在回家的路上，还会自动触发同步
![image](https://user-images.githubusercontent.com/10437293/86128616-2d2ec000-bb14-11ea-8ef3-465d862352bd.png)

**Comment by altairwei** [comment]
你想要的行为是 “睡眠时 WizNotePlus 停止同步” 吗？

**Comment by altairwei** [comment]
或者说自动检查网络状况，如果网络断开则停止同步，网络重连后自动同步。

**Comment by AriaLyy** [comment]
合上盖子不自动同步

**Comment by altairwei** [comment]
v2.11.2 已修复

**Comment by ChloemoShaw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢来信。我将尽快给您回复。
