### ISSUE TITLE
maoxian剪辑的公众号页面，本地wiznote打开正常，同步后，web版本异常

### ISSUE THREAD

**Issue by 668477** [altairwei/WizNotePlus#123]
剪辑下来的web公众号，本地能正常展示，但是上传到docker版本的web上无法正常展示。显示图片来自公众号，其他平台不可引用。
手动拼接图片url路径发现图片已经上传。
本地检查源码
`<img class="rich_pages" data-ratio="0.5399449035812672" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/FOh11C4BDicQic3jRptDU8YXLobwWg93llhibUMR8gTovLJl4OQYQK7licpH1nzRiaGZibFKoYhZv7xf17hd80spibIjQ/640?wx_fmt=png" data-type="png" data-w="726" style="width: 677px !important; height: auto !important; visibility: visible !important;" _width="677px" data-fail="0" src="file:///C:/Users/XXXXX/AppData/Local/Temp/WizNote/7ce7c584-40ef-41ae-bc9a-becc26e9fb74/index_files/1593522760-509d38d8aa360cb293e5d0b0bfe6c9d9.webp">`

上传到服务器上后web版本查看源码
`<img class="rich_pages" data-ratio="0.5399449035812672" data-s="300,640" data-type="png" data-w="726" style="width: 677px !important; height: auto !important; visibility: visible !important;" data-fail="0" src="https://mmbiz.qpic.cn/mmbiz_png/FOh11C4BDicQic3jRptDU8YXLobwWg93llhibUMR8gTovLJl4OQYQK7licpH1nzRiaGZibFKoYhZv7xf17hd80spibIjQ/640?wx_fmt=png">`

手动查看web版本上有上传webp文件

**Comment by altairwei** [comment]
WizNotePlus 什么版本？

**Comment by altairwei** [comment]
你把这个网页提供一下呢。

**Comment by 668477** [comment]
Version: 2.8.0
Development Stage: stable.0
Build against: Qt 5.14.2
Build Time: Jun 27 2020 10:08:09

**Comment by 668477** [comment]
https://mp.weixin.qq.com/s?__biz=MzIwMDk1MjMyMg==&mid=2247485180&idx=1&sn=73ee714315eafd6d0f18ae940f57a147&chksm=96f41991a183908795c3c458b998b45212a4e0b1432a8525948fa1ba793f1dafb43b9acfadb2&mpshare=1&scene=1&srcid=&sharer_sharetime=1593422158697&sharer_shareid=57a78a278ec493834fc5ebe9dc10a417&key=0b1033424c0eb9587f44fb7556765a3a30a7c6d5b8de264c947f12aa965ca58c57863fa8376fa8c5c6ef0bdea21f2be13a1a2be6cc3557aad73d36b65fe223deeee5fe97faddb28c265d32863a81ee49&ascene=1&uin=MTQ5MjAwNzE0MQ%3D%3D&devicetype=Windows+10+x64&version=62090523&lang=zh_CN&exportkey=Aa%2Beki7aCdzCUf%2BW2zxfKPY%3D&pass_ticket=NtycyMNrJxhJfMtiQPKtIJSmdggJ9kwvqfVPqJ843658oK%2BvzGxgWGl67fqqxJxB

公众号的用maoxian剪辑下来，在本地看都是正常显示图片。但是上传到docker版本的wizserver用web版本查看图就不能正常显示。

**Comment by altairwei** [comment]
我测试了一下，官方服务端的 Web App 也会出现这个问题。

**Comment by altairwei** [comment]
你试试 WizNote 官方 Windows 客户端，用 devtools 看看图片是否需要从微信服务器加载？

**Comment by 668477** [comment]
因为是maoxian剪辑的，貌似只支持wiznoteplus，不支持官方的客户端。

**Comment by altairwei** [comment]
我觉得可能是 Web App 渲染问题，把 `data-src` 当成图片地址渲染了。

**Comment by 668477** [comment]
> 我觉得可能是 Web App 渲染问题，把 `data-src` 当成图片地址渲染了。

是的，感觉是这个问题。

**Comment by 668477** [comment]
我现在的临时快速解决办法是，剪辑后，到wiznoteplus里面，选择编辑器用notepad++打开，替换全部的data-src= 成 data=，再update就可以在web上面打开了。

**Comment by altairwei** [comment]
这个问题有点难处理，因为主要问题在于 Web App ，如果让 MaoXian WebClipper 自动替换 `data-src` 的话，这就太特例了。

**Comment by 668477** [comment]
> 这个问题有点难处理，因为主要问题在于 Web App ，如果让 MaoXian WebClipper 自动替换 `data-src` 的话，这就太特例了。

ok,那我和官方沟通下。临时先用自己的办法对付着用。感谢。
