### ISSUE TITLE
Mac版可以设置第三方编辑器吗？

### ISSUE THREAD

**Issue by kakushang** [altairwei/WizNotePlus#124]
请问Mac版可以设置第三方编辑器吗？目前没有找到

**Comment by altairwei** [comment]
可以，参考 [外部编辑器配置方法](https://github.com/altairwei/WizNotePlus/wiki/%E5%A4%96%E9%83%A8%E7%BC%96%E8%BE%91%E5%99%A8%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95) 。如果图片无法加载，请关注为知社区订阅号，在历史文章中找到外部编辑器配置方法。

**Comment by poisonoff** [comment]
请问Mac版第三方编辑器设置入口在哪里呀..看了一圈也没发现。。
