### ISSUE TITLE
Markdown的quote行为似乎和github有些区别

### ISSUE THREAD

**Issue by adamhj** [altairwei/WizNotePlus#125]
客户端版本：2.8.0 rc1

示例：
```
* line one
  > quote content
  * nested list
* line two 
```

github的渲染效果：
* line one
  > quote content
  * nested list
* line two 

WizNotePlus的渲染效果：
![wiznoteplus_bug1](https://user-images.githubusercontent.com/1115256/87531455-50d13900-c6c4-11ea-848a-47688866e616.png)

GitHub Flavored Markdown Spec里有一个类似的示例讲这种情况下不应该触发lazy continuation
https://github.github.com/gfm/#example-216

**Comment by altairwei** [comment]
是的，这应该是官方富文本编辑器中的 Markdown 渲染引擎的问题，估计版本比较旧了。
