### ISSUE TITLE
请问笔记的服务端开源了吗？

### ISSUE THREAD

**Issue by doulejian** [altairwei/WizNotePlus#126]

**Comment by altairwei** [comment]
没有开源，为知官方只公开了 API

**Comment by AriaLyy** [comment]
如果自己有群晖dns或云服务，可以使用官方的dockcer镜像，5个人以下免费

**Comment by mika-cn** [comment]
找了半天没找到项目，只有 docker 镜像，试着 pull 了下，乖乖，快 1 个G 。溜了溜了……

**Comment by altairwei** [comment]
> 找了半天没找到项目，只有 docker 镜像，试着 pull 了下，乖乖，快 1 个G 。溜了溜了……

这个 docker 镜像我解包开来看过，里面的服务端代码被编译成了 V8 的字节码。所以，总的来说这个为知笔记的服务端是闭源但是免费使用的。

**Comment by mika-cn** [comment]
@altairwei 

你跑起来过？ 我感觉如果需要离线跑这个，还需要在本地搭一个邮件服务。

另，现在 WizNotePlus 只能在 百毒网盘下？ 我刚读了下编译流程，有点复杂的样子。

**Comment by altairwei** [comment]
> @altairwei
> 
> 你跑起来过？ 我感觉如果需要离线跑这个，还需要在本地搭一个邮件服务。
> 
> 另，现在 WizNotePlus 只能在 百毒网盘下？ 我刚读了下编译流程，有点复杂的样子。

为知笔记的服务端 docker，我在 VPS 上跑过，有不少用户也在自己服务器或者群晖 NAS 上运行着。本地运行这个 docker 我只听说过一个用户尝试过，不过跑这个 docker 为什么现需要一个邮件服务呢？

WizNotePlus 直接在 GitHub release 的 assets 就能下载。提供百度网盘只是因为 GitHub 被墙，有些用户下载速度太慢。

**Comment by mika-cn** [comment]
> 为知笔记的服务端 docker，我在 VPS 上跑过，有不少用户也在自己服务器或者群晖 NAS 上运行着。本地运行这个 docker 我只听说过一个用户尝试过，不过跑这个 docker 为什么现需要一个邮件服务呢？

> WizNotePlus 直接在 GitHub release 的 assets 就能下载。提供百度网盘只是因为 GitHub 被墙，有些用户下载速度太慢。

我把這個 docker 跑起來了，之前看到 wiznote 官網的截圖，以爲註冊是需要郵件驗證，所以猜想會需要一個郵件服務， 跑起來後才知道不用。這個 docker 挺費內存的，沒啓用之前整個系統用了一百多兆內存，啓用後直接飆到 一個G 以上。

關於下載速度和網盤，不知道壓縮一下軟件包可不可以。對於網盤，其實可以避免的，應該有一些鏡像網站可以做到免翻牆提速。當然，這只是一個爲了減少訪問障礙的建議。

**Comment by altairwei** [comment]
> 我把這個 docker 跑起來了，之前看到 wiznote 官網的截圖，以爲註冊是需要郵件驗證，所以猜想會需要一個郵件服務， 跑起來後才知道不用。這個 docker 挺費內存的，沒啓用之前整個系統用了一百多兆內存，啓用後直接飆到 一個G 以上。
> 
> 關於下載速度和網盤，不知道壓縮一下軟件包可不可以。對於網盤，其實可以避免的，應該有一些鏡像網站可以做到免翻牆提速。當然，這只是一個爲了減少訪問障礙的建議。

为知笔记的 Docker 使用了 Elasticsearch 所谓全文搜索引擎，主要的内存占用是它造成的。如果你不需要全文搜索，可以照着官方教程把全文搜索引擎关掉，应该会剩下很多内存。

另外，我最近在研究 WizNotePlus 的单机模式，看看怎么实现单机模式简单。我感觉单机模式的 WizNotePlus 才是你需要的。

**Comment by mika-cn** [comment]
> 为知笔记的 Docker 使用了 Elasticsearch 所谓全文搜索引擎，主要的内存占用是它造成的。如果你不需要全文搜索，可以照着官方教程把全文搜索引擎关掉，应该会剩下很多内存。

嗯，我試試把 ElasticSearch關掉。看看能不能改善些，主要是現在所有的東西（wizServerDocker + WizNotePlus + Browser）都同時需要啓動起來，內存就有點緊張。現在都裝起來後，測試 wiznotePlus 這個存儲方式的時候就比較方便了。

> 另外，我最近在研究 WizNotePlus 的单机模式，看看怎么实现单机模式简单。我感觉单机模式的 WizNotePlus 才是你需要的。

如果實現了單機模式，就可以獨立於 wiznoteServer 了，不過感覺會挺複雜的。因爲我本身沒有使用 WizNotePlus 來管理文章，所以不太在意 WizNotePlus 有沒有單機模式。
