### ISSUE TITLE
反馈bug，近期概况没有更新

### ISSUE THREAD

**Issue by AriaLyy** [altairwei/WizNotePlus#130]
我使用的mac版本，没有退出过wiznoteplus，近期概况界面的内容就不会更新。
![image](https://user-images.githubusercontent.com/10437293/88121216-a5f6d880-cbf7-11ea-909f-086b4eca9ac2.png)

**Comment by altairwei** [comment]
这个页面不会自动更新，你需要右键菜单里面手动 Reload

**Comment by altairwei** [comment]
我突然发现，会自动更新的近期文档还是挺有用的。

**Comment by altairwei** [comment]
新版本的近期概况将会自动更新。
