### ISSUE TITLE
ubuntu16.04.6无法正常显示的问题

### ISSUE THREAD

**Issue by MedlarTea** [altairwei/WizNotePlus#131]
![image](https://user-images.githubusercontent.com/40930622/88358469-a9c65e80-cda1-11ea-85c8-7f6ffcbdd0b3.png)
但是内部是有反应的：
/home/jing/Pictures/Screenshot from 2020-07-24 11-40-34.png
![image](https://user-images.githubusercontent.com/40930622/88358684-88b23d80-cda2-11ea-81d7-259f41f3cf8d.png)

**Comment by MedlarTea** [comment]
版本为2.8.1

**Comment by MedlarTea** [comment]
请问有测试过ubuntu16哪个版本是没问题的吗，我可以为了为知plus重装 ^ ^

**Comment by altairwei** [comment]
> 请问有测试过ubuntu16哪个版本是没问题的吗，我可以为了为知plus重装 ^ ^

我明天用虚拟机测试下。

**Comment by MedlarTea** [comment]
我的电脑是联想Y7000, GTX1650, 安装的驱动为nvidia-418。我重装成16.04.05后, 为知笔记界面变成透明的；安装了nvidia-418后，再次出现上述情况。所以可能是显卡驱动的opengl渲染与该软件的冲突。

**Comment by altairwei** [comment]
原本没有问题？

**Comment by MedlarTea** [comment]
也有问题，没那么严重而已。运行官网下载的weizhi是没有问题的。

**Comment by MedlarTea** [comment]
我在联想T470p, GTX940MX, nvidia-418尝试了，也是一样的问题。在安装英伟达驱动前，启动为知笔记，为透明显示：
![image](https://user-images.githubusercontent.com/40930622/88446432-6bda4080-ce5c-11ea-9849-dc46c43b450b.png)
![image](https://user-images.githubusercontent.com/40930622/88446439-7a285c80-ce5c-11ea-89dc-670314fa0137.png)
安装nvidia-418驱动后，就完全不显示：
![image](https://user-images.githubusercontent.com/40930622/88446459-97f5c180-ce5c-11ea-9c1a-a1de0ca8277d.png)

**Comment by altairwei** [comment]
你瞧瞧 #99 ，问题是不是类似？

**Comment by MedlarTea** [comment]
哇，解决了！太感谢了太感谢了！

**Comment by altairwei** [comment]
> 哇，解决了！太感谢了太感谢了！

怎么解决的？

**Comment by altairwei** [comment]
> 哇，解决了！太感谢了太感谢了！

怎么解决的？

**Comment by MedlarTea** [comment]
不勾选"系统窗口样式"
![image](https://user-images.githubusercontent.com/40930622/88446951-edcc6880-ce60-11ea-9d5b-5aedf9f5b863.png)

**Comment by altairwei** [comment]
这个问题还存在吗？
