### ISSUE TITLE
能否增加使用系统浏览器打开url地址

### ISSUE THREAD

**Issue by AriaLyy** [altairwei/WizNotePlus#132]
官方的版本是支持直接使用默认浏览器打开点击的url的。
能否增加这个功能？

**Comment by altairwei** [comment]
WizQTClient 能够这样打开是因为它将所有超链接的打开方式都设置成了桌面默认浏览器。

WizNotePlus 因为实现了多标签功能，所以有些链接能够通过应用内的新标签页打开。想要实现既能在应用内新标签页打开又能在桌面默认浏览器中打开，有一点技术上的难题，这与 Qt 库的 QtWebEngine 的设计有关。

目前最简单实现这个功能的方式是给用户自定义的设置，选择所有超链接在应用内打开还是在默认浏览器中打开。

**Comment by AriaLyy** [comment]
我想要的是所有超链接都使用默认浏览器打开，因为内置的那个浏览器有一些超链接打不开，并且不好用

**Comment by altairwei** [comment]
> 我想要的是所有超链接都使用默认浏览器打开，因为内置的那个浏览器有一些超链接打不开，并且不好用

那你是支持增加一个 “用户设置” 来决定用什么打开超链接？

**Comment by AriaLyy** [comment]
是的

**Comment by altairwei** [comment]
已实现这个功能，请等待 v2.8.2 发布。

在应用设置 “阅读” 栏目中，新增了一个 “使用桌面默认浏览器打开所有链接” 的选项。

- 默认情况下（不勾选这个选项），Ctrl + 鼠标左键点击超链接将会在桌面默认浏览器中打开链接。
- 勾选这个选项的情况下，任何类型的超链接打开行为都会在桌面默认浏览器中进行。
