### ISSUE TITLE
没有找到更改数据文件夹位置的设置项

### ISSUE THREAD

**Issue by nexply** [altairwei/WizNotePlus#136]
RT，官方版本可以选择数据文件夹位置，本客户端是否有同样的功能？

**Comment by altairwei** [comment]
目前还未实现。

**Comment by altairwei** [comment]
你说的官方版本是 Windows 官方版本还是 WizQTClient ?

**Comment by nexply** [comment]
我说的是 Windows 官方版本

**Comment by altairwei** [comment]
v2.10 已实现此功能，允许通过环境变量 `WIZNOTE_DATA_STORE` 设置数据文件夹位置。

**Comment by abe520** [comment]
> v2.10 已实现此功能，允许通过环境变量 `WIZNOTE_DATA_STORE` 设置数据文件夹位置。

怎么使用？ mac特有？

**Comment by altairwei** [comment]
> 怎么使用？ mac特有？

全平台的特性，用法见 [客户端主要特性#自定义数据文件夹位置](https://github.com/altairwei/WizNotePlus/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%B8%BB%E8%A6%81%E7%89%B9%E6%80%A7#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%96%87%E4%BB%B6%E5%A4%B9%E4%BD%8D%E7%BD%AE)
