### ISSUE TITLE
Windows缩放124%，程序整体字体都很小

### ISSUE THREAD

**Issue by heartnn** [altairwei/WizNotePlus#139]
包括正文字体，以及editor.md里的编辑自己和预览

124%是因为125%的时候很多程序会变糊，但是124%就不会，而且系统界面也放大到125%的水平。

**Comment by altairwei** [comment]
试试设置环境变量：

```
QT_SCALE_FACTOR_ROUNDING_POLICY=1
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_SCALE_FACTOR=1.25
```

**Comment by heartnn** [comment]
设置完环境变量以后基本完美了，除了近期概况里面的字体仍然稍小（但也比原来的大了）。

**Comment by altairwei** [comment]
这几个参数你可以改一改，都试一试，看看什么搭配适合你。参考https://github.com/altairwei/WizNotePlus/wiki/HiDPI%E6%94%AF%E6%8C%81

**Comment by heartnn** [comment]
了解了，自己还是没有好号阅读wiki啊，多谢。
