### ISSUE TITLE
windows下怎么用?

### ISSUE THREAD

**Issue by kaikewang** [altairwei/WizNotePlus#14]
windows下怎么用?

**Comment by altairwei** [comment]
Windows 下得自己编译，但目前我不推荐你自己编译。虽然我在Windows能成功编译，但你在编译过程中会遇到很多问题，有些问题还比较棘手。以 WizNotePlus 目前的状态来看，是不如官方 Windows 客户端好用。在 WizNotePlus 赶得上官方版本后，我会考虑为 Windows 平台构建该应用。
