### ISSUE TITLE
外部编辑器或者单独编辑窗口保存时会导致主界面窗口被激活并在最上层显示

### ISSUE THREAD

**Issue by zzugyl** [altairwei/WizNotePlus#141]
我用的是Windows版本V2.8.1
在编辑笔记的时候，如果在“在单独窗口打开笔记”进行编辑，比如添加图片等，关闭这个单独窗口，返回标签页编辑：
这个时候标签页的该笔记并没有图片，大概需要等半分钟才显示出来。
如果我没等待，直接编辑的话，导致该笔记刚刚添加的图片丢失。
这一点通过历史版本可以看到，中间经历了一个有图片的版本，然后最新的版本没图片。
给我的感觉是“在单独窗口打开笔记”的内容，需要经过网络同步到服务器之后，再同步下来到标签页编辑器。这个过程反了吧？

**Comment by zzugyl** [comment]
Linux版本V2.8.1
也是同样的问题。

**Comment by altairwei** [comment]
标签页编辑用的是内部富文本编辑器吧？

**Comment by altairwei** [comment]
我测试了一下，只有标签页中的编辑器出于编辑状态时 (阅读状态没问题)，新窗口中编辑器更新的数据才无法同步。

**Comment by zzugyl** [comment]
如果标签页中的编辑器出于“编辑状态”，这个时候点击“在单独窗口打开笔记”，标签页的笔记会立刻变成“阅读状态”。
我这边“在单独窗口打开笔记”，插入几张图片，然后等半分钟，标签页的笔记才会同步。对比本地的印象笔记这个过程则是先本地同步，也就是“单独窗口”打开的笔记任意添加内容，标签页的笔记1秒内完成同步，而云同步需要等到固定的时间。

**Comment by zzugyl** [comment]
是否通过配置改成实时自动本地同步，然后再手动或者定时云同步？
有个操作可以实现：
在“单独窗口”编辑后，按“Ctrl+S”保存，则会立刻同步到标签页笔记。但是有个缺点，这个“单独窗口”会被切到后台。

**Comment by altairwei** [comment]
是这样的，在 “单独窗口打开笔记” 中做出的任何变更，在你 Ctrl+S 或者按下保存按钮前，都是仅仅临时内容，之所以你等待半分钟才可以看见标签页对应笔记同步，是因为半分钟后编辑器会自动保存。

**Comment by zzugyl** [comment]
WizNotePlus在 “单独窗口打开笔记” 进行编辑，即便不按 Ctrl+S ，它也会每隔1分钟自动保存，同时把当前编辑窗口切换到后台。这个体验不好，会打断正在进行的写作。
WizNote原版本没有这个问题，也是1分钟自动保存，但是不切换窗口。

**Comment by altairwei** [comment]
> WizNotePlus在 “单独窗口打开笔记” 进行编辑，即便不按 Ctrl+S ，它也会每隔1分钟自动保存，同时把当前编辑窗口切换到后台。这个体验不好，会打断正在进行的写作。
> WizNote原版本没有这个问题，也是1分钟自动保存，但是不切换窗口。

那我修一下这个 BUG

**Comment by altairwei** [comment]
抱歉了，这个 BUG 我尝试了很久，只能定位到信号源，没有办法定位到问题真正发生的地方。这个 BUG 可能暂时没法修复了。

**Comment by altairwei** [comment]
目前这个问题诱发的原因是笔记保存时导致的主界面文档页面 reload 事件。当 `QWebEngineView::load(QUrl::fromLocalFile(strFileName));` 被执行后，QWebEngineView 可能发出了一个尚未被找出的信号，导致主界面窗口被激活了。

**Comment by altairwei** [comment]
通过查看 QtWebEngine 模块源代码，终于定位了问题所在：

```C++
static void Navigate(WebContentsAdapter *adapter, const content::NavigationController::LoadURLParams &params)
{
    Q_ASSERT(adapter);
    adapter->webContents()->GetController().LoadURLWithParams(params);
    adapter->focusIfNecessary();
    adapter->resetSelection();
}

void WebContentsAdapter::focusIfNecessary()
{
    CHECK_INITIALIZED();
    const WebEngineSettings *settings = m_adapterClient->webEngineSettings();
    bool focusOnNavigation = settings->testAttribute(WebEngineSettings::FocusOnNavigationEnabled);
    if (focusOnNavigation)
        m_webContents->Focus();
}
```

原来是因为某些原因设置了 FocusOnNavigationEnabled ：

```C++
QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::FocusOnNavigationEnabled, true);
```

**Comment by altairwei** [comment]
> WizNotePlus在 “单独窗口打开笔记” 进行编辑，即便不按 Ctrl+S ，它也会每隔1分钟自动保存，同时把当前编辑窗口切换到后台。这个体验不好，会打断正在进行的写作。
> WizNote原版本没有这个问题，也是1分钟自动保存，但是不切换窗口。

@zzugyl 你提到的这个问题已经修复了。

但是你在此 issue 最开始提到的问题我依然不是很明白，现在你觉得依然还是一个问题吗？

**Comment by zzugyl** [comment]
还是没有修复哦。一共2个问题，我录2个视频你看一下吧。
https://www.bilibili.com/video/BV1E44y1t7sb/  图片没有实时保存 丢了
https://www.bilibili.com/video/BV1h64y187vT/  1:15编辑窗口被强制关闭了

**Comment by altairwei** [comment]
> 还是没有修复哦。

"主窗口在保存文档时被激活，从而打断写作体验" 这个问题修复了，还没有发布。

**Comment by altairwei** [comment]
> https://www.bilibili.com/video/BV1E44y1t7sb/ 图片没有实时保存 丢了

我测试了下，发现问题了：直接关闭 “单独编辑窗口” ，笔记保存时没有触发 “笔记内容变更信号” 。

如果在 “单独编辑窗口” 按保存键，内容是可以正常被同步到标签页的。

**Comment by altairwei** [comment]
> https://www.bilibili.com/video/BV1h64y187vT/ 1:15编辑窗口被强制关闭了

这个问题亲测已在 v2.9.1 修复，等几天就发布。

**Comment by altairwei** [comment]
@zzugyl 最新版本 v2.9.1 已发布，你试用下是否问题都解决了？

**Comment by zzugyl** [comment]
v2.9.1 我遇到的两个问题，已经修复了。
B站视频我就删除了。
