### ISSUE TITLE
编译错误，这是怎么写？

### ISSUE THREAD

**Issue by Travis990** [altairwei/WizNotePlus#142]
![image](https://user-images.githubusercontent.com/6883210/95282031-19b99080-088b-11eb-826d-6dfa5b393a16.png)

**Comment by altairwei** [comment]
你的 powershell 版本较低，不支持 `&&` 语法。你试试将这两句分开先后执行。

**Comment by Travis990** [comment]
![Uploading image.png…]()
分开执行是这样写吗？

**Comment by Travis990** [comment]
分开执行怎么写：
$env:QT_INSTALL_PREFIX = "D:\Qt\Qt5.14.2\5.14.2\msvc2017_64"
.\.ci\build.ps1 "$PWD" "$PWD\_build"

**Comment by altairwei** [comment]
就是这样：

```powershell
$env:QT_INSTALL_PREFIX = "C:\path\to\qt\msvc2017_64"
.\.ci\build.ps1 "$PWD" "$PWD\_build"
```

**Comment by Travis990** [comment]
谢谢 我看一下为啥脚本禁止了
![image](https://user-images.githubusercontent.com/6883210/95282788-bdf00700-088c-11eb-994c-f788798becf3.png)

**Comment by altairwei** [comment]
你查查，应该是 powershell 脚本的安全限制，你改一下系统设置就行了。

**Comment by Travis990** [comment]
可以了，谢谢，我继续编译

**Comment by Travis990** [comment]
![image](https://user-images.githubusercontent.com/6883210/95283218-d3b1fc00-088d-11eb-9c04-65194f894ef7.png)
Unknown CMake command "conan_check".

**Comment by altairwei** [comment]
这个文件下载失败了 ，你试试手动下载？众所周知的墙的原因。

**Comment by Travis990** [comment]
手动式可以下载，但是如何手动下载的cmake-conan关联到cmakefile项目中呢

**Comment by altairwei** [comment]
Qt Creator 创建的编译目录在哪，你就把这个文件拷贝到哪，覆盖掉下载失败的 conan.cmake
