### ISSUE TITLE
Linux下运行时如何进行无序列表缩进?

### ISSUE THREAD

**Issue by mareden** [altairwei/WizNotePlus#143]
Linux下使用WizNotePlus for Linux 2.8.1版本，使用无序列表(Alt+Ctrl+U)时，请问如何进行无序列表缩进控制？即为无序列表引入多层级，类似如下情况，如何在界面控制实现第二级、第三级的效果？
- 第一级
  - 第二级
  - 第二级
    - 第三级
    - 第三级
- 第一级

**Comment by mareden** [comment]
- 发现为知笔记的网页版上有编辑按钮“Indent”，正好可用于控制无序列表的缩进。但WizNotePlus上还没有找到相应的按钮，希望能得到关于此问题进一步的回复
- 同样的问题对WizNodePlus有序列表也适用

**Comment by altairwei** [comment]
确实有这个问题，除了没有缩进按钮外，也没有上下标的按钮。内部富文本编辑器的改进不是一件容易的事情，这个问题的修复可能得等等了。

**Comment by mareden** [comment]
感谢回复。将进一步等待WizNotePlus关于此bug的更新。
