### ISSUE TITLE
使用wiznoteplus2.8.1版本，点击标签页关闭按钮太快会卡死

### ISSUE THREAD

**Issue by ghl116** [altairwei/WizNotePlus#145]
如题：
使用wiznoteplus2.8.1版本，打开多个标签页，如果点击标签页关闭按钮太快会卡死。
控制台报错：
2020-10-31T21:29:37: [Console]line:  1 ,  "Uncaught ReferenceError: WizEditor is not defined"
F12打开个人开发者工具，
整个工具卡死

**Comment by altairwei** [comment]
客户端主程序会首先发出关闭请求，然后页面处理关闭逻辑，最后再统治主程序关闭页面。这个过程可能由于 Chromium 进程的运行环境出现问题而卡死。可以考虑为用户提供一个 “强制关闭标签” 的选项。

**Comment by altairwei** [comment]
已实现
