### ISSUE TITLE
移植 Wiz.Editor.md 插件到 WizNotePlus咋用的？

### ISSUE THREAD

**Issue by emperinter** [altairwei/WizNotePlus#146]
尝试下载了插件然后去插件那里配置后无发使用，选择是会闪一下页面，难不成还要配置什么参数吗？

![image](https://user-images.githubusercontent.com/20177836/98468430-54f60900-2215-11eb-8dbd-75f9ed74c132.png)

**Comment by altairwei** [comment]
从这里下载源代码：https://github.com/altairwei/Wiz.Editor.md/releases/tag/v3.0

参考 [插件安装指南](https://github.com/altairwei/WizNotePlus/wiki/%E6%8F%92%E4%BB%B6%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97) 手动安装。

**Comment by emperinter** [comment]
谢谢!我晚上试试！
