### ISSUE TITLE
如何进行“提醒”的设置？

### ISSUE THREAD

**Issue by mareden** [altairwei/WizNotePlus#151]
看到为知笔记移动版有提醒的设置（参见：[https://www.wiz.cn/android_reminders]），但没有看到WizNote有“提醒”的设置或纺编辑或能。请问如何进行“提醒”的设置？谢谢

**Comment by altairwei** [comment]
设置提醒的功能目前还没有实现。

**Comment by ChloemoShaw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢来信。我将尽快给您回复。
