### ISSUE TITLE
wiki中外部编辑器自动导入图片一章中不显示图片

### ISSUE THREAD

**Issue by grassvalley** [altairwei/WizNotePlus#154]
我先使用typora编辑markdown文件，插入图片。需要知道怎么设置才能把插入的图片自动传回wiznoteplus，但是wiki中关键的图片无法显示。
哪位呢看到图片，或者知道如何设置的，请在这里帮我解释下如何设置

**Comment by altairwei** [comment]
你看不见 Wiki 中的图片是因为 GitHub 的很多域名被 DNS 污染了，你可以试着挂一个代理查看。另外一个查看 Wiki 文档的方式是关注微信 “为知社区” 订阅号，历史文章里会有 Wiki 的文档。
