### ISSUE TITLE
递归展示子文件夹的内容

### ISSUE THREAD

**Issue by bing345** [altairwei/WizNotePlus#157]
1.点一级文件夹，能否看到二级文件夹下的文章，每次要点几次目录才能找到文章
2.客户端好久没更新了，期待早点更新，多一点小惊喜

**Comment by altairwei** [comment]
你想要的这个功能还没有实现。其实 WizNotePlus 已经有新功能，只是我没空发布。:pensive:

**Comment by bing345** [comment]
@altairwei 早点更新阿。

**Comment by altairwei** [comment]
与 #113 相同。

**Comment by altairwei** [comment]
v2.9.0 已经实现此功能。
