### ISSUE TITLE
v2.7.0 MacOS 版本错误-使用外部编辑器篡改文件

### ISSUE THREAD

**Issue by sinlov** [altairwei/WizNotePlus#16]
- OS 

ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

- Software https://github.com/altairwei/WizNotePlus/releases/tag/v2.7.0

- Issues Info

当添加外部编辑器，例如 Typora，或者 Sublime Text时，打开本来为 Markdown 源码的笔记

1. 不能唤器外部编辑器打开
1. 同时，Markdown的内容被修改成 Markdown 渲染后的 HTML 格式
1. 最终导致文档因为这个功能被篡改

**Comment by altairwei** [comment]
你查看了外置编辑器的 Wiki 教程了吗？[外部编辑器配置方法](https://github.com/altairwei/WizNotePlus/wiki/%E5%A4%96%E9%83%A8%E7%BC%96%E8%BE%91%E5%99%A8%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95) 。
正确配置后，我在 macOS 上没遇到过i提到的问题。

**Comment by altairwei** [comment]
能展示一下你外部编辑器的配置吗？以及笔记出现问题的截图。
