### ISSUE TITLE
不能修改文本字体和大小

### ISSUE THREAD

**Issue by 1322739583** [altairwei/WizNotePlus#166]
系统： 
OS: Manjaro 21.0.1 Ornara
 Kernel: x86_64 Linux 5.10.26-1-MANJARO
 Shell: zsh 5.8
 DE: KDE 5.80.0 / Plasma 5.21.3

问题描述：
appimage包2.8.2版本 选中文本后不能修改字体和大小，之前用的2.8.1.5版本也是存在这个问题，基本等于不能用。

**Comment by altairwei** [comment]
试试 2.8.3 版本，更新了内部编辑器，应该解决了这个问题。
