### ISSUE TITLE
Markdown锚点失效问题

### ISSUE THREAD

**Issue by onisuly** [altairwei/WizNotePlus#172]
比如我现在有这样一个Markdown文本
```markdown
### 列出镜像

### 列出版本
使用[列出镜像](#列出镜像)方法获取到的镜像名
```

在WizNotePlus for Linux 2.8.2中，其渲染出的HTML为
```html
<h3 id="列出镜像">列出镜像</h3>
<h3 id="列出版本">列出版本</h3>
<p>使用<a href="#列出镜像">列出镜像</a>方法获取到的镜像名</p>
```

这样可以方便的使用`[列出镜像](#列出镜像)`链接到笔记的一个标题中。可是在2.8.3中，渲染后的HTML中标题id属性变成一个随机生成的id，而且每次打开笔记这个id都不同，所以会导致链接到标题的锚点失效
```html
<h3 id="wiz-toc-2-163971668">列出镜像</h3>
<h3 id="wiz-toc-3-123518187">列出版本</h3>
<p>使用<a href="#列出镜像">列出镜像</a>方法获取到的镜像名</p>
```

**Comment by altairwei** [comment]
这个问题涉及到为知官方内部编辑器的更新，很可能它更改了 Markdown 的渲染逻辑。因为官方的内部编辑器没有开源，所以我也不知道怎么解决这个问题。

**Comment by onisuly** [comment]
随机ID比如`wiz-toc-2-163971668`应该是wizEditorForMac.js生成的，在为知的Web和移动端好像也会生成这样的随机ID，所以PC客户端修改这个JS也就没有意义了

在标题前使用一个a标签设置锚点的方法在三端测试下来都适用
```markdown
### <a id="列出镜像"></a>列出镜像

### 列出版本
使用[列出镜像](#列出镜像)方法获取到的镜像名
```
