### ISSUE TITLE
[Mac] 通过 Close 按钮关闭窗口以后，点击 dock 上的图标不起作用，只能退出后重新打开才能显示界面

### ISSUE THREAD

**Issue by zhenzou** [altairwei/WizNotePlus#175]
![image](https://user-images.githubusercontent.com/7829073/128607869-9f309eef-cdbb-456d-a645-686d9fbdd6d4.png)

这个问题上个版本就有了

**Comment by altairwei** [comment]
双击也不行吗？

**Comment by zhenzou** [comment]
是的，单机，双击，都不行，只能退出后重新打开。

**Comment by altairwei** [comment]
我大概知道问题在哪。你会 C++ 吗？有兴趣试着修复一下这个问题吗？我没有 mac ，得用虚拟机，所以不是很方便测试。

**Comment by zhenzou** [comment]
勉强能用，不过对 QT 不熟
已经搭好环境可以 buld 了，你可以说在大概要改哪里，如果改动不多的话，我可以改一下测试一下。

**Comment by altairwei** [comment]
你试试修改 `src\WizMainWindow.cpp` 文件的 `WizMainWindow::shiftVisableStatus` 函数的逻辑。

另外参考一下两个 commit 的变动：

* 1907e3a58699f58661e38bff81b9c6345a678705
* 3f5913fd45fbd80e0d6922ef902c6f53f9421728

**Comment by zhenzou** [comment]
研究了下，应该是 a407b5da7a4124b4c9b63f6aee57724b7e54b363 这个 PR 引入的，不过如果修复了好像会引起其他问题。

**Comment by altairwei** [comment]
> 研究了下，应该是 [a407b5d](https://github.com/altairwei/WizNotePlus/commit/a407b5da7a4124b4c9b63f6aee57724b7e54b363) 这个 PR 引入的，不过如果修复了好像会引起其他问题。

你试试用条件编译，看有没办法为 mac 打一个特定的补丁。

**Comment by zhenzou** [comment]
好的，更新 PR 了。

**Comment by altairwei** [comment]
OK，我明天在 Linux 和 Windows 上测试一下。

**Comment by altairwei** [comment]
@zhenzou 我今天特地用 WizNotePlus v2.8.3 在 macOS  10.15.7 上测试了下。点击 dock 图标，弹出菜单栏，然后点击 “显示/隐藏主窗口” 可以在主窗口关闭后正常激活并显示主窗口呀？

**Comment by zhenzou** [comment]
哈哈哈，看来大佬是换 Mac 了。
@altairwei

**Comment by altairwei** [comment]
> 哈哈哈，看来大佬是换 Mac 了。

借了台 Mac 专门用于解决 WizNotePlus 的问题。
