### ISSUE TITLE
WizNotePlus输入两个词进行全文检索，查不出内容

### ISSUE THREAD

**Issue by ghl116** [altairwei/WizNotePlus#177]
如题，在官方版本上测试了一下，是可以同时输入两个词，查出来的，如输入：“java 程序”就查不出来。而且搜索选项的两个：
高级搜索和添加自定义搜索不管用。

**Comment by onisuly** [comment]
在最新的Linux版里也遇到了这个问题，貌似不支持多个单词的全文检索了，只支持标题的contains搜索

搜索时的日志如下
```
Version: WizNote QTLINUX 2.8.3
Username: username@gmail.com
Time: 2021-08-14 21:59:15

2021-08-14T21:58:54: QFSFileEngine::open: No file name specified
2021-08-14T21:58:54: "/ks/note/search/19613a1c-dbd7-45fd-af94-35e04ycb78f0?token=3ee96e66cbf3295e9e80b24e6e67726agpfdeilhhkyv1f&ss=java 程序&kb_guid=19843a1c-hrd7-43gh-af94-32e17ecb78f0"
2021-08-14T21:58:54: start search
2021-08-14T21:58:54: search time:  1
2021-08-14T21:58:54: [Search] Search failed! error:  ""
```

**Comment by altairwei** [comment]
@onisuly 感谢指出问题所在。WizNotePlus v2.8.2 有这个问题吗？

**Comment by onisuly** [comment]
> @onisuly 感谢指出问题所在。WizNotePlus v2.8.2 有这个问题吗？

在WizNotePlus v2.8.2中搜索是好的，会调用REST API进行搜索

**Comment by altairwei** [comment]
> 在WizNotePlus v2.8.2中搜索是好的，会调用REST API进行搜索

应该是我在拉取官方客户端更新时引入的变更，我会尽快把它反转过去。

**Comment by altairwei** [comment]
下面我更新一下对于全文搜索 API 的研究情况：

我笔记库中有很多 C++ 和 C# 关键字的笔记，因此分别搜索 C++ 和 C#，结果如下：

* 使用官方最新客户端搜索 "C++" 或者 "C#" ，无任何结果呈现。
* 使用 WizNotePlus v2.8.2 搜索 "C++" 或者 "C#"，无任何结果呈现。
* 使用 WizNotePlus v2.8.3 搜索 "C++" 或者 "C#"，似乎只有标题中包含关键字的文章才能呈现。

或者同时搜索 "C++ 编译"：

* 使用官方最新客户端搜索 "C++ 编译" ，仅呈现 "编译" 相关内容。
* 使用 WizNotePlus v2.8.2 搜索 "C++ 编译"，仅呈现 "编译" 相关内容。
* 使用 WizNotePlus v2.8.3 搜索 "C++ 编译"，无任何结果呈现。

**Comment by altairwei** [comment]
经过多番测试，为知笔记在线搜索似乎没有对 “单个英文字母” 或者 “符号” 建立索引。

**Comment by altairwei** [comment]
@onisuly @ghl116 能帮忙测试最新的修复吗？去这里下载：https://github.com/altairwei/WizNotePlus/actions/runs/1147335010

**Comment by onisuly** [comment]
我这边测试下来Linux版是OK的
![image](https://user-images.githubusercontent.com/8399827/130091606-e5032a3a-9d2e-4457-bea1-2ea5df0a538b.png)

**Comment by altairwei** [comment]
v2.8.4 已修复这个问题。

**Comment by altairwei** [comment]
v2.8.4 已修复这个问题。
