### ISSUE TITLE
请问能否实现笔记批量导出功能呢？

### ISSUE THREAD

**Issue by poisonoff** [altairwei/WizNotePlus#182]
非常感谢，数据迁移太艰难了

**Comment by alfoil** [comment]
同问。笔记格式基本上是 md，现在想全面转到 Obsidian。能不能将所有 md 笔记导出，并保持文件夹结构。另外，有没有方法写出笔记的元数据（标签、建立时间、修改时间）？

**Comment by altairwei** [comment]
> 同问。笔记格式基本上是 md，现在想全面转到 Obsidian。能不能将所有 md 笔记导出，并保持文件夹结构。另外，有没有方法写出笔记的元数据（标签、建立时间、修改时间）自动添加为 YAML Front Matter？

你这个需求实现起来还是挺简单的。

**Comment by altairwei** [comment]
@alfoil Markdown 的图片附件你希望以什么结构存放？

**Comment by alfoil** [comment]
我对这个没要求，图片都是存储在自己的阿里云OSS图床上的，笔记都是纯文本。

**Comment by alfoil** [comment]
> @alfoil Markdown 的图片附件你希望以什么结构存放？

我对这个没要求，图片都转存到自己的阿里云OSS图床上了，因此 md 笔记都是纯文本。

**Comment by altairwei** [comment]
> 我对这个没要求，图片都转存到自己的阿里云OSS图床上了，因此 md 笔记都是纯文本。

Obsidian 是怎么处理非图床图片的？你知道吗？

**Comment by alfoil** [comment]
> > 我对这个没要求，图片都转存到自己的阿里云OSS图床上了，因此 md 笔记都是纯文本。
> 
> Obsidian 是怎么处理非图床图片的？你知道吗？

Obsidian 是以库（Vault）为单位存储和检索文件的。本地图片可以放置在库内的任意位置，可以使用wiki链接 ![[src]] 的格式直接嵌入图片。笔记虽然都是md，但其实是md的超集。

**Comment by appotry** [comment]
同求批量导出功能

**Comment by altairwei** [comment]
> 同求批量导出功能

在搞

**Comment by altairwei** [comment]
已在 v2.11 中初步实现，更多导出笔记的需求请另开 issues
