### ISSUE TITLE
Windows编译无法完全clone依赖库

### ISSUE THREAD

**Issue by csuft** [altairwei/WizNotePlus#19]
<img width="449" alt="2018-11-29_161734" src="https://user-images.githubusercontent.com/3948137/49208277-52b48e80-f3f2-11e8-81b8-81eb795eae80.png">

**Comment by altairwei** [comment]
我还没打算在 Windows 上测试 WizNotePlus 构建脚本。虽然 WizNotePlus 确实能在 Windows 上编译，但存在很多问题。所以呢，暂时不要做这事，除非你有兴趣自己解决构建过程中可能遇到的 Bug 。

**Comment by altairwei** [comment]
v2.8.0 已经提供了预编译的Windows客户端
