### ISSUE TITLE
为知笔记重构版已经实现了linux上的体验优化

### ISSUE THREAD

**Issue by allblue** [altairwei/WizNotePlus#190]
多平台一致性体验+Markdown实时渲染+多标签+沉浸式输入模式+兼容老版本，内置了draw.io还有思维导图，同时整体有notion化的趋势但又保证了本地客户端特性，目前还在beta测试阶段，但个人感觉比稳定版体验好多了，有需求的可以尝试下

https://www.wiz.cn/zh-cn/wiznew.html

**Comment by altairwei** [comment]
没开源，不得劲，没得玩

**Comment by allblue** [comment]
> 没开源，不得劲，没得玩

按为知的风格，后续可能会开源，另个这个重构版是electron的，逆向也不难

**Comment by zzugyl** [comment]
用重构版写的编辑，在WizNotePlus打不开。
看官方的说法，重构版笔记能在官方非重构版打开，可能是最近更新的版本。

**Comment by altairwei** [comment]
> 用重构版写的编辑，在WizNotePlus打不开。 看官方的说法，重构版笔记能在官方非重构版打开，可能是最近更新的版本。

WizNote X 采用了新的编辑器（live-editor），这种笔记类型在 WizNotePlus 尚且不支持，需要等我将 live-editor 移植到 WizNotePlus 后才 OK 。

**Comment by AriaLyy** [comment]
大佬，支持WizNote X的编辑器啥时候能上啊，WizNote X流畅性真的太糟糕了

**Comment by altairwei** [comment]
> 大佬，支持WizNote X的编辑器啥时候能上啊，WizNote X流畅性真的太糟糕了

v2.11 将参考官方 Windows 客户端实现一个 “在线” 的 live-editor 编辑器，可以查看和编辑 collaboration 类型的笔记。

**Comment by allblue** [comment]
> 

用了几天winznotex，还是觉得功能简陋，引用，双链什么

**Comment by woeoio** [comment]
思源都没有私有服务端，，，搞毛线

**Comment by allblue** [comment]
> 思源都没有私有服务端，，，搞毛线

有啊，docker+网页版
