### ISSUE TITLE
支持 Lite 和重构版本的 Markdown

### ISSUE THREAD

**Issue by alluLinger** [altairwei/WizNotePlus#198]
新版的 type 应该是 `lite/markdown`，但是标题没有以 `.md` 结尾所以不会渲染

![image](https://user-images.githubusercontent.com/21037233/134479524-54620c09-f945-4e18-b4d1-3caf4af1c789.png)

btw，不知道是否会有 WizNote Lite 特有的 Markdown 语法

**Comment by altairwei** [comment]
> btw，不知道是否会有 WizNote Lite 特有的 Markdown 语法

渲染取决于内部富文本编辑器，这个 WizNotePlus 动不了。

**Comment by altairwei** [comment]
待办事项：

- [ ] 在笔记信息弹窗中展示  type 信息。
- [ ] 以 .md 或者 lite/markdown 任一条件作为判断 Markdown 的标准。
