### ISSUE TITLE
MAC 下 code is not sighed 一直被 little snitch 拦截无法联网

### ISSUE THREAD

**Issue by datacruiser** [altairwei/WizNotePlus#20]
首先非常感谢热心解答帮我解决了WizNote 占用系统资源过高的问题，然后再尝试了这个 Plus 版本后发现在 MAC 下因为 code is not sighed 的原因一直被`little snitch`拦截

**Comment by altairwei** [comment]
我没有 WizNote 官方在 Xcode 上的许可证，没法 sign code
