### ISSUE TITLE
能和为知笔记重构版并存么

### ISSUE THREAD

**Issue by bing345** [altairwei/WizNotePlus#203]
如题，能和为知笔记重构版并存么，2个软件想结合一起用。现在是替换。mac版本

**Comment by altairwei** [comment]
WizNotePlus v2.10.0 将会更改程序名称以解决这个问题。

**Comment by abe520** [comment]
> WizNotePlus v2.10.0 将会更改程序名称以解决这个问题。

能不能自定义笔记存放位置？

**Comment by altairwei** [comment]
> > WizNotePlus v2.10.0 将会更改程序名称以解决这个问题。
> 
> 能不能自定义笔记存放位置？

v2.10.0 将允许使用环境变量来改变所有笔记缓存的位置。

**Comment by bing345** [comment]
@altairwei 能尽快么，markdown我还是习惯用WizNotePlus里面插件typora来弄，重构版看似方便，直接复制markdown显示出来的字体大小都不一样

**Comment by altairwei** [comment]
> @altairwei 能尽快么，markdown我还是习惯用WizNotePlus里面插件typora来弄，重构版看似方便，直接复制markdown显示出来的字体大小都不一样

你自己改一下 WizNote.app 包的名字就能共存了啊。

**Comment by bing345** [comment]
> > @altairwei 能尽快么，markdown我还是习惯用WizNotePlus里面插件typora来弄，重构版看似方便，直接复制markdown显示出来的字体大小都不一样
> 
> 你自己改一下 WizNote.app 包的名字就能共存了啊。

果然。。谢谢

**Comment by altairwei** [comment]
v2.10 版已解决此问题
