### ISSUE TITLE
wizserver越来越离谱

### ISSUE THREAD

**Issue by abe520** [altairwei/WizNotePlus#205]
10+G笔记内容跑两天愣是跑出381G的空间占用量
![Snipaste_2021-11-10_18-27-47](https://user-images.githubusercontent.com/9929511/141098198-978559c9-0856-4064-8a1f-164385630d0f.png)

**Comment by altairwei** [comment]
这是真实物理占用？这么离谱？

**Comment by abe520** [comment]
![Snipaste_2021-11-10_18-42-21](https://user-images.githubusercontent.com/9929511/141098819-6c0ef508-65a3-411b-b733-b38da21df943.png)
还在量 看下啥东东占用

**Comment by Hothua** [comment]
Docker缓存，清理即可，物理占用应该是在overlay2目录
