### ISSUE TITLE
M1芯片的MBP安装完后打开软件无反应

### ISSUE THREAD

**Issue by zhiyuanZAG** [altairwei/WizNotePlus#207]
### 电脑信息: 
> 名称: MacBook Pro (13-inch, M1, 2020)
> 芯片: Apple M1
> 内存: 16G
> 系统版本: macOS Big Sur 11.5.2

### 现象: 
> 软件安装完成之后, 打开软件无反应, 未打开, 无报错弹框;

### 问: 
> 现有发布的安装包是不支持M1芯片(或者ARM芯片)吗?

希望能得到作者答复, 谢谢!

**Comment by altairwei** [comment]
目前还没 ARM 架构的预编译包，下个版本发布前我会探索一下能否在 CI 中交叉编译。

**Comment by zhiyuanZAG** [comment]
多谢!

**Comment by altairwei** [comment]
能关注一下为知社区订阅号，然后加入用户交流群吗？近期我可能会试一试构建 ARM 的包，到时候需要麻烦你测试下。

**Comment by zhiyuanZAG** [comment]
好的, 订阅号和交流群获取途径能发一下吗?

**Comment by altairwei** [comment]
> 好的, 订阅号和交流群获取途径能发一下吗?

项目 README 中有二维码，关注订阅号就知道怎么加群了。

**Comment by zhiyuanZAG** [comment]
好的, 我加一下.

**Comment by altairwei** [comment]
将 WizNotePlus 依赖的 CryptoPP 升级到 8.5.0 后，能够使用 rosetta2 在 M1 上转译。WizNotePlus v2.10.1 将会包含此变更。
