### ISSUE TITLE
按钮点击坐标不准

### ISSUE THREAD

**Issue by zzugyl** [altairwei/WizNotePlus#210]
最新的版本，v2.10.0，Windows版本。
所有能点击的地方，实际点击生效的地方，都需要往上偏移一点才可以点击。效果如图。
![20211213_091811 521](https://user-images.githubusercontent.com/27466768/145740523-abfca2b3-396f-4e99-9ebb-3c19663a2be7.jpg)
![20211213_091822 763](https://user-images.githubusercontent.com/27466768/145740526-fee29535-fec1-4c97-88c7-711c5774d369.jpg)
![20211213_091832 925](https://user-images.githubusercontent.com/27466768/145740529-4b12b575-84ab-4d1a-89e3-951ace9f57c3.jpg)
![20211213_091838 793](https://user-images.githubusercontent.com/27466768/145740533-e09ae66f-4648-40d6-819a-23e30527856f.jpg)

**Comment by altairwei** [comment]
你在用双屏吗？屏幕分辨率是多少？缩放倍数是多少？显示器用的显卡是集成显卡还是独立显卡，什么型号？

**Comment by zzugyl** [comment]
单个显示器，Windows7系统，分辨率1920x1080，缩放100%。集成显卡。

**Comment by altairwei** [comment]
> 单个显示器，Windows7系统，分辨率1920x1080，缩放100%。集成显卡。

你查一下集成显卡的型号，如果有 NVIDIA 独显，试着让 WizNotePlus 用独显试试看。

**Comment by zzugyl** [comment]
我只有集成显卡IntelB)HGr aphics 530

**Comment by altairwei** [comment]
你在用户交流群里面吗？

**Comment by zzugyl** [comment]
更新显卡(集成显卡)驱动之后，问题解决了。
