### ISSUE TITLE
maoxian-web-clipper有没可能再上架 Chrome 商店？

### ISSUE THREAD

**Issue by abe520** [altairwei/WizNotePlus#211]
chrome用crx 文件拖放法安装maoxian-web-clipper总有些不便

**Comment by altairwei** [comment]
参考 mika-cn/maoxian-web-clipper#212 ，看样子 Mika 不愿意再商家 Chrome 。

我有充裕时间的时候，会考虑 fork 一个新的 WebClipper 。

**Comment by abe520** [comment]
![Snipaste_2022-03-20](https://user-images.githubusercontent.com/9929511/159131664-3a982392-765d-4236-974f-840e15e4cd23.png)
有时候莫名其妙出错，（0.4.2和0.4.4）扩展重装一下又能恢复正常。
