### ISSUE TITLE
Mac M1 外部编辑器添加VS- Code不能跳转打开

### ISSUE THREAD

**Issue by sxzhou1937** [altairwei/WizNotePlus#212]
在M1 Mac11.6上安装wizPlus之后，由于编辑器比较简陋，所以使用外部编辑器VS- Code，但是无法跳转，每次都需要去指定目录下，手动打开。

经测试，这个在windows上是可以打开的。

添加外部编辑器方法
<img width="359" alt="image" src="https://user-images.githubusercontent.com/19250976/148159700-a5ee5035-1199-46cd-a0a0-0244a391dda4.png">

**Comment by sxzhou1937** [comment]
问完这个问题，突然顿悟🤣（如有打扰是在抱歉了😞
看到截图，发现app结尾的不是可执行程序。这里写一下方法：
1. 在vs-code下建立shell命令：cmd+shitf+P，输入shell command，安装到Path；
2. 终端里 type code 得到可执行命令路径；
3. 写入截图里应用程序的地址框 一般是：/usr/local/bin/code;
4. 其他设置如上截图

**Comment by altairwei** [comment]
其实你的这种写法也不对，可以参考 [外部编辑器配置方法](https://github.com/altairwei/WizNotePlus/wiki/%E5%A4%96%E9%83%A8%E7%BC%96%E8%BE%91%E5%99%A8%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95) 使用 `/usr/bin/open %1 -a Typora` 这种形式。

**Comment by sxzhou1937** [comment]
@altairwei 谢谢回复，`open -a xx`的命令要打开的文件要求在`/usr/bin`下有软连接或者指向，`vscode`默认创建在`usr/local/bin/`下，我用`open`是打不开的; 若创建到 `/usr/bin` 下 则成功了*-*。
