### ISSUE TITLE
关于wiznoteplus2.10.1客户端设置"页边距"的问题

### ISSUE THREAD

**Issue by JingbenShi668** [altairwei/WizNotePlus#213]
![image](https://user-images.githubusercontent.com/39040502/148959665-5f75a535-4f8c-4cef-a0a1-ca3e600e25c1.png)
你好，这个页边距设置好像是不起作用的呀？😊

**Comment by altairwei** [comment]
这个只对富文本编辑器写下的文档起作用，对 Markdown 不起作用。

**Comment by JingbenShi668** [comment]
> 这个只对富文本编辑器写下的文档起作用，对 Markdown 不起作用。

你好，我用为知笔记的话，是不写Markdown的，我基本都是如下图去编辑，这应该是富文本编辑模式吧？
![image](https://user-images.githubusercontent.com/39040502/148962384-48d987db-54a0-4b88-ae23-734360ded886.png)

**Comment by JingbenShi668** [comment]
@altairwei 期待您的回复哈，这几天被为知笔记的问题搞得头痛，突然发现您做的这个产品满符合我的需求的😊

**Comment by altairwei** [comment]
> 你好，我用为知笔记的话，是不写Markdown的，我基本都是如下图去编辑，这应该是富文本编辑模式吧？

这个是富文本编辑模式。

**Comment by JingbenShi668** [comment]
> > 你好，我用为知笔记的话，是不写Markdown的，我基本都是如下图去编辑，这应该是富文本编辑模式吧？
> 
> 这个是富文本编辑模式。

![image](https://user-images.githubusercontent.com/39040502/148968056-88c140dc-70f2-4886-8c7b-9cfa21571248.png)
但是我调节页边距后貌似没起作用呢？是需要重启软件吗？😊

**Comment by altairwei** [comment]
> 但是我调节页边距后貌似没起作用呢？是需要重启软件吗？

首先右键刷新一下文档页面，然后截图给我看看。这个 “页边距” 调整的是左右两侧的边距。

**Comment by JingbenShi668** [comment]
你好，我右键的话是没有"刷新"选项的呀？
![image](https://user-images.githubusercontent.com/39040502/148968712-78ab052a-4f24-481d-b891-acefb3fc32bc.png)

**Comment by altairwei** [comment]
> 你好，我右键的话是没有"刷新"选项的呀？

切换回 “阅读” 模式。

**Comment by JingbenShi668** [comment]
> > 你好，我右键的话是没有"刷新"选项的呀？
> 
> 切换回 “阅读” 模式。

可以了，可以了，感谢，感觉你的这个客户端比官方的好用很多，衷心感谢你们优秀的工作😊～

**Comment by altairwei** [comment]
> 感觉你的这个客户端比官方的好用很多

WizNotePlus 成立的初衷就是想要改善官方客户端的用户体验。

**Comment by JingbenShi668** [comment]
> > 感觉你的这个客户端比官方的好用很多
> 
> WizNotePlus 成立的初衷就是想要改善官方客户端的用户体验。

嗯，好的，你们的回复也很及时，之后就用wiznotePlus了，优秀的软件🎉🎉🎉～

**Comment by JingbenShi668** [comment]
我的技术栈是容器、k8s这块儿，如果需要的话，我很乐意跟大家一块儿来改善wiznote哈😊～
