### ISSUE TITLE
关于mac客户端command+上键/下健快速定位到文档最顶端/最底端的问题

### ISSUE THREAD

**Issue by JingbenShi668** [altairwei/WizNotePlus#214]
你好，是这样的，mac中wiznote客户端中command+上键/下健是可以快速定位到文档最顶端/最底端的，但是在wiznotePlus中，组合键位“command+上键/下健”功能出现了重合的问题，即: 既可以实现“定位到文档最顶端/最底端”，又能调整笔记字体的大小，，感觉"调整笔记大小"的功能是没有必要的呢😊

**Comment by altairwei** [comment]
我不用 Mac 所以没注意到这个问题，我想一下有没有什么方案来解决这个冲突。

**Comment by JingbenShi668** [comment]
> 我不用 Mac 所以没注意到这个问题，我想一下有没有什么方案来解决这个冲突。

好的哈，"command+上键/下健"在mac上默认功能是快速定位到文档的最顶端与最底端，而“command+上键/下健”却在wiznotePlus中实现了"字体变大/变小"的功能，应该是wiznotePlus快捷键设置的问题(因为wiznote中是不存在这种情况的)，把这套快捷键组合与"字体放大/缩小"之间的监听关系给禁掉应该就可以了。  这个bug感觉还是比较难受的，😊毕竟，对于很长的笔记来说，如果不能快速定位到笔记的最底端，“慢慢拖动鼠标到页面最底端”是一件非常痛苦的事情😊～

**Comment by JingbenShi668** [comment]
您好，想问一下就是这个修复需要多长时间呢？😊因为目前想删除几行内容的话，会使用到“command+上键/下键”，字体大小也是在不断变化，还是挺难受的～

**Comment by altairwei** [comment]
我晚上修一下

**Comment by JingbenShi668** [comment]
麻烦您了哈☕️～

**Comment by JingbenShi668** [comment]
您修好如果需要测试的话，我可以来测试哈～😊

**Comment by JingbenShi668** [comment]
您好，我看您修复了，是我自己使用qt编译应用，还是您会发布一个Release版本呀？😊

**Comment by altairwei** [comment]
> 您好，我看您修复了，是我自己使用qt编译应用，还是您会发布一个Release版本呀？😊


从这个 [build](https://github.com/altairwei/WizNotePlus/actions/runs/1688221008) 中下载 MacOS_Dist 就行。

**Comment by JingbenShi668** [comment]
> > 您好，我看您修复了，是我自己使用qt编译应用，还是您会发布一个Release版本呀？😊
> 
> 从这个 [build](https://github.com/altairwei/WizNotePlus/actions/runs/1688221008) 中下载 MacOS_Dist 就行。

好的

**Comment by altairwei** [comment]
> 可以了，问题解决了哦，我测试过了呢，谢谢您😊

OK
