### ISSUE TITLE
关于"侧边栏笔记目录与笔记编辑页面共同显示，但是笔记编辑页面宽度固定而不能调整"的问题

### ISSUE THREAD

**Issue by JingbenShi668** [altairwei/WizNotePlus#215]
![image](https://user-images.githubusercontent.com/39040502/149272697-eb48915b-b279-4e36-982f-f67ff0635aac.png)

你好，情况是这样的，因为有时候需要在不同笔记之间进行切换，所以需要把侧边栏显示出来；但是有时候分屏或者想把wizNoteplus的尺寸变小一些，比如宽度变小一下，但是宽度是固定的不能调整，这样有时候wizNotePlus就会占据太多界面空间～😊您看下这个问题有没有办法解决一下呢，感觉如果用户可以自己调整wizNotePlus尺寸的话，还是挺方便的～😊
(wiznote的话侧边栏显示出来的时候，是可以调整笔记尺寸大小的)
![image](https://user-images.githubusercontent.com/39040502/149273107-25fcd0db-67b6-4fef-8d0d-8901daaab773.png)

**Comment by JingbenShi668** [comment]
我所使用的是macbook电脑，系统为10.15.5，所使用的wizNotePlus的版本为WizNotePlus-mac-v2.10.1-2，😊

**Comment by altairwei** [comment]
首先，你可以试试快捷键 F3 ，隐藏侧边栏，看看能否满足你需求。
第二，笔记编辑区域硬编码了一个最小宽度。
第三，整个笔记应用是可以调整大小的，你最好录一个视频给我看看你发现的问题。

**Comment by JingbenShi668** [comment]
1、是这样的哈，因为有时候使用为知笔记需要在不停笔记之间切换，所以侧边栏还是需要的
2、对的，其实侧边栏占据的面积不大，但是笔记编辑区域的宽度哪怕是最小化，wiznotePlus宽度也基本是占用了我屏幕2/3的(wiznote的最小宽度占用了我屏幕1/2左右), 有没有可能把"笔记编辑区域的最小宽度"调整得更小一些呢？这样就可以兼顾更多的用户了呢～😊，因为有时候分屏使用，可能需要更小尺寸的wiznotePlus呢😊
![image](https://user-images.githubusercontent.com/39040502/149278204-e3a6eddd-a2b8-4360-9960-fab41b6593a8.png)

3、整个笔记应用是可以调整大小的，但是最小化还是面积比较大呢
![image](https://user-images.githubusercontent.com/39040502/149277885-16cda691-e213-4f48-8206-f031639fc3fb.png)

**Comment by altairwei** [comment]
也就是说，你的问题其实是：笔记页面的最小尺寸限制了你对软件大小的调整？

**Comment by JingbenShi668** [comment]
> 也就是说，你的问题其实是：笔记页面的最小尺寸限制了你对软件大小的调整？

对对对，就是这个意思，就是笔记编辑页面的最小尺寸限制了调整的空间😊，感觉把那个笔记编辑页面的最小尺寸的阈值调得更小一些，整个软件就会显得比较美观，以及也就可以适应更多的需求了～😊

**Comment by JingbenShi668** [comment]
好的哈，期待您把[issue215](https://github.com/altairwei/WizNotePlus/issues/215)和[issue216](https://github.com/altairwei/WizNotePlus/issues/216)解决哈😊，蛮烦您了哈～

**Comment by JingbenShi668** [comment]
> 好的，期待您把[issue215](https://github.com/altairwei/WizNotePlus/issues/215)和[issue216](https://github.com/altairwei/WizNotePlus/issues/216)解决哈😊～麻烦您了哦～

**Comment by JingbenShi668** [comment]
您好，过年前会发新版本wizNotePlus吗？期待年前能用上修复后的WizNotePlus～😊

**Comment by altairwei** [comment]
> 您好，过年前会发新版本wizNotePlus吗？期待年前能用上修复后的WizNotePlus～blush

尽量

**Comment by JingbenShi668** [comment]
嗯，辛苦您了，希望开通打赏功能😊，可以请wizNotePlus的核心开发者喝杯咖啡☕️～

**Comment by altairwei** [comment]
> 嗯，辛苦您了，希望开通打赏功能blush，可以请wizNotePlus的核心开发者喝杯咖啡coffee～

你可以去 “为知社区” 公众号（二维码在 README），找任一文章打赏。

**Comment by JingbenShi668** [comment]
> > 嗯，辛苦您了，希望开通打赏功能blush，可以请wizNotePlus的核心开发者喝杯咖啡coffee～
> 
> 你可以去 “为知社区” 公众号（二维码在 README），找任一文章打赏。

好的哦，找到入口了，嘻嘻，天冷，记得喝杯咖啡☕️～

**Comment by altairwei** [comment]
今晚搞定这个 issue

**Comment by altairwei** [comment]
试试这个 https://github.com/altairwei/WizNotePlus/actions/runs/1698304751

**Comment by JingbenShi668** [comment]
> 试试这个 https://github.com/altairwei/WizNotePlus/actions/runs/1698304751
哇，可以的，现在已经很方便调整尺寸了，辛苦您了～😊
