### ISSUE TITLE
关于"wizNotePlus中ctrl+F搜索关键字后，关键字颜色标示消除"的问题

### ISSUE THREAD

**Issue by JingbenShi668** [altairwei/WizNotePlus#218]
1、在**wizNotePlus**中基于按键组合ctrl+F可以调出"查找 & 替换"的功能，并且**wizNotePlus**会将笔记中的关键字会被不同颜色高亮标示出来，这一点是比**wizNote**做得要好的，并且**wizNotePlus**、**wizNote**的笔记检索速度很快，是同类型笔记的一个亮点～
2、但是有一个问题就是，在**wizNotePlus**中使用"查找 & 替换"功能时，关键字的高亮标示只有在点击"查找 & 替换"框中的"删除按钮"才能被消除，其实，删除按钮是比较小的(按钮还是很小的)，每次点这个需要费点儿事儿😂～而在**wizNote**笔记中，只要点击"查找 & 替换"框之外的笔记区域，关键字的高亮标示就可以被消除，这样用起来就很方便了。
举个例子，在**wizNotePlus**中只有点击图中A区域的"删除按钮"才能消除关键字的标示，只要不点击删除按钮，文字的高亮标示就会一直存在；而在**wizNote**中可以点击区域B中的任意位置，就可以消除关键字的高亮标示了～相比之下，**wizNote**消除高亮标示就要简单很多～
![image](https://user-images.githubusercontent.com/39040502/149465093-03827581-3f93-4615-b6e0-5d4bef15f7ad.png)

3、因为用户使用一次"查找 & 替换"功能后，用户就可以找到自己所要找的关键字，并不需要关键字高亮标示的一直保存(其实一直保存“关键字的高亮表示”是没有必要的)，但是在**wizNotePlus**中只有点击"查找 & 替换"框中的"删除按钮"才能消除文字高亮标示😊～
![image](https://user-images.githubusercontent.com/39040502/149464556-0a397636-ba21-481f-900e-612b1b38a122.png)

**Comment by JingbenShi668** [comment]
这两天提的issue比较多哈，但是我是非常希望wizNotePlus越做越好的～😊

**Comment by altairwei** [comment]
我检查下

**Comment by altairwei** [comment]
> 2、但是有一个问题就是，在**wizNotePlus**中使用"查找 & 替换"功能时，关键字的高亮标示只有在点击"查找 & 替换"框中的"删除按钮"才能被消除，其实，删除按钮是比较小的(按钮还是很小的)，每次点这个需要费点儿事儿😂～而在**wizNote**笔记中，只要点击"查找 & 替换"框之外的笔记区域，关键字的高亮标示就可以被消除，这样用起来就很方便了。

“关闭 ‘查找 & 替换’ 对话框才让搜索关键字高亮消失“ 是网页浏览器或者代码编辑器中正常的页面搜索功能，有的用户就是需要这个特性。我给 ”查找 & 替换“ 对话框底部添加一个 ”关闭“ 按钮，你觉得怎么样？

**Comment by JingbenShi668** [comment]
> > 2、但是有一个问题就是，在**wizNotePlus**中使用"查找 & 替换"功能时，关键字的高亮标示只有在点击"查找 & 替换"框中的"删除按钮"才能被消除，其实，删除按钮是比较小的(按钮还是很小的)，每次点这个需要费点儿事儿😂～而在**wizNote**笔记中，只要点击"查找 & 替换"框之外的笔记区域，关键字的高亮标示就可以被消除，这样用起来就很方便了。
> 
> “关闭 ‘查找 & 替换’ 对话框才让搜索关键字高亮消失“ 是网页浏览器或者代码编辑器中正常的页面搜索功能，有的用户就是需要这个特性。我给 ”查找 & 替换“ 对话框底部添加一个 ”关闭“ 按钮，你觉得怎么样？

可以的哈，比之前要去点击那个很小的“删除按钮”操作好多了，麻烦你了哈～😊
