### ISSUE TITLE
网络图片本地化

### ISSUE THREAD

**Issue by wsxwd** [altairwei/WizNotePlus#219]
网络图片非常容易失效，将所有图片下载并转换为笔记自带图片，有效预防了上述可能遇到的问题。如果可以的话，希望您能够支持一下这个功能。
这里有个插件https://github.com/richex-cn/wiz-plugin-picture-localize 但mac无法使用

**Comment by altairwei** [comment]
OK，我移植以下这个插件。

**Comment by altairwei** [comment]
另外提醒一下，如果你使用 https://github.com/mika-cn/maoxian-web-clipper 来剪裁网页，图片都是保存到本地的，不会出现失效的问题。

**Comment by wsxwd** [comment]
谢谢大佬，我试试

**Comment by altairwei** [comment]
> 谢谢大佬，我试试

你先看看 MaoXian WebClipper 能否解决你的问题（[使用方法](https://github.com/altairwei/WizNotePlus/wiki/MaoXian%E7%BD%91%E9%A1%B5%E5%89%AA%E8%A3%81%E6%8F%92%E4%BB%B6%E8%AE%BE%E7%BD%AE)），如果可以的话，我就不尝试移植 [wiz-plugin-picture-localize](https://github.com/richex-cn/wiz-plugin-picture-localize) 了。

**Comment by wsxwd** [comment]
> > 谢谢大佬，我试试
> 
> 你先看看 MaoXian WebClipper 能否解决你的问题（[使用方法](https://github.com/altairwei/WizNotePlus/wiki/MaoXian%E7%BD%91%E9%A1%B5%E5%89%AA%E8%A3%81%E6%8F%92%E4%BB%B6%E8%AE%BE%E7%BD%AE)），如果可以的话，我就不尝试移植 [wiz-plugin-picture-localize](https://github.com/richex-cn/wiz-plugin-picture-localize) 了。

可以解决我的问题，谢谢大佬
