### ISSUE TITLE
mac 版本：如何配置外部编辑器？

### ISSUE THREAD

**Issue by ferocknew** [altairwei/WizNotePlus#221]
已经阅读此地址：
https://github.com/altairwei/WizNotePlus/wiki/%E5%A4%96%E9%83%A8%E7%BC%96%E8%BE%91%E5%99%A8%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95

也明白如何实现，但是如何在编辑器里找到此设置窗口？

![https://github.com/altairwei/WizNotePlus/wiki/images/macOS_TextEdit_Setting.png](https://github.com/altairwei/WizNotePlus/wiki/images/macOS_TextEdit_Setting.png)

**Comment by altairwei** [comment]
“编辑” 按钮右侧有个下拉菜单。

**Comment by ferocknew** [comment]
> “编辑” 按钮右侧有个下拉菜单。

我勒个去。。。。get it！
还真 隐晦。。。


感谢！
