### ISSUE TITLE
为知笔记X创建和编辑过的文档看不了，但是我使用官方的还可以看到，这个可以完善吗

### ISSUE THREAD

**Issue by yu243e** [altairwei/WizNotePlus#222]
当前客户端版本较低，无法编辑协作笔记
请升级客户端
The current client version is too low to edit collaborative notes
Please click the button to upgrade the client

**Comment by altairwei** [comment]
已经提上日程了。

**Comment by altairwei** [comment]
已在 v2.11 中实现。
