### ISSUE TITLE
希望可以固定大纲视图

### ISSUE THREAD

**Issue by ghl116** [altairwei/WizNotePlus#227]
如图，目前大纲视图是悬浮的，内容一多，很不方便查找，希望支持固定大纲视图。
![image](https://user-images.githubusercontent.com/19288752/167147716-7f6a6b23-575c-4ef0-985a-0eccaf36227e.png)

**Comment by altairwei** [comment]
初步实现了这个功能，去这下载试用下：https://github.com/altairwei/WizNotePlus/actions/runs/2323948189

然后更新 Wiz.Outline 插件：https://github.com/altairwei/Wiz.Note.Outline

发现什么问题，反馈一下。

**Comment by ghl116** [comment]
用typora打开笔记后，outline内容为空
