### ISSUE TITLE
IPV6环境下 客户端会同步失败

### ISSUE THREAD

**Issue by 99u** [altairwei/WizNotePlus#229]
![图片](https://user-images.githubusercontent.com/64686203/178645331-f5a141ce-95d6-48fd-ba9b-cdbe0a86effc.png)
私有部署，域名有解析IPV6，
IPV6环境下 ，网页版正常，使用客户端会同步失败，原因未知

**Comment by ChloemoShaw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢来信。我将尽快给您回复。

**Comment by altairwei** [comment]
方便加一下用户交流群，给我一个你私服的测试账号排查下吗？

**Comment by 99u** [comment]
Close issue
