### ISSUE TITLE
mac下编译问题

### ISSUE THREAD

**Issue by 384782946** [altairwei/WizNotePlus#23]
Start generate 3rdparty dependencies at /Users/zhangxiaojian/projects/cpp/Qt/build-WizNotePlus:

Configuration:
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
build_type=Release
[options]
[build_requires]
[env]

ERROR: OpenSSL/1.0.2p@conan/stable: 'settings.compiler' value not defined

CMake Error at CMakeLists.txt:65 (message):

  Fail to generate 3rdparty dependencies!

  -- Exit code: 1

  -- Build type: Release

-- Configuring incomplete, errors occurred!
See also "/Users/zhangxiaojian/projects/cpp/Qt/build-WizNotePlus/CMakeFiles/CMakeOutput.log".
CMake Error at package.cmake:150 (message):
  Fail to generate WizNotePlus project!

请问这cmake错误这个问题怎么解决，我执行的命令是：cmake -D QTDIR=~/Qt5.9.7/5.9.7/clang_64 -P package.cmake
系统是10.14.1

**Comment by altairwei** [comment]
请注意查阅Wiki编译教程，在 Conan 这一步你需要配置 `.conan/profile/default` 文件，另外不支持Qt5.11一下版本。

**Comment by 384782946** [comment]
你好，根据wiki纠正了一下步骤，链接阶段有错误：

      CryptoPP::Rijndael::Enc::Enc(CryptoPP::Rijndael::Enc const&) in WizEnc.cpp.o
      CryptoPP::CipherModeFinalTemplate_CipherHolder<CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)0, CryptoPP::Rijndael::Enc>, CryptoPP::CBC_Encryption>::~CipherModeFinalTemplate_CipherHolder() in WizEnc.cpp.o
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for CryptoPP::Rijndael::Base", referenced from:
      encryptAES256CbcPkcs5(unsigned char const*, int, unsigned char const*, int, QDataStream*, QDataStream*) in WizEnc.cpp.o
      decryptAES256CbcPkcs5(unsigned char const*, int, unsigned char const*, int, QDataStream*, QDataStream*) in WizEnc.cpp.o
      CryptoPP::CipherModeFinalTemplate_CipherHolder<CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)0, CryptoPP::Rijndael::Enc>, CryptoPP::CBC_Encryption>::CipherModeFinalTemplate_CipherHolder() in WizEnc.cpp.o
      CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)0, CryptoPP::Rijndael::Enc>::~BlockCipherFinal() in WizEnc.cpp.o
      CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)0, CryptoPP::Rijndael::Enc>::~BlockCipherFinal() in WizEnc.cpp.o
      non-virtual thunk to CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)0, CryptoPP::Rijndael::Enc>::~BlockCipherFinal() in WizEnc.cpp.o
      non-virtual thunk to CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)0, CryptoPP::Rijndael::Enc>::~BlockCipherFinal() in WizEnc.cpp.o
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "non-virtual thunk to CryptoPP::CBC_Decryption::ProcessData(unsigned char*, unsigned char const*, unsigned long)", referenced from:
      vtable for CryptoPP::CipherModeFinalTemplate_CipherHolder<CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)1, CryptoPP::Rijndael::Dec>, CryptoPP::CBC_Decryption> in WizEnc.cpp.o
  "non-virtual thunk to CryptoPP::CBC_Encryption::ProcessData(unsigned char*, unsigned char const*, unsigned long)", referenced from:
      vtable for CryptoPP::CipherModeFinalTemplate_CipherHolder<CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)0, CryptoPP::Rijndael::Enc>, CryptoPP::CBC_Encryption> in WizEnc.cpp.o
  "non-virtual thunk to CryptoPP::Rijndael::Dec::ProcessAndXorBlock(unsigned char const*, unsigned char const*, unsigned char*) const", referenced from:
      vtable for CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)1, CryptoPP::Rijndael::Dec> in WizEnc.cpp.o
  "non-virtual thunk to CryptoPP::Rijndael::Enc::ProcessAndXorBlock(unsigned char const*, unsigned char const*, unsigned char*) const", referenced from:
      vtable for CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)0, CryptoPP::Rijndael::Enc> in WizEnc.cpp.o
  "non-virtual thunk to CryptoPP::Rijndael::Enc::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const", referenced from:
      vtable for CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)0, CryptoPP::Rijndael::Enc> in WizEnc.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/WizNote.app/Contents/MacOS/WizNote] Error 1
make[1]: *** [src/CMakeFiles/WizNote.dir/all] Error 2
make: *** [all] Error 2
CMake Error at package.cmake:197 (message):
  Fail to build WizNotePlus project!

应该是crytopp库链接的问题，我的build-WizNotePlus/bin 目录目前是这样的：
drwxr-xr-x  3 zhangxiaojian  staff    96B Dec 11 16:06 WizNote.app
-rwxr-xr-x  1 zhangxiaojian  staff   1.9M Dec 11 11:15 libcrypto.1.0.0.dylib
lrwxr-xr-x  1 zhangxiaojian  staff    21B Dec 11 16:06 libcrypto.dylib -> libcrypto.1.0.0.dylib
-rwxr-xr-x  1 zhangxiaojian  staff   420K Dec 11 11:15 libssl.1.0.0.dylib
lrwxr-xr-x  1 zhangxiaojian  staff    18B Dec 11 16:06 libssl.dylib -> libssl.1.0.0.dylib

**Comment by altairwei** [comment]
你本地代码库位于什么分支指向什么提交？

**Comment by altairwei** [comment]
看一下你修改的 `./conan/profile/default` ，确认你 clang 版本是否正确。

**Comment by 384782946** [comment]
`[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]`

代码在master分支上

**Comment by 384782946** [comment]
(clang -v)
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix

**Comment by altairwei** [comment]
这个问题应该是 10.14 新出现的，我有空修复下。

**Comment by 384782946** [comment]
主要还是想学习代码，不想用release

**Comment by 384782946** [comment]
谢谢

**Comment by altairwei** [comment]
> 主要还是想学习代码，不想用release

有兴趣加入开发组吗？一起学习进步。

**Comment by altairwei** [comment]
> 可以呀，业余时间没问题

你邮件给我你为知笔记ID以及微信号，我把你通过为知笔记团队功能把你加入开发组以及微信群。
