### ISSUE TITLE
windows平台 表格如何插入一行或者多行呢

### ISSUE THREAD

**Issue by chenzao1024** [altairwei/WizNotePlus#231]
windows平台 表格如何插入一行或者多行呢

**Comment by altairwei** [comment]
好像没有什么直接指定插入多少行的功能，不过你把软件设置里 “页边距” 调成 32 ，会看见表格的操作 UI ，插入多行变得很方便。

**Comment by chenzao1024** [comment]
调成32好多了，感谢感谢
