### ISSUE TITLE
qt debug调试构建

### ISSUE THREAD

**Issue by xixi911** [altairwei/WizNotePlus#235]
window powershell编译没问题，但是qt调试客户端的时候构建出现下述问题：
C:\Program Files\CMake\share\cmake-3.23\Modules\CMakeTestCCompiler.cmake:69: error: The C compiler "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe" is not able to compile a simple test program. It fails with the following output: Change Dir: C:/Users/Administrator/AppData/Local/Temp/QtCreator-wUZuJt/qtc-cmake-KMNBdoJm/CMakeFiles/CMakeTmp Run Build Command(s):jom -f Makefile /nologo cmTC_5d8b4\fast && 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆    Generator: execution of make failed. Make command was: jom -f Makefile /nologo cmTC_5d8b4\fast &&

**Comment by altairwei** [comment]
jom 装了吗？

**Comment by altairwei** [comment]
conan 你装了吗

**Comment by xixi911** [comment]
> conan 你装了吗

安装了，之前跑powershell就安装了，下载exe安装的，用的1.53.0版本。。

**Comment by altairwei** [comment]
你用 Qt Create 重新跑一遍，把完整日志发出来看看。

**Comment by xixi911** [comment]
> 

The system is: Windows - 10.0.19044 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe 
Build flags: 
Id flags:  

The output was:
0
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27048 版
版权所有(C) Microsoft Corporation。保留所有权利。

CMakeCCompilerId.c
Microsoft (R) Incremental Linker Version 14.16.27048.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCCompilerId.exe 
CMakeCCompilerId.obj 


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"

The C compiler identification is MSVC, found in "C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/3.23.0/CompilerIdC/CMakeCCompilerId.exe"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe 
Build flags: 
Id flags:  

The output was:
0
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27048 版
版权所有(C) Microsoft Corporation。保留所有权利。

CMakeCXXCompilerId.cpp
Microsoft (R) Incremental Linker Version 14.16.27048.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCXXCompilerId.exe 
CMakeCXXCompilerId.obj 


Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"

The CXX compiler identification is MSVC, found in "C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/3.23.0/CompilerIdCXX/CMakeCXXCompilerId.exe"

Detecting C compiler ABI info compiled with the following output:
Change Dir: C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/CMakeTmp

Run Build Command(s):jom -f Makefile /nologo cmTC_c9d83\fast && jom: parallel job execution disabled for Makefile

	C:\QT\Qt5.12.4\Tools\QtCreator\bin\jom.exe  -f CMakeFiles\cmTC_c9d83.dir\build.make /nologo -L CMakeFiles\cmTC_c9d83.dir\build

Building C object CMakeFiles/cmTC_c9d83.dir/CMakeCCompilerABI.c.obj

	"C:\Program Files\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\cmTC_c9d83.dir\CMakeCCompilerABI.c.obj.d --working-dir=C:\Users\Administrator\AppData\Local\Temp\QtCreator-fMAdQV\qtc-cmake-YYyotTNb\CMakeFiles\CMakeTmp --filter-prefix="扅鶓??: ???畱??劘?  " -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x86\cl.exe" @C:\Users\Administrator\AppData\Local\Temp\CMakeCCompilerABI.c.obj.17524.0.jom

CMakeCCompilerABI.c
?鈷? 鍖呭惈鏂囦欢:  c:\program files\cmake\share\cmake-3.23\modules\CMakeCompilerABI.h
Linking C executable cmTC_c9d83.exe

	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_c9d83.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\mt.exe" --manifests -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\link.exe" /nologo @CMakeFiles\cmTC_c9d83.dir\objects1.rsp @C:\Users\Administrator\AppData\Local\Temp\cmTC_c9d83.exe.17524.453.jom




Detecting CXX compiler ABI info compiled with the following output:
Change Dir: C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/CMakeTmp

Run Build Command(s):jom -f Makefile /nologo cmTC_cadb3\fast && jom: parallel job execution disabled for Makefile

	C:\QT\Qt5.12.4\Tools\QtCreator\bin\jom.exe  -f CMakeFiles\cmTC_cadb3.dir\build.make /nologo -L CMakeFiles\cmTC_cadb3.dir\build

Building CXX object CMakeFiles/cmTC_cadb3.dir/CMakeCXXCompilerABI.cpp.obj

	"C:\Program Files\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\cmTC_cadb3.dir\CMakeCXXCompilerABI.cpp.obj.d --working-dir=C:\Users\Administrator\AppData\Local\Temp\QtCreator-fMAdQV\qtc-cmake-YYyotTNb\CMakeFiles\CMakeTmp --filter-prefix="扅鶓??: ???畱??劘?  " -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x86\cl.exe" @C:\Users\Administrator\AppData\Local\Temp\CMakeCXXCompilerABI.cpp.obj.30604.0.jom

CMakeCXXCompilerABI.cpp
?鈷? 鍖呭惈鏂囦欢:  c:\program files\cmake\share\cmake-3.23\modules\CMakeCompilerABI.h
Linking CXX executable cmTC_cadb3.exe

	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_cadb3.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\mt.exe" --manifests -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\link.exe" /nologo @CMakeFiles\cmTC_cadb3.dir\objects1.rsp @C:\Users\Administrator\AppData\Local\Temp\cmTC_cadb3.exe.30604.172.jom




The system is: Windows - 10.0.19044 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe 
Build flags: 
Id flags:  

The output was:
0
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27048 版
版权所有(C) Microsoft Corporation。保留所有权利。

CMakeCCompilerId.c
Microsoft (R) Incremental Linker Version 14.16.27048.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCCompilerId.exe 
CMakeCCompilerId.obj 


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"

The C compiler identification is MSVC, found in "C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/3.23.0/CompilerIdC/CMakeCCompilerId.exe"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe 
Build flags: 
Id flags:  

The output was:
0
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27048 版
版权所有(C) Microsoft Corporation。保留所有权利。

CMakeCXXCompilerId.cpp
Microsoft (R) Incremental Linker Version 14.16.27048.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCXXCompilerId.exe 
CMakeCXXCompilerId.obj 


Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"

The CXX compiler identification is MSVC, found in "C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/3.23.0/CompilerIdCXX/CMakeCXXCompilerId.exe"

Detecting C compiler ABI info compiled with the following output:
Change Dir: C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/CMakeTmp

Run Build Command(s):jom -f Makefile /nologo cmTC_6126a\fast && jom: parallel job execution disabled for Makefile

	C:\QT\Qt5.12.4\Tools\QtCreator\bin\jom.exe  -f CMakeFiles\cmTC_6126a.dir\build.make /nologo -L CMakeFiles\cmTC_6126a.dir\build

Building C object CMakeFiles/cmTC_6126a.dir/CMakeCCompilerABI.c.obj

	"C:\Program Files\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\cmTC_6126a.dir\CMakeCCompilerABI.c.obj.d --working-dir=C:\Users\Administrator\AppData\Local\Temp\QtCreator-fMAdQV\qtc-cmake-YYyotTNb\CMakeFiles\CMakeTmp --filter-prefix="扅鶓??: ???畱??劘?  " -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x86\cl.exe" @C:\Users\Administrator\AppData\Local\Temp\CMakeCCompilerABI.c.obj.28796.0.jom

CMakeCCompilerABI.c
?鈷? 鍖呭惈鏂囦欢:  c:\program files\cmake\share\cmake-3.23\modules\CMakeCompilerABI.h
Linking C executable cmTC_6126a.exe

	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_6126a.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\mt.exe" --manifests -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\link.exe" /nologo @CMakeFiles\cmTC_6126a.dir\objects1.rsp @C:\Users\Administrator\AppData\Local\Temp\cmTC_6126a.exe.28796.187.jom




The system is: Windows - 10.0.19044 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe 
Build flags: 
Id flags:  

The output was:
0
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27048 版
版权所有(C) Microsoft Corporation。保留所有权利。

CMakeCCompilerId.c
Microsoft (R) Incremental Linker Version 14.16.27048.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCCompilerId.exe 
CMakeCCompilerId.obj 


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"

The C compiler identification is MSVC, found in "C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/3.23.0/CompilerIdC/CMakeCCompilerId.exe"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe 
Build flags: 
Id flags:  

The output was:
0
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27048 版
版权所有(C) Microsoft Corporation。保留所有权利。

CMakeCXXCompilerId.cpp
Microsoft (R) Incremental Linker Version 14.16.27048.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCXXCompilerId.exe 
CMakeCXXCompilerId.obj 


Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"

The CXX compiler identification is MSVC, found in "C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/3.23.0/CompilerIdCXX/CMakeCXXCompilerId.exe"

Detecting C compiler ABI info compiled with the following output:
Change Dir: C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/CMakeTmp

Run Build Command(s):jom -f Makefile /nologo cmTC_ec44a\fast && jom: parallel job execution disabled for Makefile

	C:\QT\Qt5.12.4\Tools\QtCreator\bin\jom.exe  -f CMakeFiles\cmTC_ec44a.dir\build.make /nologo -L CMakeFiles\cmTC_ec44a.dir\build

Building C object CMakeFiles/cmTC_ec44a.dir/CMakeCCompilerABI.c.obj

	"C:\Program Files\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\cmTC_ec44a.dir\CMakeCCompilerABI.c.obj.d --working-dir=C:\Users\Administrator\AppData\Local\Temp\QtCreator-fMAdQV\qtc-cmake-YYyotTNb\CMakeFiles\CMakeTmp --filter-prefix="扅鶓??: ???畱??劘?  " -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x86\cl.exe" @C:\Users\Administrator\AppData\Local\Temp\CMakeCCompilerABI.c.obj.944.0.jom

CMakeCCompilerABI.c
?鈷? 鍖呭惈鏂囦欢:  c:\program files\cmake\share\cmake-3.23\modules\CMakeCompilerABI.h
Linking C executable cmTC_ec44a.exe

	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_ec44a.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\mt.exe" --manifests -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\link.exe" /nologo @CMakeFiles\cmTC_ec44a.dir\objects1.rsp @C:\Users\Administrator\AppData\Local\Temp\cmTC_ec44a.exe.944.235.jom




Detecting CXX compiler ABI info compiled with the following output:
Change Dir: C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/CMakeTmp

Run Build Command(s):jom -f Makefile /nologo cmTC_a4d14\fast && jom: parallel job execution disabled for Makefile

	C:\QT\Qt5.12.4\Tools\QtCreator\bin\jom.exe  -f CMakeFiles\cmTC_a4d14.dir\build.make /nologo -L CMakeFiles\cmTC_a4d14.dir\build

Building CXX object CMakeFiles/cmTC_a4d14.dir/CMakeCXXCompilerABI.cpp.obj

	"C:\Program Files\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\cmTC_a4d14.dir\CMakeCXXCompilerABI.cpp.obj.d --working-dir=C:\Users\Administrator\AppData\Local\Temp\QtCreator-fMAdQV\qtc-cmake-YYyotTNb\CMakeFiles\CMakeTmp --filter-prefix="扅鶓??: ???畱??劘?  " -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x86\cl.exe" @C:\Users\Administrator\AppData\Local\Temp\CMakeCXXCompilerABI.cpp.obj.2836.16.jom

CMakeCXXCompilerABI.cpp
?鈷? 鍖呭惈鏂囦欢:  c:\program files\cmake\share\cmake-3.23\modules\CMakeCompilerABI.h
Linking CXX executable cmTC_a4d14.exe

	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_a4d14.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\mt.exe" --manifests -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\link.exe" /nologo @CMakeFiles\cmTC_a4d14.dir\objects1.rsp @C:\Users\Administrator\AppData\Local\Temp\cmTC_a4d14.exe.2836.203.jom




The system is: Windows - 10.0.19044 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe 
Build flags: 
Id flags:  

The output was:
0
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27048 版
版权所有(C) Microsoft Corporation。保留所有权利。

CMakeCCompilerId.c
Microsoft (R) Incremental Linker Version 14.16.27048.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCCompilerId.exe 
CMakeCCompilerId.obj 


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"

The C compiler identification is MSVC, found in "C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/3.23.0/CompilerIdC/CMakeCCompilerId.exe"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe 
Build flags: 
Id flags:  

The output was:
0
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27048 版
版权所有(C) Microsoft Corporation。保留所有权利。

CMakeCXXCompilerId.cpp
Microsoft (R) Incremental Linker Version 14.16.27048.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCXXCompilerId.exe 
CMakeCXXCompilerId.obj 


Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"

The CXX compiler identification is MSVC, found in "C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/3.23.0/CompilerIdCXX/CMakeCXXCompilerId.exe"

Detecting C compiler ABI info compiled with the following output:
Change Dir: C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/CMakeTmp

Run Build Command(s):jom -f Makefile /nologo cmTC_76019\fast && jom: parallel job execution disabled for Makefile

	C:\QT\Qt5.12.4\Tools\QtCreator\bin\jom.exe  -f CMakeFiles\cmTC_76019.dir\build.make /nologo -L CMakeFiles\cmTC_76019.dir\build

Building C object CMakeFiles/cmTC_76019.dir/CMakeCCompilerABI.c.obj

	"C:\Program Files\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\cmTC_76019.dir\CMakeCCompilerABI.c.obj.d --working-dir=C:\Users\Administrator\AppData\Local\Temp\QtCreator-fMAdQV\qtc-cmake-YYyotTNb\CMakeFiles\CMakeTmp --filter-prefix="扅鶓??: ???畱??劘?  " -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x86\cl.exe" @C:\Users\Administrator\AppData\Local\Temp\CMakeCCompilerABI.c.obj.23116.0.jom

CMakeCCompilerABI.c
?鈷? 鍖呭惈鏂囦欢:  c:\program files\cmake\share\cmake-3.23\modules\CMakeCompilerABI.h
Linking C executable cmTC_76019.exe

	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_76019.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\mt.exe" --manifests -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\link.exe" /nologo @CMakeFiles\cmTC_76019.dir\objects1.rsp @C:\Users\Administrator\AppData\Local\Temp\cmTC_76019.exe.23116.188.jom




Detecting CXX compiler ABI info compiled with the following output:
Change Dir: C:/Users/Administrator/AppData/Local/Temp/QtCreator-fMAdQV/qtc-cmake-YYyotTNb/CMakeFiles/CMakeTmp

Run Build Command(s):jom -f Makefile /nologo cmTC_8142c\fast && jom: parallel job execution disabled for Makefile

	C:\QT\Qt5.12.4\Tools\QtCreator\bin\jom.exe  -f CMakeFiles\cmTC_8142c.dir\build.make /nologo -L CMakeFiles\cmTC_8142c.dir\build

Building CXX object CMakeFiles/cmTC_8142c.dir/CMakeCXXCompilerABI.cpp.obj

	"C:\Program Files\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\cmTC_8142c.dir\CMakeCXXCompilerABI.cpp.obj.d --working-dir=C:\Users\Administrator\AppData\Local\Temp\QtCreator-fMAdQV\qtc-cmake-YYyotTNb\CMakeFiles\CMakeTmp --filter-prefix="扅鶓??: ???畱??劘?  " -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x86\cl.exe" @C:\Users\Administrator\AppData\Local\Temp\CMakeCXXCompilerABI.cpp.obj.8432.0.jom

CMakeCXXCompilerABI.cpp
?鈷? 鍖呭惈鏂囦欢:  c:\program files\cmake\share\cmake-3.23\modules\CMakeCompilerABI.h
Linking CXX executable cmTC_8142c.exe

	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_8142c.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\100190~1.0\x64\mt.exe" --manifests -- "C:\PROGRA~2\Microsoft Visual Studio\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\link.exe" /nologo @CMakeFiles\cmTC_8142c.dir\objects1.rsp @C:\Users\Administrator\AppData\Local\Temp\cmTC_8142c.exe.8432.157.jom

**Comment by altairwei** [comment]
你这个日志没有出现 error 啊

**Comment by xixi911** [comment]
> 你这个日志没有出现 error 啊

我重装了系统，现在是报下面这个错误。。这个是我qt版本不对没有这个模块吗，我用的5.14.1
CMake Error at CMakeLists.txt:135 (message):
  The submodules 'framelesshelper' were not downloaded! GIT_SUBMODULE was
  turned off or failed.  Please update submodules and try again.

-- Configuring incomplete, errors occurred!

**Comment by altairwei** [comment]
这个是自动下载的 git 库，你需要在运行 CMake 是确保网络能链接到 GitHub

**Comment by xixi911** [comment]
> 这个是自动下载的 git 库，你需要在运行 CMake 时确保网络能链接到 GitHub

试了很多次不行，我手动在github上下下来放进去可以了。

**Comment by altairwei** [comment]
> 试了很多次不行，我手动在github上下下来放进去可以了。

你要确保下载的是正确的分支 `altairwei/2.0`

**Comment by xixi911** [comment]
> > 试了很多次不行，我手动在github上下下来放进去可以了。
> 
> 你要确保下载的是正确的分支 `altairwei/2.0`

是的
