### ISSUE TITLE
为知笔记升级失败

### ISSUE THREAD

**Issue by MagicStarTrace** [altairwei/WizNotePlus#240]
私有化部署的为知笔记，为什么我的一直让我升级？
docker 镜像已经是用的最新的了，是有什么升级的隐藏命令？

**Comment by altairwei** [comment]
客户端升级？

**Comment by MagicStarTrace** [comment]
wizserver 
![image](https://user-images.githubusercontent.com/15685376/210688686-dd4bed3e-a1c1-4d8a-95e7-122406481a3c.png)

**Comment by altairwei** [comment]
客户端没有什么关于服务端升级的隐藏命令。你把这个图截大一点，我看看这个通知是在哪出现的。

**Comment by MagicStarTrace** [comment]
> 客户端没有什么关于服务端升级的隐藏命令。你把这个图截大一点，我看看这个通知是在哪出现的。

登录为知网页端 提示的

**Comment by MagicStarTrace** [comment]
wiznote/wizserver:latest 目前我使用的docker 镜像

**Comment by altairwei** [comment]
> 登录为知网页端 提示的

那这个问题跟 WizNotePlus 无关，桌面客户端管不着服务端的。

**Comment by MagicStarTrace** [comment]
那应该是要去wiz server 提issue

**Comment by altairwei** [comment]
> 那应该是要去wiz server 提issue

是的，因为网页版客户端也是由 wizserver 提供的。
