### ISSUE TITLE
向表格添加行的控件被遮挡导致无法点击添加

### ISSUE THREAD

**Issue by turtleizzy** [altairwei/WizNotePlus#241]
Web版：
![image](https://user-images.githubusercontent.com/2318046/215002820-df600f79-61f1-4fb8-8b61-62d0feaddcec.png)
WizNotePlus版：
![image](https://user-images.githubusercontent.com/2318046/215002927-738329e0-1145-45d5-a58b-dc164c1ef16a.png)

P.S：如果能增加表格专用编辑按钮更好hh

**Comment by altairwei** [comment]
去软件设置里面增大页边距。之所以默认这么窄，是为了兼容官方的 annotation 功能，不然会发生位置偏移。

**Comment by turtleizzy** [comment]
赞，要不要考虑加一下专用按钮来规避这个问题呢hh

**Comment by altairwei** [comment]
> 赞，要不要考虑加一下专用按钮来规避这个问题呢hh

这个编辑器官方没开源，不好改。

**Comment by turtleizzy** [comment]
> > 赞，要不要考虑加一下专用按钮来规避这个问题呢hh
> 
> 这个编辑器官方没开源，不好改。

原来如此


以及我刚看到之前也有个[issue](https://github.com/altairwei/WizNotePlus/issues/231)提到同一个问题，要不要考虑在某个documentation或者faq之类的位置加一个条目来帮助后续的人
