### ISSUE TITLE
编译提示 Conan --version failed='拒绝访问。'

### ISSUE THREAD

**Issue by vivi20089527** [altairwei/WizNotePlus#243]
使用
windows10 
vc2019 
qt5.15

cmake提示如下。

请问大佬们，如何解决啊

Start generate 3rdparty dependencies as Release:

Conan: checking conan executable
Conan: Found program E:\Program Files\Conan\conan
CMake Error at cmake/conan.cmake:806 (message):
  Conan --version failed='拒绝访问。'
Call Stack (most recent call first):
  CMakeLists.txt:85 (conan_check)

**Comment by ChloemoShaw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢来信。我将尽快给您回复。

**Comment by altairwei** [comment]
暂时无法解决，因为太久没触发 CI 导致 JFrog 把我的 Conan 仓库回收了，等我有空更改编译和依赖方式吧。

**Comment by altairwei** [comment]
你试试编译 conan-qt 这个分支吧。

**Comment by vivi20089527** [comment]
也不行，提示
CMake Error at cmake/conan.cmake:522 (message):
  Conan install failed='6'
Call Stack (most recent call first):
  cmake/conan.cmake:759 (old_conan_cmake_install)
  CMakeLists.txt:86 (conan_cmake_run)

**Comment by altairwei** [comment]
你的网络能访问这个地址吗？https://conan.io/center/

**Comment by vivi20089527** [comment]
可以  开不开vpn都可以打开的

**Comment by vivi20089527** [comment]
删除临时编译文件夹，重新使用cmake编译后的内容


Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
The C compiler identification is MSVC 19.29.30147.0
The CXX compiler identification is MSVC 19.29.30147.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: e:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: e:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done

Start generate 3rdparty dependencies as Release:

Conan: checking conan executable
Conan: Found program C:/Program Files/Conan/conan/conan.exe
Conan: Version found Conan version 1.57.0

Conan: Automatic detection of conan settings from cmake
Conan: Detected VS runtime: MD
Conan: Settings= -s;arch=x86_64;-s;build_type=Release;-s;compiler=Visual Studio;-s;compiler.version=16;-s;compiler.runtime=MD
Conan: checking conan executable
Conan: Found program C:/Program Files/Conan/conan/conan.exe
Conan: Version found Conan version 1.57.0

Conan executing: C:/Program Files/Conan/conan/conan.exe install D:/91-code-test/WizNotePlus-feat-conan-qt/conanfile.py -s arch=x86_64 -s build_type=Release -s compiler=Visual Studio -s compiler.version=16 -s compiler.runtime=MD -g=cmake --build=missing -if=D:/91-code-test/WizNotePlus-feat-conan-qt/sln
Configuration:

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]


WARN: qt/5.15.6: requirement zlib/1.2.13 overridden by WizNotePlus/2.11.2-stable.0 to zlib/1.2.11 
WARN: qt/5.15.6: requirement openssl/1.1.1s overridden by WizNotePlus/2.11.2-stable.0 to openssl/1.1.1t 
WARN: pcre2/10.40: requirement zlib/1.2.13 overridden by qt/5.15.6 to zlib/1.2.11 
WARN: freetype/2.12.1: requirement zlib/1.2.13 overridden by qt/5.15.6 to zlib/1.2.11 
WARN: libpng/1.6.39: requirement zlib/1.2.13 overridden by freetype/2.12.1 to zlib/1.2.11 
ERROR: qt/5.15.6: Invalid configuration: Python2 must be available in PATH in order to build Qt WebEngine

CMake Error at cmake/conan.cmake:522 (message):
  Conan install failed='6'
Call Stack (most recent call first):
  cmake/conan.cmake:759 (old_conan_cmake_install)
  CMakeLists.txt:86 (conan_cmake_run)


Configuring incomplete, errors occurred!
See also "D:/91-code-test/WizNotePlus-feat-conan-qt/sln/CMakeFiles/CMakeOutput.log".

**Comment by altairwei** [comment]
你需要参考 https://github.com/altairwei/WizNotePlus/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4 安装 Qt ，然后在编译 WizNotePlus 时指定 Qt 库位置。

**Comment by ChloemoShaw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢来信。我将尽快给您回复。
