### ISSUE TITLE
Docker 部署服务端与 WizNotePlus 客户端的 SSL 握手错误

### ISSUE THREAD

**Issue by ferocknew** [altairwei/WizNotePlus#249]
如图
<img width="345" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/4d03aae4-56fa-4b24-bdb7-6f3cb8fc8afa">

**Comment by ferocknew** [comment]
mac 端客户端

**Comment by ferocknew** [comment]
windows 客户端无此问题

**Comment by altairwei** [comment]
WizNotePlus v2.11 试过吗？也有这个问题？

**Comment by altairwei** [comment]
参考 https://github.com/altairwei/WizNotePlus/issues/242 排查一下你的电脑。

**Comment by ferocknew** [comment]
<img width="1294" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/1c2c1c94-e3b9-4cfb-befe-1df09cbb3dce">

**Comment by ferocknew** [comment]
现象应该是一样的，但是，原因应该不一样。
我抓了一下日志，想知道app 的log 在macos 下，那个路径？

**Comment by altairwei** [comment]
~/.wiznote/log 默认在 HOME 目录下

**Comment by ferocknew** [comment]
<img width="698" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/bbd5eb3f-3afc-4fa6-a781-9c460610df3c">

**Comment by ferocknew** [comment]
现象的确是一样的，但是这个url 我直接curl 是可以获取到数据的。。。

**Comment by ferocknew** [comment]
<img width="455" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/b1b8687a-aade-4365-9ca7-6497907eef65">

**Comment by altairwei** [comment]
你的 docker 部署在本地还是云端？HTTP 还是 HTTPS 协议？

**Comment by ferocknew** [comment]
docker 部署在服务器上，通过nginx 反向代理https

**Comment by altairwei** [comment]
你换台电脑测试一下，看看是否为网络问题。或者你私信我一个测试账号，我来试试。

**Comment by ferocknew** [comment]
同一台mac ，官方客户端无问题，参考上面的截图。
同一个wifi 下，windows 电脑，windows 版本的 WizNotePlus 2.12.0 版本，无问题。

**Comment by altairwei** [comment]
> 同一个wifi 下，windows 电脑，windows 版本的 WizNotePlus 2.12.0 版本，无问题。

按照这个测试，有可能是你 macOS 本机的网络设置哪里出了问题，毕竟 WizNotePlus 的 Windows 版和 macOS 版本是相同代码。

**Comment by altairwei** [comment]
检查下是否有全局代理之类的。

**Comment by ferocknew** [comment]
<img width="476" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/45b4b9af-9571-4521-bb30-7f35a4ebf71d">

**Comment by altairwei** [comment]
WizNotePlus 登录框也没设置代理吧？

**Comment by ferocknew** [comment]
没有全局代理，直接 wget  也无问题。
mac 也重启过了。

您这边是否可以考虑一下有网络解析的缓存？

**Comment by ferocknew** [comment]
<img width="515" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/6be4c356-2c49-428a-8c6c-84a74bc311fa">

**Comment by ferocknew** [comment]
登录框怎么设置代理？

**Comment by altairwei** [comment]
奇怪，macOS 端没有显示代理设置的 UI，那就不用管登录框的代理了。

**Comment by altairwei** [comment]
你会抓包吗？抓一下 WizNotePlus 登录全过程，看看具体发生了什么网络错误。

**Comment by ferocknew** [comment]
macos 用什么工具抓app 的包？告诉我一个关键词，我试试

**Comment by altairwei** [comment]
> macos 用什么工具抓app 的包？告诉我一个关键词，我试试

我没有太多 macOS 使用经验，你试试 Fiddler Classic 行不行。

**Comment by ferocknew** [comment]
<img width="1050" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/817af1ee-bda9-45ac-8a3f-121e89cb4cde">

**Comment by ferocknew** [comment]
我换了一个用户名和密码，反复提示用户名和密码错误。
实际上，用户名和密码是对的。
日志如截图

**Comment by altairwei** [comment]
我看了下代码，发现很久以前官方对 macOS 端做了这个处理：

```C++
    //FIXME: 在Mac osx安全更新之后存在ssl握手问题，此处进行特殊处理
    QSslConfiguration conf = QSslConfiguration::defaultConfiguration();
    conf.setPeerVerifyMode(QSslSocket::VerifyNone);
    QSslConfiguration::setDefaultConfiguration(conf);
```

有可能与此相关。

**Comment by ferocknew** [comment]
<img width="402" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/c3eae5e7-90ca-4146-851b-54003e918223">

**Comment by ferocknew** [comment]
用的是 let 证书，虽然快到期了，但是至少还没过期

**Comment by altairwei** [comment]
抓包结果是最直接的，可以确定是否为 SSL 问题，你试过了吗？

**Comment by altairwei** [comment]
等我给你编译一个注释掉那段 SSL 代码的客户端版本试试。

**Comment by ferocknew** [comment]
<img width="605" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/3a70a2b6-22ff-4e63-81f4-86b668232c0d">

**Comment by altairwei** [comment]
等这个 https://github.com/altairwei/WizNotePlus/actions/runs/6105454811 编译完了，去 Artifacts 里面下载客户端。

**Comment by ferocknew** [comment]
这个截图忽略，是抓包软件我还需要设置一下

**Comment by ferocknew** [comment]
<img width="611" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/46d25d06-afc2-4c0e-aed6-2b46751f8788">

**Comment by ferocknew** [comment]
果然是SSL 的问题，但是，LET 证书在macos 下其他情况使用毫无问题啊

**Comment by altairwei** [comment]
> 等这个 https://github.com/altairwei/WizNotePlus/actions/runs/6105454811 编译完了，去 Artifacts 里面下载客户端。

等这个。不是你的证书问题。

**Comment by altairwei** [comment]
@ferocknew 怎么样，试过这个 hotfix 版本了吗？

**Comment by ferocknew** [comment]
<img width="602" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/053057ca-9af4-4084-9a97-2a245b30627c">

**Comment by ferocknew** [comment]
试过了，还是一样

**Comment by ferocknew** [comment]
辛苦了，我继续用官方客户端吧。
您这边如果有时间再看看这个问题，感谢

我认为，应该有网络缓存，或者证书缓存之类的

**Comment by altairwei** [comment]
更改你的 Nginx 设置，降低 TLS 版本也许有用。

**Comment by altairwei** [comment]
不对，你应该需要升级 Nginx 或者相应的 SSL 库，以支持 TLS v1.2

**Comment by altairwei** [comment]
> <img alt="image" width="602" src="https://user-images.githubusercontent.com/2178683/266209448-053057ca-9af4-4084-9a97-2a245b30627c.png">

给我看一下 Notes 里面的消息全文。

**Comment by ferocknew** [comment]
The remote SSL server rejected the connection.  The server may require a specific certificate or cipher not supported by Charles.


但是，抓包代理的证书我已经信任了

<img width="940" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/cb20a4f0-7da2-4ec3-b084-42842cb2c499">

**Comment by altairwei** [comment]
> The remote SSL server rejected the connection. The server may require a specific certificate or cipher not supported by Charles.
> 
> 但是，抓包代理的证书我已经信任了
> 
> <img alt="image" width="940" src="https://user-images.githubusercontent.com/2178683/266212483-cb20a4f0-7da2-4ec3-b084-42842cb2c499.png">

这个不是证书问题，是服务端不支持客户端提出的 TLS 版本，比如你图片中的 TLS v1.2。

**Comment by altairwei** [comment]
升级你服务端的 Nginx 或者 OpenSSL 也许能解决这个问题。或者我在 WizNotePlus 中人为降低 TLS 支持版本。

**Comment by ferocknew** [comment]
我知道了，我把TLS 升级为 1.3 了。。。。

**Comment by ferocknew** [comment]
问题解决了，把 1.2 加入反代协议就行了，感谢！

**Comment by altairwei** [comment]
> 我知道了，我把TLS 升级为 1.3 了。。。。

哦，原来是你服务端 TLS 版本太高了。

**Comment by ferocknew** [comment]
另外给一个解决的参考：
https://kb.synology.cn/zh-cn/DSM/help/DSM/AdminCenter/connection_security_advanced?version=7

<img width="740" alt="image" src="https://github.com/altairwei/WizNotePlus/assets/2178683/166e7105-58f6-4700-83c5-ea8bc3c6ba48">

**Comment by ferocknew** [comment]
可以解帖了
