### ISSUE TITLE
不能混合使用wiznote自带的编辑器和Typora

### ISSUE THREAD

**Issue by Lightmann** [altairwei/WizNotePlus#25]
一个 markdown 文件，如果使用 Typora 编辑过，保存后又在 wiznote 中编辑，下次再用 typora 编辑时，会还原到上一次 typora 编辑的版本，从而出线 wiznote 中编辑的内容丢失。有遇到同样问题的吗？

**Comment by altairwei** [comment]
是这样的，存在这个 Bug。你用内部编辑器编辑后，需要**关闭标签重新打开笔记**刷新缓存。这个 Bug 计划在下个版本更新解决。

**Comment by altairwei** [comment]
你可以去 release 页面尝试一下 2.7.3-beta.2 版本，修复了这个问题。

**Comment by Lightmann** [comment]
试用了，确实解决了一些问题。

还有个小问题：

# 结合 wiznote 和 typora 的体验

* 可以结合起来使用，但必须要同时使用。下面的操作是不行的：

在wiz笔记中用 typora 打开了 md 文件，但把 wiz 完全关闭了。这时候再在 typora 上编辑，没法直接保存到 wiz 了，即使再把 wiz 打开。
