### ISSUE TITLE
怎样才能用等号让文字高亮

### ISSUE THREAD

**Issue by Kukmoon** [altairwei/WizNotePlus#252]
==MarkDown 扩展语法支持在文字前后分别加两个等号（`==...==`）让文字高亮==。但是 WizNotePlus 不支持。请问我能不能通过修改 WizNotePlus 的渲染引擎，实现这个功能？

![用两个等号（MarkDown 语法）让文字高亮](https://github.com/altairwei/WizNotePlus/assets/16938012/fd28ff8c-c9dd-47f5-b883-083e2cd83bc5)

![用两个等号（MarkDown 语法）让文字高亮](https://github.com/altairwei/WizNotePlus/assets/16938012/232a6335-4b76-43fe-a9c8-e78c36badda7)

**Comment by altairwei** [comment]
不能，官方没开源渲染引擎。

**Comment by Kukmoon** [comment]
> 不能，官方没开源渲染引擎。

啊这，原来 WizNotePlus 也用的是官方的渲染引擎啊……
那真没办法了嘤嘤嘤，我还是用<mark>...</mark>标签吧
