### ISSUE TITLE
输入的服务端URL和实际请求的URL协议不一致

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [altairwei/WizNotePlus#264]
如题，假设在登陆到自定义服务器时，输入的URL为 `https://example.com`, 实际上请求的地址却是 `http://example.com`

Windows平台出现，其余平台未做测试

**Comment by ChloemoShaw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢来信。我将尽快给您回复。

**Comment by altairwei** [comment]
检查你服务端的设置，正常情况下客户端不会这样。

**Comment by PeanutMelonSeedBigAlmond** [comment]
检查过了，并不是服务端的问题，不论从抓包还是从用户目录的日志内看，都请求的是HTTP协议

Altair Wei ***@***.***> 于 2024年9月20日周五 08:14写道：

**Comment by PeanutMelonSeedBigAlmond** [comment]
> 检查你服务端的设置，正常情况下客户端不会这样。

方便的话，晚些时候可以提供录屏和日志

**Comment by altairwei** [comment]
你在登录窗口输入你私服地址时，需要以 https:// 开头，不能只输入域名。

**Comment by PeanutMelonSeedBigAlmond** [comment]
> 你在登录窗口输入你私服地址时，需要以 https:// 开头，不能只输入域名。

![image](https://github.com/user-attachments/assets/9fb81d31-c026-4ab4-a4ca-649259099ea6)

**Comment by altairwei** [comment]
> > 你在登录窗口输入你私服地址时，需要以 https:// 开头，不能只输入域名。
> 
> ![image](https://private-user-images.githubusercontent.com/25266280/369365439-9fb81d31-c026-4ab4-a4ca-649259099ea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjgwNjYsIm5iZiI6MTcyNjgyNzc2NiwicGF0aCI6Ii8yNTI2NjI4MC8zNjkzNjU0MzktOWZiODFkMzEtYzAyNi00YWI0LWE0Y2EtNjQ5MjU5MDk5ZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEwMjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNGZiMDY3MzFlODMzZTY3Y2QyYTA5OWFjYzRhNDYxZDQ4NzlmNWNmNGEzNGVkNzAyNTRkZmI2YTNiZjRhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2HDQeZYwZ5tNbsuXzXN2lp_4OzQgdukVTA6bGhNO8Ss)

下面不是有一个 HTTPS 408 错误吗？你确定你服务端配置正确了？而且，上面也是个 HTTPS 的请求。

**Comment by altairwei** [comment]
你最好只因此域名和 params，把 api 请求的路径给我看，不然我无法定位代码。

**Comment by PeanutMelonSeedBigAlmond** [comment]
下面408是因为我Nginx配置了HTTP请求自动跳转到HTTPS，但是因为登录请求是post，重定向之后会变成get请求，所以才会有408

直接用post请求HTTPS是没有问题的

Altair Wei ***@***.***> 于 2024年9月20日周五 18:29写道：

**Comment by PeanutMelonSeedBigAlmond** [comment]
如果方便的话，可以私聊，我提供一个测试账号和服务器地址

**Comment by altairwei** [comment]
> 如果方便的话，可以私聊，我提供一个测试账号和服务器地址

README 页面有二维码。

**Comment by PeanutMelonSeedBigAlmond** [comment]
已解决，方案如下：

若使用nginx反向代理https请求，需要在nginx配置中加入

`proxy_set_header X-Forwarded-Proto $scheme;`
