### ISSUE TITLE
分辨率问题？

### ISSUE THREAD

**Issue by yijie0710** [altairwei/WizNotePlus#27]
OS: UBUNTU 18.04
高分屏
直接运行appimage的结果
已经试过https://github.com/altairwei/WizNotePlus/issues/22　的方法，但是没有起作用～
![image](https://user-images.githubusercontent.com/33541978/51364336-a00dcc00-1b16-11e9-8953-40e07b171a09.png)

**Comment by altairwei** [comment]
你分辨率和 DPI 缩放分别多少？三个变量是否写入了 .bash_profile ？是否注销账号并重新登录 Ubuntu 桌面？

**Comment by yijie0710** [comment]
全部设置统一了之后就正常了，谢谢谢谢
