### ISSUE TITLE
整合到桌面环境失败

### ISSUE THREAD

**Issue by TyrantJoy** [altairwei/WizNotePlus#29]
按照wiki，安装了appimaged，并将APPimage文件加入到了家目录的.local/bin，以及增加了执行权限，但是在桌面环境中找不到为知笔记图标

**Comment by altairwei** [comment]
如果你使用 gnome 那么在 launcher 里面搜索 `为知笔记` ，右键收藏到桌面。重新登录账户后，图标会刷新。

**Comment by altairwei** [comment]
参考相关维基文档，使用 AppImageLauncher
