### ISSUE TITLE
Arch 上有关 Freetype 库的问题

### ISSUE THREAD

**Issue by xcffl** [altairwei/WizNotePlus#3]
Arch 系上无法运行，报错：
`symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var`
这是由于打包的 `./lib/libfreetype.so.6`（类似名字）请求系统的 `libfontconfig.so.1`。也许是因为 Arch 与 Ubuntu 的 lib 提供的东西不一样。

## 解决办法
https://gist.github.com/nemanjan00/dca98f1eb26414327e32452185916ec8
```
./WizNote-x86_64.AppImage --appimage-extract
cd squashfs-root
mv ./lib/libfreetype.so.6 ./lib/libfreetype.so.6.bak
./stremio
```
或
```
 LD_PRELOAD=/usr/lib/libfreetype.so ./WizNote-x86_64.AppImage
```

或
https://bbs.archlinux.org/viewtopic.php?pid=1766377
```
pacman -S lib32-fontconfig lib32-freetype2
```

**Comment by altairwei** [comment]
感谢提供临时解决方法，Qt GUI 依赖 Freetype 2。能否告知一下你 Arch 的系统版本以及相应的 freetype 版本。

**Comment by xcffl** [comment]
用的是 Manjaro Linux 18.0-rc1。
Freetype 2.9.1-1。

**Comment by altairwei** [comment]
> 用的是 Manjaro Linux 18.0-rc1。
> Freetype 2.9.1-1。

等一段时间我完善了打包脚本，并把编译教程写出来后，你可以尝试在 Arch 上编译并打包一个 AppImage 。

**Comment by altairwei** [comment]
@xcffl 
构建脚本写出了，你有兴趣可以尝试编译一下。

**Comment by xcffl** [comment]
我发现 Arch 下各个 library 的位置相当不同（例如 QT 的位置根据有没有 /bin/qmake 来判断不太合适）。

打算进一步研究研究。也许 Arch 下更适合直接打包传到 AUR 甚至官方仓库，你觉得呢？

或者你打包的时候按照 1 楼的解决办法，不打包 ./lib/libfreetype.so.6。亦或在启动脚本里判断，如果非 Ubuntu，执行  `LD_PRELOAD=/usr/lib/libfreetype.so`

**Comment by roachsinai** [comment]
`Arch/Manjaro`上`qt`库的路径，知道么？@altairwei

**Comment by roachsinai** [comment]
`/usr/include/qt`?

**Comment by altairwei** [comment]
> `Arch/Manjaro`上`qt`库的路径，知道么？@altairwei

你安装Qt5时自己选择了路径，而Linux 自带的大多是 Qt4 。具体编译过程请参看项目Wiki。

**Comment by xcffl** [comment]
@ roachsinai 仓库里的包确实安装在这个路径

**Comment by roachsinai** [comment]
emm，一会代码下完了，我试一下。

**Comment by roachsinai** [comment]
@xcff 嗯，好的。从仓库下载安装的。

**Comment by xcffl** [comment]
注意编译脚本里判断是否有qt包的方式不适用于 Arch，需要手动修改（或者注释掉）

**Comment by roachsinai** [comment]
@xcff 貌似路径不对

```
➜  WizNotePlus git:(master) cmake -D QTDIR=/usr/include/qt -P package.cmake

The following variables must be confirmed:

CMake Error at package.cmake:22 (message):
  

  QTDIR is not valid, Qt5 library cannot be found !

  Please define QTDIR!
```

`package.cmake`:

左边是行号
```
  3 if(NOT QTDIR)
  2     set(QTDIR /Users/altairwei/Qt5.11.1/5.11.1/clang_64)
  1 endif()
20  find_path(qt_dir "bin/qmake" ${QTDIR})                                                                                
  1 if(NOT qt_dir)
  2     message(FATAL_ERROR "\nQTDIR is not valid, Qt5 library cannot be found !\nPlease define QTDIR!")
  3 else()
  4     get_filename_component(QTDIR ${QTDIR} ABSOLUTE)
  5 endif()
```

**Comment by roachsinai** [comment]
```
➜  WizNotePlus git:(master) which qmake
/usr/bin/qmake
```

**Comment by altairwei** [comment]
> 我发现 Arch 下各个 library 的位置相当不同（例如 QT 的位置根据有没有 /bin/qmake 来判断不太合适）。
> 
> 打算进一步研究研究。也许 Arch 下更适合直接打包传到 AUR 甚至官方仓库(脚本编写难度上没什么差异)，你觉得呢？
> 
> 或者你用 Ubuntu 打包的时候按照 1 楼的解决办法，不打包 ./lib/libfreetype.so.6。亦或在启动脚本里判断，如果非 Ubuntu，执行 `LD_PRELOAD=/usr/lib/libfreetype.so`

Arch 必须从仓库安装 Qt5 吗？无法下载 Qt 官网的 official_release 来手动安装？

**Comment by xcffl** [comment]
@altairwei 当然可以，只不过从仓库安装方便快捷得多。
我本地从官网装的 qt 是 5.9 的，还没尝试下载新版，近期比较忙

**Comment by altairwei** [comment]
如果你是通过仓库安装 Qt5 的话，请把 `package.cmake` 脚本下面这段代码注释掉，并确保 `QTDIR` 指向正确位置：

```cmake
if(NOT QTDIR)
    set(QTDIR /Users/altairwei/Qt5.11.1/5.11.1/clang_64)
endif()
find_path(qt_dir "bin/qmake" ${QTDIR})
if(NOT qt_dir)
    message(FATAL_ERROR "\nQTDIR is not valid, Qt5 library cannot be found !\nPlease define QTDIR!")
else()
    get_filename_component(QTDIR ${QTDIR} ABSOLUTE)
endif()
```

**Comment by roachsinai** [comment]
```
[ 57%] Linking CXX shared library ../../libgq.so
/usr/bin/c++ -fPIC    -std=c++11 -g       -shared -Wl,-soname,libgq.so -o ../../libgq.so CMakeFiles/gumbo_query_shared.dir/Document.cpp.o CMakeFiles/gumbo_query_shared.dir/Node.cpp.o CMakeFiles/gumbo_query_shared.dir/Object.cpp.o CMakeFiles/gumbo_query_shared.dir/Parser.cpp.o CMakeFiles/gumbo_query_shared.dir/QueryUtil.cpp.o CMakeFiles/gumbo_query_shared.dir/Selection.cpp.o CMakeFiles/gumbo_query_shared.dir/Selector.cpp.o  -L/home/roach/.conan/data/OpenSSL/1.0.2p/conan/stable/package/8de045835f655eac46a5ad3b4eadbcf79dcebafd/lib  -L/home/roach/.conan/data/zlib/1.2.11/conan/stable/package/1d877a3df840030e6a8abb74c5ffb9088d08b47a/lib -Wl,-rpath,/home/roach/.conan/data/OpenSSL/1.0.2p/conan/stable/package/8de045835f655eac46a5ad3b4eadbcf79dcebafd/lib:/home/roach/.conan/data/zlib/1.2.11/conan/stable/package/1d877a3df840030e6a8abb74c5ffb9088d08b47a/lib: ../../libGumbo.a 
/usr/bin/ld: ../../libGumbo.a(parser.c.o): relocation R_X86_64_PC32 against symbol `kGumboEmptyString' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: 最后的链结失败: bad value
collect2: 错误：ld 返回 1
make[2]: *** [lib/gumbo-query/src/CMakeFiles/gumbo_query_shared.dir/build.make:178：lib/libgq.so] 错误 1
make[1]: *** [CMakeFiles/Makefile2:580：lib/gumbo-query/src/CMakeFiles/gumbo_query_shared.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2
CMake Error at package.cmake:190 (message):
  Fail to build WizNotePlus project!
```

:-(

**Comment by altairwei** [comment]
> ```
> [ 57%] Linking CXX shared library ../../libgq.so
> /usr/bin/c++ -fPIC    -std=c++11 -g       -shared -Wl,-soname,libgq.so -o ../../libgq.so CMakeFiles/gumbo_query_shared.dir/Document.cpp.o CMakeFiles/gumbo_query_shared.dir/Node.cpp.o CMakeFiles/gumbo_query_shared.dir/Object.cpp.o CMakeFiles/gumbo_query_shared.dir/Parser.cpp.o CMakeFiles/gumbo_query_shared.dir/QueryUtil.cpp.o CMakeFiles/gumbo_query_shared.dir/Selection.cpp.o CMakeFiles/gumbo_query_shared.dir/Selector.cpp.o  -L/home/roach/.conan/data/OpenSSL/1.0.2p/conan/stable/package/8de045835f655eac46a5ad3b4eadbcf79dcebafd/lib  -L/home/roach/.conan/data/zlib/1.2.11/conan/stable/package/1d877a3df840030e6a8abb74c5ffb9088d08b47a/lib -Wl,-rpath,/home/roach/.conan/data/OpenSSL/1.0.2p/conan/stable/package/8de045835f655eac46a5ad3b4eadbcf79dcebafd/lib:/home/roach/.conan/data/zlib/1.2.11/conan/stable/package/1d877a3df840030e6a8abb74c5ffb9088d08b47a/lib: ../../libGumbo.a 
> /usr/bin/ld: ../../libGumbo.a(parser.c.o): relocation R_X86_64_PC32 against symbol `kGumboEmptyString' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: 最后的链结失败: bad value
> collect2: 错误：ld 返回 1
> make[2]: *** [lib/gumbo-query/src/CMakeFiles/gumbo_query_shared.dir/build.make:178：lib/libgq.so] 错误 1
> make[1]: *** [CMakeFiles/Makefile2:580：lib/gumbo-query/src/CMakeFiles/gumbo_query_shared.dir/all] 错误 2
> make: *** [Makefile:130：all] 错误 2
> CMake Error at package.cmake:190 (message):
>   Fail to build WizNotePlus project!
> ```
> :-(

用 Git 拉取最新的 master ，把编译临时文件删除后，再重新编译。

**Comment by roachsinai** [comment]
```
Start generate 3rdparty dependencies at /home/roach/code/Git/build-WizNotePlus:


Configuration:
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

cryptopp/5.6.5@bincrafters/stable: Not found in local cache, looking in remotes...
cryptopp/5.6.5@bincrafters/stable: Trying with 'conan-center'...
ERROR: Failed requirement 'cryptopp/5.6.5@bincrafters/stable' from 'PROJECT'
ERROR: Unable to find 'cryptopp/5.6.5@bincrafters/stable' in remotes

CMake Error at CMakeLists.txt:65 (message):
  

  Fail to generate 3rdparty dependencies!

  -- Exit code: 1

  -- Build type: Release



-- Configuring incomplete, errors occurred!
See also "/home/roach/code/Git/build-WizNotePlus/CMakeFiles/CMakeOutput.log".
CMake Error at package.cmake:165 (message):
  Fail to generate WizNotePlus project!
```

昨天编译的时候没有这个问题，删除`build-WizNotePlus`文件夹之后使用proxychain-ng代理编译，还有这个错误。是网络的问题？

**Comment by altairwei** [comment]
> ```
> Start generate 3rdparty dependencies at /home/roach/code/Git/build-WizNotePlus:
> 
> 
> Configuration:
> [settings]
> os=Linux
> os_build=Linux
> arch=x86_64
> arch_build=x86_64
> compiler=gcc
> compiler.version=8
> compiler.libcxx=libstdc++11
> build_type=Release
> [options]
> [build_requires]
> [env]
> 
> cryptopp/5.6.5@bincrafters/stable: Not found in local cache, looking in remotes...
> cryptopp/5.6.5@bincrafters/stable: Trying with 'conan-center'...
> ERROR: Failed requirement 'cryptopp/5.6.5@bincrafters/stable' from 'PROJECT'
> ERROR: Unable to find 'cryptopp/5.6.5@bincrafters/stable' in remotes
> 
> CMake Error at CMakeLists.txt:65 (message):
>   
> 
>   Fail to generate 3rdparty dependencies!
> 
>   -- Exit code: 1
> 
>   -- Build type: Release
> 
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/roach/code/Git/build-WizNotePlus/CMakeFiles/CMakeOutput.log".
> CMake Error at package.cmake:165 (message):
>   Fail to generate WizNotePlus project!
> ```
> 昨天编译的时候没有这个问题，删除`build-WizNotePlus`文件夹之后使用proxychain-ng代理编译，还有这个错误。是网络的问题？

不好意思，忘了在 WiKi 中加这段：

```
conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
```

你为 Conan 添加上这个远程仓库就可以找到 CryptoPP 了 。

**Comment by altairwei** [comment]
v2.8.0-beta.2 解决这个问题了吗？

**Comment by xcffl** [comment]
解决了
