### ISSUE TITLE
2个功能建议

### ISSUE THREAD

**Issue by CodingOX** [altairwei/WizNotePlus#31]
1. 为知笔记在windows中的桌面便签功能，mac是否有可能实现？
2. 图片粘贴，我发现不能用ctrl+v 必须在编辑中利用邮件来选择粘贴图片，这个是否可以实现！

**Comment by altairwei** [comment]
桌面便签功能以后会有，Windows 端的插件会慢慢移植过来。

第二个问题应该是快捷键失效，我会检查一下。

**Comment by CodingOX** [comment]
第二个问题已经解决了！
