### ISSUE TITLE
请问下我的mac下，用emac快键键移动光标会自动按两次怎么解决？

### ISSUE THREAD

**Issue by GerrieWell** [altairwei/WizNotePlus#35]
例如在表格内，搜狗输入法按t，结果自动输入两个t。
或者按 ctrl+fbud 移动光标。自动移动两格。
官方版和这个版本都有这个问题。其他软件没事。

**Comment by altairwei** [comment]
fbud 是什么键？

**Comment by altairwei** [comment]
确实是有这个问题：光标位于单元格起始位置时，使用输入法会造成连续键入两个字母的问题。

这个问题很可能是由于表格组件响应了某种键盘输入事件导致的。但由于官方没有开源内置富文本编辑器源代码，所以我没法修复这个 bug 。

**Comment by GerrieWell** [comment]
> fbud 是什么键？

就是ctrl + f /ctrl +b  移动光标。不知为何，在我的电脑上会移动两格，而不是期待的一格。

**Comment by altairwei** [comment]
WizNotePlus 未来会更换内部富文本编辑器，所以涉及官方内部富文本编辑器的bug我都无法处理。

**Comment by GerrieWell** [comment]
还有我用最新版本没法用typora打开耶。也无法编辑。该怎么调试。

**Comment by altairwei** [comment]
> 还有我用最新版本没法用typora打开耶。也无法编辑。该怎么调试。

参考 [Wiki 文档](https://github.com/altairwei/WizNotePlus/wiki/%E5%A4%96%E9%83%A8%E7%BC%96%E8%BE%91%E5%99%A8%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95)
