### ISSUE TITLE
2.7.3在windows环境下无法运行

### ISSUE THREAD

**Issue by jzhfmm** [altairwei/WizNotePlus#37]
![image](https://user-images.githubusercontent.com/8255644/55625007-1f3ba380-57da-11e9-9e1a-887dc390241d.png)
提示无法打开zlib.h 文件

**Comment by altairwei** [comment]
你参考下 [客户端编译步骤](https://github.com/altairwei/WizNotePlus/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4) ，找不到库文件是因为你没有使用 conan 安装依赖。另外，这篇维基有一些过时了，我还没空更新。

WizNotePlus 在 Windows 端有性能缺陷以及存在一些严重 bug ，所以目前尽量不要在 Windows 端使用。

**Comment by jzhfmm** [comment]
我使用conan安装过了，但是还是提示失败，要怎么解决呢？


jzhfmm@163.com
 
发件人： Altair Wei
发送时间： 2019-04-05 20:47
收件人： altairwei/WizNotePlus
抄送： jsee; Author
主题： Re: [altairwei/WizNotePlus] 2.7.3在windows环境下无法运行 (#37)
你参考下 客户端编译步骤 ，找不到库文件是因为你没有使用 conan 安装依赖。另外，这篇维基有一些过时了，我还没空更新。
WizNotePlus 在 Windows 端有性能缺陷以及存在一些严重 bug ，所以目前尽量不要在 Windows 端使用。

**Comment by jzhfmm** [comment]
·另外，再补充两个截图，一个是qt里面的概要信息，另外一个是编译信息。求帮忙，要怎么解决啊




jzhfmm@163.com
 
发件人： jzhfmm@163.com
发送时间： 2019-04-05 21:37
收件人： altairwei/WizNotePlus; altairwei/WizNotePlus
抄送： Author
主题： Re: Re: [altairwei/WizNotePlus] 2.7.3在windows环境下无法运行 (#37)

我使用conan安装过了，但是还是提示失败，要怎么解决呢？


jzhfmm@163.com
 
发件人： Altair Wei
发送时间： 2019-04-05 20:47
收件人： altairwei/WizNotePlus
抄送： jsee; Author
主题： Re: [altairwei/WizNotePlus] 2.7.3在windows环境下无法运行 (#37)
你参考下 客户端编译步骤 ，找不到库文件是因为你没有使用 conan 安装依赖。另外，这篇维基有一些过时了，我还没空更新。
WizNotePlus 在 Windows 端有性能缺陷以及存在一些严重 bug ，所以目前尽量不要在 Windows 端使用。

**Comment by altairwei** [comment]
我没有看见你的补充截图在哪。

你贴出来的错误信息表示没有构建成功。

**Comment by altairwei** [comment]
v2.8.0 已经提供了预编译的Windows客户端。
