### ISSUE TITLE
centos7 下运行，Socket服务被拒绝

### ISSUE THREAD

**Issue by chasezphp** [altairwei/WizNotePlus#38]
~]$ sudo chmod a+x ./～/WizNotePlus-linux-x86_64-v2.7.3.AppImage 
~]$ ./～/WizNotePlus-linux-x86_64-v2.7.3.AppImage 
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
**### "QLocalSocket::connectToServer: Connection refused"**
[stuff@localhostmyname ~]$

**Comment by chasezphp** [comment]
/lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_WizNotvKo9te/WizNote/bin/../lib/libsystemd.so.0)

**Comment by chasezphp** [comment]
./Application/WizNotePlus-linux-x86_64-v2.7.3.AppImage: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_WizNot3SHxMm/WizNote/bin/../lib/libpng16.so.16)
./Application/WizNotePlus-linux-x86_64-v2.7.3.AppImage: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_WizNot3SHxMm/WizNote/bin/../lib/libsystemd.so.0)
./Application/WizNotePlus-linux-x86_64-v2.7.3.AppImage: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_WizNot3SHxMm/WizNote/bin/../lib/libsystemd.so.0)
./Application/WizNotePlus-linux-x86_64-v2.7.3.AppImage: /lib64/libgpg-error.so.0: no version information available (required by /tmp/.mount_WizNot3SHxMm/WizNote/bin/../lib/libgcrypt.so.20)

**Comment by altairwei** [comment]
你参考 [Wiki 教程](https://github.com/altairwei/WizNotePlus/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4) 在 CentOS7 上编译试试？

Release 里的 AppImage 是我在 Ubuntu 18.04 下编译的，你的报错信息看起来是依赖库有点问题。

**Comment by altairwei** [comment]
比如你的 libc6 包太旧了？

**Comment by chasezphp** [comment]
> 比如你的 libc6 包太旧了？

glibc包升级太难了，这里的系统默认是 2.17，提示上需要2.27以上的glibc库
![image](https://user-images.githubusercontent.com/7436514/56337593-a7597a00-61d8-11e9-9278-9a97f8ff9a05.png)

**Comment by chasezphp** [comment]
WizNotePlus v2.7.3 必须注明 ，QT版本只能且必须使用Qt5.11.x版本

![Screenshot_2019-06-08_16-35-39](https://user-images.githubusercontent.com/7436514/59152090-8b6d9a00-8a0b-11e9-9c63-4481729391e4.png)

**Comment by altairwei** [comment]
实际上 Wiki 教程里面用的就是 Qt 5.11 ，只是没强调低于该版本会构建失败。那我加上这句话把。

**Comment by sunskyhsh** [comment]
ubuntu 16.04自带的glibc版本是2.23，如果想安全地升级glibc好像就得重装系统，所以建议作者在README中注明当前release中的AppImage不适用于ubuntu 16.04

**Comment by altairwei** [comment]
> ubuntu 16.04自带的glibc版本是2.23，如果想安全地升级glibc好像就得重装系统，所以建议作者在README中注明当前release中的AppImage不适用于ubuntu 16.04

感谢提醒，发布新的 release 时，我会注意这个问题。

**Comment by altairwei** [comment]
预编译 AppImage 目前最低要求 GLIBC_2.17
