### ISSUE TITLE
使用conan install 时，出现关于Gumbo 的 Missing prebuilt package  Missing prebuilt package for 'Gumbo/0.10.1@altairwei/testing'

### ISSUE THREAD

**Issue by chasezphp** [altairwei/WizNotePlus#39]
conan install ../WizNotePlus

![Screenshot from 2019-04-18 11-59-00](https://user-images.githubusercontent.com/7436514/56336058-74f84e80-61d1-11e9-985b-1d155c51aadc.png)

但已安装gumbo已安装，仍出错
![Screenshot from 2019-04-18 12-03-38](https://user-images.githubusercontent.com/7436514/56336225-14b5dc80-61d2-11e9-95da-0ce85461bfbc.png)

**Comment by altairwei** [comment]
WizNotePlus 编译系统使用的是 Conan 里的 Gumbo 包，不会去寻找系统包。

要么你加上 `--build missing` 手动使用 conan 编译依赖，要么直接使用 package.cmake 脚本。

**Comment by altairwei** [comment]
WizNotePlus 已经移除 Gumbo 依赖。
