### ISSUE TITLE
希望能支持mac的黑暗模式

### ISSUE THREAD

**Issue by AriaLyy** [altairwei/WizNotePlus#40]
![image](https://user-images.githubusercontent.com/10437293/57189370-a0ed3100-6f40-11e9-954b-04222190e67c.png)
现在的ui界面感觉很奇怪

**Comment by AriaLyy** [comment]
官方已经支持黑暗模式了，希望作者能跟进，这样就可以不使用官方哪个残疾版本

**Comment by altairwei** [comment]
实现黑暗模式最简单的方法是 merge 官方代码库，但是官方代码库很混乱，**维护成本相当的高**。我尝试过 merge 官方最新的主分支，但是解决层出不穷的 bug 很痛苦，最后放弃了。所以，未来我都不打算与官方代码库同步。另外，官方代码库实现的黑暗模式有相当多的硬编码样式，组件之间依赖性太高了，**进一步增加维护成本**。

我计划中的黑暗模式是通过**主题/皮肤系统**实现，但主题/皮肤系统的计划很靠后，我目前的精力放在 JavaScript 插件系统的实现和 Windows 版本插件的移植上面。

**Comment by AriaLyy** [comment]
确实，官方的代码bug太多了，动不动崩溃
