### ISSUE TITLE
Ubuntu19.04下无法运行

### ISSUE THREAD

**Issue by lfweqaz** [altairwei/WizNotePlus#44]
在终端内运行提示：非法指令 (核心已转储)
在Ubuntu18.04下运行也是提示这个错误
电脑硬件参数为：
cpu：Intel® Celeron(R) CPU 1037U @ 1.80GHz × 2
gpu：Intel® Ivybridge Mobile

**Comment by altairwei** [comment]
可能你得自己编译了，参考 [客户端编译步骤](https://github.com/altairwei/WizNotePlus/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4) 。编译过程遇到什么问题，随时向我提问。

**Comment by altairwei** [comment]
能否提供一下 `cat /proc/cpuinfo` 的输出信息？

**Comment by altairwei** [comment]
same to #56

**Comment by lfweqaz** [comment]
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Celeron(R) CPU 1037U @ 1.80GHz
stepping	: 9
microcode	: 0x21
cpu MHz		: 1258.907
cache size	: 2048 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 3591.65
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Celeron(R) CPU 1037U @ 1.80GHz
stepping	: 9
microcode	: 0x21
cpu MHz		: 1219.069
cache size	: 2048 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 3591.65
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

**Comment by altairwei** [comment]
能否尝试一下 https://pan.baidu.com/s/1QfkbiZGz7_mOLnlcysuelA 里 testing 文件夹中的 WizNotePlus-linux-x86_64-v2.8.0-beta.1-5-g78ad5852.AppImage ，应该能够在你电脑上运行了。

**Comment by lfweqaz** [comment]
还是不行，但是官方的可以用了。。。。
