### ISSUE TITLE
deepin系统下运行AppImage文件无反应

### ISSUE THREAD

**Issue by wan9wu** [altairwei/WizNotePlus#47]
从命令行运行后提示以下错误，请问如何解决呢？
``
/home/wangwenzhu/Downloads/WizNotePlus-linux-x86_64-v2.8.0-beta.0-2-g68265526.AppImage: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_WizNot8PBkBu/WizNote/bin/../lib/libpng16.so.16)
/home/wangwenzhu/Downloads/WizNotePlus-linux-x86_64-v2.8.0-beta.0-2-g68265526.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_WizNot8PBkBu/WizNote/bin/../lib/libsystemd.so.0)
/home/wangwenzhu/Downloads/WizNotePlus-linux-x86_64-v2.8.0-beta.0-2-g68265526.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_WizNot8PBkBu/WizNote/bin/../lib/libsystemd.so.0)
``

**Comment by altairwei** [comment]
使用 `ldd --version` 查看一下你发行版 GLIBC 的版本。
另外你的发行版需要安装 zlib 。

**Comment by wan9wu** [comment]
我的GLIBC版本号是2.24-11
ldd (Debian GLIBC 2.24-11+deb9u3) 2.24

**Comment by altairwei** [comment]
> 我的GLIBC版本号是2.24-11
> ldd (Debian GLIBC 2.24-11+deb9u3) 2.24

你可以尝试按照[教程](https://github.com/altairwei/WizNotePlus/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4)自己编译，或者升级发行版的 GLIBC 。

**Comment by wan9wu** [comment]
我想编译成功之后分享给和我一样使用deepin的朋友们，但我是小白，没有这方面经验。

您有什么建议吗？

> > 我的GLIBC版本号是2.24-11
> > ldd (Debian GLIBC 2.24-11+deb9u3) 2.24
> 
> 你可以尝试按照[教程](https://github.com/altairwei/WizNotePlus/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4)自己编译，或者升级发行版的 GLIBC 。

**Comment by altairwei** [comment]
你先按照教程把该装的东西安装好，然后按照流程走，哪里碰到问题我们再解决。

**Comment by wan9wu** [comment]
我发现，Qt官方现在不提供5.11了，我正在下载5.13可以吗？

https://download.qt.io/official_releases/qt/

**Comment by altairwei** [comment]
> 我发现，Qt官方现在不提供5.11了，我正在下载5.13可以吗？
> 
> https://download.qt.io/official_releases/qt/

最好不要，因为我还没测试过 Qt 5.13 有什么坑，你去 archive 文件夹，或者选择 online 下载器，然后找到 archive 中的 Qt 5.11

**Comment by altairwei** [comment]
你可以关注为知社区公众号，然后回复 “加群” ，这样我能及时指导你。

**Comment by altairwei** [comment]
目前预编译 AppImage 最低要求 GLIBC_2.17
