### ISSUE TITLE
希望支持cmd+w关闭标签快捷键

### ISSUE THREAD

**Issue by lanbos** [altairwei/WizNotePlus#48]

**Comment by altairwei** [comment]
ctrl+w ?

**Comment by altairwei** [comment]
Ctrl+W 原本是 WizNote 窗口关闭快捷键。不过我看 Chrome 和 VSCode 的 Ctrl+W 都是关闭标签页，这应该是通用操作。这样的化，窗口关闭快捷键调整到 Ctrl+Alt+W ，Ctrl+W 让给关闭标签页。

**Comment by zhangyu0806** [comment]
Ctrl + w 关闭标签页是比较符合使用习惯的，希望多增加一些快捷键的设置。

**Comment by altairwei** [comment]
> Ctrl + w 关闭标签页是比较符合使用习惯的，希望多增加一些快捷键的设置。

有什么快捷键的建议可以明确地开个 issue 提一下。

**Comment by altairwei** [comment]
已经实现 Ctrl+W 关闭当前标签页，等待 v2.8.2 发布。
