### ISSUE TITLE
[20181021]fedora28_inteli5_X86_64下载appimage镜像后无法启动

### ISSUE THREAD

**Issue by shuchaoma** [altairwei/WizNotePlus#5]
下载后，在文件所在目录执行./WizNote-x86_64.AppImage，输出以下信息：
############ BEGIN ###########
./WizNote-x86_64.AppImage: relocation error: ./WizNote-x86_64.AppImage: symbol _ZNSt20bad_array_new_lengthD1Ev version Qt_5 not defined in file libQt5Xml.so.5 with link time reference
############### END #########
看不懂这是什么含义，求教。

**Comment by altairwei** [comment]
尝试参考 [Wiki教程](https://github.com/altairwei/WizNotePlus/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4) 编译一下。

**Comment by shuchaoma** [comment]
> 尝试参考 [Wiki教程](https://github.com/altairwei/WizNotePlus/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4) 编译一下。
> 


这份构建教程比官网的详细多了；赞！！！

**Comment by altairwei** [comment]
你编译成功了吗？

**Comment by shuchaoma** [comment]
> 尝试参考 [Wiki教程](https://github.com/altairwei/WizNotePlus/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4) 编译一下。
> 
> 光看这个不知道是依赖版本问题还是打包的问题，你可以尝试用打包脚本以及用 QtCreator 分别编译并运行一下。

你好。我正在根据你的wiki进行编译打包。

一、
不过发现了一些并不太细致的地方。
尤其对于命令行编译的部分，比如：
1. “配置构建脚本选项”：似乎笔者是mac使用者，大写的环境变量只有mac-paackge中才存在。
2. package.cmake：git clone下来的源码包并没有这个文件；对应的是各种适用于不同平台的package.sh文件
3. linux-package.sh存在较多绝对路径，并不太适合release打包。

二、后面仔细阅读了linux-package.sh，手动完成了打包过程，最终生成了appImage文件。但是：
- 依然存在这个issue最开始所描述的问题。
现在我有两点待继续分析：
1）或许我安装的Qt5.11.2 libaray也需要打包至appiamge中；可能之前默认索引到我系统路径默认的Qt5.11.1
2）或许我将HOME下安装的Qt5.11.2中的libs也加到LD_LIBRARY就可以了。

感谢;感觉快解决了

**Comment by altairwei** [comment]
```
git checkout release
```

WizNotePlus v2.7.0-beta 还没有合并到 master，请切换到 release 分支。
另外，package.cmake 是跨平台脚本，你不是 macOS 就不用管 macOS 的参数。

**Comment by shuchaoma** [comment]
> ```
> git checkout release
> ```
> 
> WizNotePlus v2.7.0-beta 还没有合并到 master，请切换到 release 分支。
> 另外，package.cmake 是跨平台脚本，你不是 macOS 就不用管 macOS 的参数。

感谢；我基本快编译通过了。不过依然存在一个问题：
一、
![image](https://user-images.githubusercontent.com/6086958/47776983-a74ee600-dd2e-11e8-8d19-2277ad821bde.png)
为何wiznoteplug一定要使用fcit输入法框架呢？在输入法方面我一直使用的系统默认的ibus（fedora默认）；在编译期间如果没有找到fcitx-qt5-lib就会报 FATAL_ERROR。

**Comment by altairwei** [comment]
OK，之后我会给编译脚本添加一个选择输入法框架的选项。目前，你可以将 `package.cmake` 脚本中下面这一段删除掉：

```cmake
            # copy fcitx-qt5 library
            find_file (fcitx-qt5-lib libfcitxplatforminputcontextplugin.so 
                /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/ 
            )
            if(NOT fcitx-qt5-lib)
                message(FATAL_ERROR "Fail to find fcitx-qt5 !")
            endif()

            file(MAKE_DIRECTORY 
                ${WIZNOTE_PACKAGE_DIR}/WizNote/plugins/platforminputcontexts
            )
            file(COPY ${fcitx-qt5-lib} 
                DESTINATION ${WIZNOTE_PACKAGE_DIR}/WizNote/plugins/platforminputcontexts)
```

**Comment by shuchaoma** [comment]
Good!!!
按照你说的方法，不仅仅生成了可运行的appimage，而且在解决问题的过程中了解了为何之前camke构建个失败的原理。
现在已经运行起来了。

不过在终端运行时，有时无法启动，另外有时启动后终端存在很多（WARING、DEBUG），未来慢慢研究；个人稍微一点强迫症

不过现在以及很幸福了！加油～～有问题我会继续反馈
