### ISSUE TITLE
增加快速跳转功能

### ISSUE THREAD

**Issue by sun3596209** [altairwei/WizNotePlus#51]
官方版本，鼠标邮件点击标签栏，可以快速定位到文章的目录，这样很方便整理文章。希望能够加上。

**Comment by altairwei** [comment]
右键菜单栏中添加 “定位” 选项？

**Comment by sun3596209** [comment]
> 右键菜单栏中添加 “定位” 选项？

转到文件夹，咱俩说的应该是一个意思

**Comment by CodingOX** [comment]
很实用的功能。。。

**Comment by altairwei** [comment]
已实现，请等待 v2.8.2 发布。
