### ISSUE TITLE
Ubuntu16.04, Qt5.11 编译出错

### ISSUE THREAD

**Issue by wenglihong** [altairwei/WizNotePlus#52]
编译错误信息
In file included from /opt/Qt5.11/5.11.1/gcc_64/include/QtWebEngineWidgets/QWebEngineView:1:0,
                 from /home/wlh/Downloads/WizNotePlus/src/share/WizWebEngineView.h:4,
                 from /home/wlh/Downloads/WizNotePlus/src/WizWebSettingsDialog.h:5,
                 from /home/wlh/Downloads/WizNotePlus/src/share/WizMisc.cpp:2:
/opt/Qt5.11/5.11.1/gcc_64/include/QtWebEngineWidgets/qwebengineview.h:127:14: error: missing binary operator before token "("
 #if QT_CONFIG(draganddrop)
              ^
[  5%] Building CXX object src/CMakeFiles/WizNote.dir/share/WizUIHelper.cpp.o
In file included from /home/wlh/Downloads/WizNotePlus/src/share/WizObject.cpp:1:0:
/home/wlh/Downloads/WizNotePlus/src/share/WizObject.h:241:12: error: field ‘crTextColor’ has incomplete type ‘QColor’
     QColor crTextColor;
            ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QMetaType:1:0,
                 from /home/wlh/Downloads/WizNotePlus/src/share/WizObject.h:4,
                 from /home/wlh/Downloads/WizNotePlus/src/share/WizObject.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h:1874:1: note: forward declaration of ‘class QColor’
 QT_FOR_EACH_STATIC_GUI_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
 ^
In file included from /home/wlh/Downloads/WizNotePlus/src/share/WizObject.cpp:1:0:
/home/wlh/Downloads/WizNotePlus/src/share/WizObject.h:242:12: error: field ‘crBackColor’ has incomplete type ‘QColor’
     QColor crBackColor;
            ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QMetaType:1:0,
                 from /home/wlh/Downloads/WizNotePlus/src/share/WizObject.h:4,
                 from /home/wlh/Downloads/WizNotePlus/src/share/WizObject.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h:1874:1: note: forward declaration of ‘class QColor’
 QT_FOR_EACH_STATIC_GUI_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
 ^
In file included from /opt/Qt5.11/5.11.1/gcc_64/include/QtWebEngineWidgets/qwebenginepage.h:46:0,
                 from /opt/Qt5.11/5.11.1/gcc_64/include/QtWebEngineWidgets/qwebengineview.h:48,
                 from /opt/Qt5.11/5.11.1/gcc_64/include/QtWebEngineWidgets/QWebEngineView:1,
                 from /home/wlh/Downloads/WizNotePlus/src/share/WizWebEngineView.h:4,
                 from /home/wlh/Downloads/WizNotePlus/src/WizWebSettingsDialog.h:5,
                 from /home/wlh/Downloads/WizNotePlus/src/share/WizMisc.cpp:2:
/opt/Qt5.11/5.11.1/gcc_64/include/QtWebEngineCore/qwebenginecallback.h:96:1: error: expected constructor, destructor, or type conversion before ‘Q_DECLARE_SHARED_NOT_MOVABLE_UNTIL_QT6’
 Q_DECLARE_SHARED_NOT_MOVABLE_UNTIL_QT6(QWebEngineCallback<const QString &>)
 ^
In file included from /opt/Qt5.11/5.11.1/gcc_64/include/QtWebEngineWidgets/qwebenginepage.h:47:0,
                 from /opt/Qt5.11/5.11.1/gcc_64/include/QtWebEngineWidgets/qwebengineview.h:48,
                 from /opt/Qt5.11/5.11.1/gcc_64/include/QtWebEngineWidgets/QWebEngineView:1,
                 from /home/wlh/Downloads/WizNotePlus/src/share/WizWebEngineView.h:4,
                 from /home/wlh/Downloads/WizNotePlus/src/WizWebSettingsDialog.h:5,
                 from /home/wlh/Downloads/WizNotePlus/src/share/WizMisc.cpp:2:
/opt/Qt5.11/5.11.1/gcc_64/include/QtWebEngineCore/qwebenginehttprequest.h:97:24: error: ‘QWebEngineHttpRequestPrivate’ was not declared in this scope
     QSharedDataPointer<QWebEngineHttpRequestPrivate> d;
                        ^
/opt/Qt5.11/5.11.1/gcc_64/include/QtWebEngineCore/qwebenginehttprequest.h:97:52: error: template argument 1 is invalid
     QSharedDataPointer<QWebEngineHttpRequestPrivate> d;
                                                    ^
[  6%] Building CXX object src/CMakeFiles/WizNote.dir/share/WizCommonUI.cpp.o
src/CMakeFiles/WizNote.dir/build.make:405: recipe for target 'src/CMakeFiles/WizNote.dir/share/WizObject.cpp.o' failed
make[2]: *** [src/CMakeFiles/WizNote.dir/share/WizObject.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  6%] Building CXX object src/CMakeFiles/WizNote.dir/share/WizAnimateAction.cpp.o
/home/wlh/Downloads/WizNotePlus/src/share/WizMisc.cpp: In function ‘bool WizURLDownloadToFile(const QString&, const QString&, bool)’:
/home/wlh/Downloads/WizNotePlus/src/share/WizMisc.cpp:3010:13: error: ‘RedirectPolicyAttribute’ is not a member of ‘QNetworkRequest’
             QNetworkRequest::RedirectPolicyAttribute, 
             ^
/home/wlh/Downloads/WizNotePlus/src/share/WizMisc.cpp:3011:13: error: ‘NoLessSafeRedirectPolicy’ is not a member of ‘QNetworkRequest’
             QNetworkRequest::NoLessSafeRedirectPolicy);
             ^
src/CMakeFiles/WizNote.dir/build.make:333: recipe for target 'src/CMakeFiles/WizNote.dir/share/WizMisc.cpp.o' failed
make[2]: *** [src/CMakeFiles/WizNote.dir/share/WizMisc.cpp.o] Error 1
CMakeFiles/Makefile2:88: recipe for target 'src/CMakeFiles/WizNote.dir/all' failed
make[1]: *** [src/CMakeFiles/WizNote.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at package.cmake:250 (message):
  Fail to build WizNotePlus project!

**Comment by altairwei** [comment]
关注公众号，加入交流群，有空我用 TeamViewer 远程帮你编译。下个版本我会解决旧 GLIBC 兼容性问题。
