### ISSUE TITLE
Ubuntu16.04 v2.8.0 AppImage无法运行

### ISSUE THREAD

**Issue by wenglihong** [altairwei/WizNotePlus#53]
错误信息
➜ ./WizNotePlus-linux-x86_64-v2.8.0-beta.0-5-g520ca2e1.AppImage
./WizNotePlus-linux-x86_64-v2.8.0-beta.0-5-g520ca2e1.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_WizNotJgcSP3/WizNote/bin/../lib/libsystemd.so.0)
./WizNotePlus-linux-x86_64-v2.8.0-beta.0-5-g520ca2e1.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_WizNotJgcSP3/WizNote/bin/../lib/libsystemd.so.0)
搜索后发现16.04无法安装GLIBC_2.25，尝试源码编译，出现下面这个问题 [#52 ](https://github.com/altairwei/WizNotePlus/issues/52)

**Comment by altairwei** [comment]
v2.8.0-beta.2 能运行了吗？

**Comment by altairwei** [comment]
目前预编译 AppImage 最低要求 GLIBC_2.17
