### ISSUE TITLE
MaoXian Web Clipper  剪裁为markdown，图片无法显示

### ISSUE THREAD

**Issue by CodingOX** [altairwei/WizNotePlus#55]
看了下数据读取的是本地的某个路径。。。应该是这个问题！

**Comment by altairwei** [comment]
提供一下出现问题的网站，指出是哪些图片出了问题。

**Comment by CodingOX** [comment]
比如掘金的网站：`https://juejin.im/post/5d565015f265da03eb13c575`
下载后效果如图所示：
![image](https://user-images.githubusercontent.com/9800933/63234759-3ea70a80-c269-11e9-9645-73b573c52cb2.png)

**Comment by altairwei** [comment]
还有其他出现这个问题的网页吗？

**Comment by CodingOX** [comment]
目前为止发现了这个网站，其他的应该没有，发现会及时反馈的

**Comment by CodingOX** [comment]
又发现剪裁位markdown后，图片丢失，网站是：`http://blog.leanote.com/post/zhangyue/%E5%88%86%E5%BA%93%E5%88%86%E8%A1%A8%E7%9A%84%E5%88%86%E9%A1%B5%E6%9F%A5%E8%AF%A2`
