### ISSUE TITLE
内部link功能失效

### ISSUE THREAD

**Issue by gnwd** [altairwei/WizNotePlus#57]
“copy internal note link"之后，在其他笔记中粘贴。
期望：在其他笔记中点击该链接，应该跳转到对应的笔记
实际：弹出标签页，但内容全空白

**Comment by altairwei** [comment]
谢谢报告，v2.8.0 正式版会修复。

**Comment by tttwwy** [comment]
@altairwei 插入的附件链接也是一样

**Comment by altairwei** [comment]
> @altairwei 插入的附件链接也是一样

好的，收到反馈。
