### ISSUE TITLE
macOS Mojave 暗黑模式下左上角菜单显示不正常

### ISSUE THREAD

**Issue by junhuali** [altairwei/WizNotePlus#59]
<img width="153" alt="WX20190828-143028@2x" src="https://user-images.githubusercontent.com/36150626/63831103-7405d380-c9a0-11e9-8508-fd857e3033d3.png">
系统版本： macOS Mojave 10.14.6
软件版本：WizNotePlus-mac-v2.8.0-beta.1

**Comment by altairwei** [comment]
WizNotePlus 没有实现 Mojave 下DE黑暗模式，你的这个黑暗模式怎么来的？

**Comment by junhuali** [comment]
> WizNotePlus 没有实现 Mojave 下的黑暗模式，你的这个黑暗模式怎么来的？

开始安装的是WizNote，然后用WizNotePlus 覆盖安装的，我先切换回去了
![image](https://user-images.githubusercontent.com/36150626/63906734-943e9c80-ca4b-11e9-8060-4e744a65b776.png)
正常如上图

**Comment by cnwoodgithub** [comment]
我也遇到了相同的问题。

**Comment by altairwei** [comment]
@junhuali 参考 #66 的解决方案，关闭自动黑暗模式的切换。
