### ISSUE TITLE
打开文档中的PDF附件时,原文档内容消失

### ISSUE THREAD

**Issue by CKboss** [altairwei/WizNotePlus#6]
打开文档中的PDF附件时,原文档内容消失

**Comment by altairwei** [comment]
确实有这个问题，我会进行排查。

**Comment by altairwei** [comment]
麻烦告知一下你使用的操作系统以及 WizNotePlus 版本

**Comment by CKboss** [comment]
Ubuntu 18.04

https://github.com/altairwei/WizNotePlus/releases/download/v2.7.0/WizNote-x86_64.AppImage

**Comment by altairwei** [comment]
> Ubuntu 18.04
> 
> https://github.com/altairwei/WizNotePlus/releases/download/v2.7.0/WizNote-x86_64.AppImage

能否描述一下怎么复现这个bug？我现在没法复现它了。

**Comment by CKboss** [comment]
> > Ubuntu 18.04
> > https://github.com/altairwei/WizNotePlus/releases/download/v2.7.0/WizNote-x86_64.AppImage
> 
> 能否描述一下怎么复现这个bug？我现在没法复现它了。

打开一篇带有PDF附件的笔记(点击笔记里的那个PDF的图标) 然后笔记就变成空白了, 需要重新点开笔记才会显示.

如果从附件列表里选择pdf打开,就不会出这个问题.

已经尝试了不同的pdf阅读器, 都会出现这个问题. 使用的版本就是gitlab上下载的那个appimage

**Comment by altairwei** [comment]
> 打开一篇带有PDF附件的笔记(点击笔记里的那个PDF的图标) 然后笔记就变成空白了, 需要重新点开笔记才会显示.

“点击笔记里的那个PDF的图标” 是指哪个PDF图标？能否截个图指示一下？我忘了当时是怎么复现你这个问题的了。

**Comment by CKboss** [comment]
录了一段视频, 可以看一下
[2018-12-09 13-30-01.flv.zip](https://github.com/altairwei/WizNotePlus/files/2660257/2018-12-09.13-30-01.flv.zip)

**Comment by altairwei** [comment]
> 录了一段视频, 可以看一下
> [2018-12-09 13-30-01.flv.zip](https://github.com/altairwei/WizNotePlus/files/2660257/2018-12-09.13-30-01.flv.zip)

OK，我知道了，谢谢。

**Comment by altairwei** [comment]
问题已解决，将在下一个 release 修复。
