### ISSUE TITLE
Ubuntu18.04 v2.8.0 AppImage无法运行

### ISSUE THREAD

**Issue by f4nyc** [altairwei/WizNotePlus#62]
![图片](https://user-images.githubusercontent.com/17718104/64590752-d916eb80-d3da-11e9-9838-def81d0df16e.png)
报错QLocalSocket::connectToServer: Connection refused

**Comment by altairwei** [comment]
1. 将原有或者僵死的 WizNote 进程 kill 掉，重新启动。
2. 如果上一步不行，检查 `8848` 端口是否有被其他程序占用。先用 `sudo lsof -i -P -n | grep 8848` 找到 PID，然后 `ps -fp <PID>` 看是什么程序。

**Comment by f4nyc** [comment]
感谢！解决了

**Comment by altairwei** [comment]
所以，你的问题是第一种情况还是第二种情况？

**Comment by f4nyc** [comment]
僵死的WizNote导致的。外部编辑器这个功能太赞了，手动存图片的过程写成Vimscript脚本来做之后十分完美_(:з」∠)_

**Comment by altairwei** [comment]
> 僵死的WizNote导致的。外部编辑器这个功能太赞了，手动存图片的过程写成Vimscript脚本来做之后十分完美_(:з」∠)_

能开个 issue 分享一下你是怎么利用 Vimscript 的吗？

**Comment by f4nyc** [comment]
> 能开个 issue 分享一下你是怎么利用 Vimscript 的吗？
done
推荐t.me/VimHub
