### ISSUE TITLE
MacOS 版本 UI 界面 Action Button 字体过小

### ISSUE THREAD

**Issue by xsb0624** [altairwei/WizNotePlus#64]
新建笔记字体太小了
![image](https://user-images.githubusercontent.com/46621393/65332103-9e8a2b80-dbf0-11e9-9db3-8a07f435d229.png)
macos 版本 10.14.6

**Comment by altairwei** [comment]
已知问题，但我目前尚未定位到造成这个bug的原因

**Comment by altairwei** [comment]
v2.10 已经调整好了字体大小。
