### ISSUE TITLE
建议增加编辑/阅读切换快捷键

### ISSUE THREAD

**Issue by hfge** [altairwei/WizNotePlus#67]
建议增加编辑/阅读快捷键，譬如cmd+R

**Comment by altairwei** [comment]
?
编辑 => ctrl + e
阅读 => ctrl + r

**Comment by cnwoodgithub** [comment]
我的意思是`cmd+r`，<k>a</k>在编辑和阅读之间来回切换
现在的`cmd+f`是当前笔记内查找，`cmd+r`是全局搜索
可以换成`cmd+shift+f`，这样会比较符合使用习惯一点。

**Comment by chncho** [comment]
现在是有这个快捷键的,官方版是alt+1,不过目前看是快捷键失效了 @altairwei @cnwoodgithub

**Comment by altairwei** [comment]
已实现自定义【编辑/阅读】快捷键
