### ISSUE TITLE
基于 WizQTClient v2.6.5 提供黑暗模式

### ISSUE THREAD

**Issue by CodingOX** [altairwei/WizNotePlus#7]
RT，可以基于最新版发一个版本吗？
暗黑主题在 mac Mojave 还是挺有意思的！

**Comment by xgdgsc** [comment]
![deepinscreenshot_select-area_20181112175932](https://user-images.githubusercontent.com/1189869/48340162-e3763500-e6a4-11e8-840f-3d0b7435fe42.png)

KDE breeze dark主题下配色是怪怪的，希望黑暗模式能一起解决

**Comment by AlphaGao1993** [comment]
官方版本的 dark 主题有 bug，总是会闪烁，暂时不要合的好

**Comment by altairwei** [comment]
> 官方版本的 dark 主题有 bug，总是会闪烁，暂时不要合的好

我尝试合并过一次，但之后各种层出不穷的 BUG 解决起来太累了，所以以后我不会考虑再同步官方仓库了。

**Comment by altairwei** [comment]
> 还会适配暗黑模式吗？

UI 开发是最繁琐的工作，未来很长一段时间我都不会计划开发黑暗模式。
