### ISSUE TITLE
使用QT1.13.1编译的坑

### ISSUE THREAD

**Issue by rengui** [altairwei/WizNotePlus#73]
编译环境
- Windows 10 64 bit
- VS2017 community
   - 安装VC++ 
   - Windows 10 SDK (也是必须)
- CMake
- Qt5.13.1 (msvc2017_64)   （官网没有5.11下载了）

按照[wiki](https://github.com/altairwei/WizNotePlus/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4)编译`release-2.8.0`分支，顺利完成！
  - `package.cmake`, line 29
     ```
        find_file(qmake_file "bin/qmake" ${QTDIR})
     ==> 
        find_file(qmake_file "bin/qmake.exe" ${QTDIR})
     ```
然后对接wiznote docker server（默认部署http)，一切正常 o(∩_∩)o 

然而都9102年了，怎么还能用http明文传输呢。。。于是把server切换成https模式，突然悲剧了，总是显示network error。
- 抓包发现压根就没有发送任何数据包！
- 然后在 qt creator 中运行debug版 ，发现error logging如下:
  ```
  [WARNING]: QSslSocket::connectToHostEncrypted: TLS initialization failed (ssl\qsslsocket.cpp:463, void __cdecl QSslSocket::connectToHostEncrypted(const class QString &,unsigned short,class QFlags<enum QIODevice::OpenModeFlag>,enum QAbstractSocket::NetworkLayerProtocol))
  //出错的地方在这里，建立https连接失败了 
  WizApiEntry.cpp:
  QString _requestUrl(const QString& strUrl)
  {
    QNetworkAccessManager net;
    QNetworkReply* reply = net.get(QNetworkRequest(strUrl));
  ```
  怀疑是openssl的问题，然而编译打包的bin目录下 `libeay32.dll`, `ssleay32.dll`都有。。。

折腾了半天，才在这里看到：
> https://forum.qt.io/topic/99374/qnetworkaccessmanager-to-a-https-troubles/10
> Qt 5.12 uses OpenSSL 1.1.0.

==> [下载openssl 1.1.x](https://slproweb.com/download/Win64OpenSSL-1_1_0L.exe)，然后把 `libcrypto-1_1-x64.dll`, `libssl-1_1-x64.dll`, 复制到Wiznote.exe所在目录，然后连接https服务器就OK了。

**结论：**
 - 如果使用QT 5.12及以后版本编译，需要把openssl依赖升级到1.1.x。
 - 比如，修改connanfile.py
   ```
    requires = (
        "OpenSSL/1.1.0k@conan/stable",
   ```

**Comment by altairwei** [comment]
对的，Qt 5.12 就已经使用 OpenSSL v1.1 了。这就是为什么目前 WizNotePlus 依然依赖于 Qt 5.11.3 的原因，我想等到 Qt 5.12 稳定后再更新依赖。

**Comment by rengui** [comment]
之前Qt5.13.1编译的确实有点适配问题：
![image](https://user-images.githubusercontent.com/42397480/68105591-fae3a900-ff19-11e9-9bfa-cf6e94e492fe.png)

今天重新安全Qt5.11.3编译的，完全OK：
![image](https://user-images.githubusercontent.com/42397480/68105670-3a11fa00-ff1a-11e9-8db6-93f2ba6bd443.png)
