### ISSUE TITLE
2.8.1beat报网络错误

### ISSUE THREAD

**Issue by chasezphp** [altairwei/WizNotePlus#77]
![image](https://user-images.githubusercontent.com/7436514/68915815-88d35580-079e-11ea-86f1-4dbcd9c3c108.png)

![image](https://user-images.githubusercontent.com/7436514/68915744-57f32080-079e-11ea-81b3-957394ac1884.png)

![image](https://user-images.githubusercontent.com/7436514/68915782-748f5880-079e-11ea-9fb4-3812c52d1a38.png)

https://as.wiz.cn/as/user/login?clientType=macos&clientVersion=2.8.0&apiVersion=10&srcHost=as.wiz.cn

**Comment by altairwei** [comment]
你什么发行版，OpenSSL 版本是什么？

**Comment by chasezphp** [comment]
![image](https://user-images.githubusercontent.com/7436514/68987724-7e30c300-0867-11ea-90d5-cf3b263d4c1d.png)
OpenSSL 1.1.1c  28 May 2019

**Comment by altairwei** [comment]
WizNotePlus 中 Qt 网络模块依赖 OpenSSL v1.0 。但这个问题不应该发生，因为 AppImage 已经打包了 OpenSSL v1.0.2p 。

简单的解决方法：

```shell
sudo apt install openssl1.0 libssl1.0-dev
```

**Comment by chasezphp** [comment]
是libssl-dev这个包出了问题，sudo apt install  libssl-dev 解决问题
