### ISSUE TITLE
Ubuntu 18.04.3 LTS下界面显示过大，求解

### ISSUE THREAD

**Issue by hzmming** [altairwei/WizNotePlus#79]
系统信息
![image](https://user-images.githubusercontent.com/15829377/70016195-9b30fa00-15ba-11ea-9d1e-c64f7ad40d49.png)
![image](https://user-images.githubusercontent.com/15829377/70016217-b0a62400-15ba-11ea-831a-31c070e49ae6.png)
与官方版本的对比
![image](https://user-images.githubusercontent.com/15829377/70016366-17c3d880-15bb-11ea-9099-7f71474624bd.png)
![image](https://user-images.githubusercontent.com/15829377/70016506-75f0bb80-15bb-11ea-9d73-86e0979d9cb0.png)
显示明显有问题，参考其它issue给的解决方案，设置了
![image](https://user-images.githubusercontent.com/15829377/70016683-f1526d00-15bb-11ea-8ac7-f540190aee2c.png)
注销重启过了，还是不行...
WizNotePlus比官方版本好太多了，就这个显示问题，实在有点难受，求解！！！

**Comment by altairwei** [comment]
按如下设置：

```shell
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
QT_SCREEN_SCALE_FACTORS=1
```

**Comment by hzmming** [comment]
![image](https://user-images.githubusercontent.com/15829377/70020293-1e584d00-15c7-11ea-83f2-2063527e3f90.png)
设置，也注销过了，还是不行，真的有去读这个参数么？会不会是我漏装了什么？

**Comment by altairwei** [comment]
从命令启动试试：

```
export QT_AUTO_SCREEN_SCALE_FACTOR=0 && export QT_SCALE_FACTOR=1 && export QT_SCREEN_SCALE_FACTORS=1 && ./WizNotePlus.AppImage
```

**Comment by hzmming** [comment]
可以了，非常感谢👍
那我是要把这命令保存成桌面快捷方式么？

**Comment by altairwei** [comment]
> 可以了，非常感谢
> 那我是要把这命令保存成桌面快捷方式么？

你得自己找找为什么 `.bashrc` 中的变量没有生效的原因。

**Comment by hzmming** [comment]
可以了，把环境变量配在_/etc/profile_，重启下就行了😁
