### ISSUE TITLE
[20181031]fedora28 | x86_64|启动appimage概率性失败

### ISSUE THREAD

**Issue by shuchaoma** [altairwei/WizNotePlus#8]
环境描述：
- Thinkpad X270
- X86_64
- fedoa 28

基于Qt5.11.2版本构建后，从termina启动（/WizNote-x86_64.AppImage ），概率性失败。

失败原因截图：
![image](https://user-images.githubusercontent.com/6086958/47786153-d0c73c00-dd45-11e8-97cc-65d90cbf45bd.png)

第一次启动失败，但是第二次再次启动会成功。
![image](https://user-images.githubusercontent.com/6086958/47786202-ff451700-dd45-11e8-9ead-6a926cef5847.png)

无论成功与否都会打印第一行（关于QXcbIntegration的提示，但是失败情况下会打印QLocalSocket::connectToServer错误，怀疑启动时网络环境连接需要一些优化）

**Comment by altairwei** [comment]
Linux 使用共享内存区块的原因，Qt 应用都是以 Signle Application 模式启动，如果第一次正常启动应用后没有正常退出，那么第二次启动会失败但同时会 detach 共享内存区段，也就是说第三次才会正常启动。

你试试直接双击AppImage启动WizNote，另外可以参考 [AppImage整合入桌面环境](https://github.com/altairwei/WizNotePlus/wiki/AppImage%E6%95%B4%E5%90%88%E5%85%A5%E6%A1%8C%E9%9D%A2%E7%8E%AF%E5%A2%83) Wiki 来将 AppImage 整合入桌面。

**Comment by shuchaoma** [comment]
> Linux 使用共享内存区块的原因，Qt 应用都是以 Signle Application 模式启动，如果第一次正常启动应用后没有正常退出，那么第二次启动会失败但同时会 detach 共享内存区段，也就是说第三次才会正常启动。
> 
> 你试试直接双击AppImage启动WizNote，另外可以参考 [AppImage整合入桌面环境](https://github.com/altairwei/WizNotePlus/wiki/AppImage%E6%95%B4%E5%90%88%E5%85%A5%E6%A1%8C%E9%9D%A2%E7%8E%AF%E5%A2%83) Wiki 来将 AppImage 整合入桌面。

按照你提供的wiki安装了appimaged，但是依然不明白怎么就叫整合入“桌面系统了”；安装完appimaged后，现在后台跑着appimaged进程；
双击WizNote-X86_64.AppImage依然无法运行。（使用terminal启动也依然存在本issue描述的问题）

**Comment by shuchaoma** [comment]
问题基本可以说解决了。
gnome3.26版本之后默认对“隐藏”应用不再有一个tary显示；而wiz关闭按钮默认的行为是隐藏。或许我们可以思考将“关闭”按钮的行为改为“关闭”
