### ISSUE TITLE
保存文章的时候，标题被清空

### ISSUE THREAD

**Issue by CodingOX** [altairwei/WizNotePlus#83]
我复制一篇文章到wiznote，然后输入标题，然后Ctrl+s，然后标题就没了。。
偶现bug,但是频率还是高

**Comment by CodingOX** [comment]
当复制的文章比较大的时候，该bug触发的几率很大！

**Comment by altairwei** [comment]
能否提供一个必然触发此 BUG 的案例？

**Comment by CodingOX** [comment]
有点难，偶发的 bug...
