### ISSUE TITLE
使用Typora编辑md笔记，修改后不保存

### ISSUE THREAD

**Issue by rengui** [altairwei/WizNotePlus#88]
发现一个bug，配置好Typora后写md笔记，发现有时在Typora保存后，文件内容**不会**同步到WizNotePlus窗口中显示的笔记。
- 也就是说，如果你此时大意把Typora关闭，然后再WizNotePlus-Typora编辑笔记，刚才修改的笔记内容就丢失了。。。 （Issue #71 不确定是不是这种情况引起的？ ）
  - 如果刚关闭Typora的时候你就发现修改的内容没同步到笔记，那么打开Typora临时文件夹（C:\Users\<your_user_name>\AppData\Local\Temp\WizNote\<uuid_of_this_article>），你修改的内容还在那里。

**复现步骤：**
在在Typora编辑笔记的时候，在WizNotePlus窗口中点开别的md笔记（WizNotePlus中，别的md笔记为选中状态）（如果点一篇还未出bug，那么再点一篇），之后在Typora中保存笔记， 发现修改的内容没有同步到WizNotePlus中。

**避免方法：**
**在修改笔记的时候不要在WizNotePlus窗口中点击查看别的md笔记**，如果非要查看（写笔记b时需要翻一下笔记a参考），那么查看了之后，在WizNotePlus窗口中，务必选中回当前Typora编辑的那篇笔记，然后在Typora中再保存一下就可以了！！！

**Comment by altairwei** [comment]
我在 Linux 平台没有重复出来你的问题。你是在 Windows 平台发现问题的吗？

**Comment by rengui** [comment]
是的，win10，这会换了个win10中文版（winver: 18363.535）试了试又没复现这个bug。

之前发现bug的是在Win10 Insider 英文内测版(19013)。

**Comment by rengui** [comment]
Win10 Insider 英文内测版(19013)，开发机，之前有1个月没重启了。今天重启之后发现为偶发性bug，
先不管了吧，万一遇到用“避免方法”解决，保存的时候自己多注意。

**Comment by altairwei** [comment]
我最近用 Win 10 偶然也会出现跟你类似的问题，所以这个 issue 重，等待修复吧。

**Comment by altairwei** [comment]
@rengui 能否上 https://github.com/altairwei/WizNotePlus/actions 找最新的构建测试下是否还能重复出这个问题？

**Comment by altairwei** [comment]
我按照你的描述无法重复这个问题，尽管我也偶尔发现过这个 BUG ，但是仍然找不到它复现的规律。

**Comment by rengui** [comment]
> @rengui 能否上 https://github.com/altairwei/WizNotePlus/actions 找最新的构建测试下是否还能重复出这个问题？

@altairwei 下周我试试哈，下周才能用装了开发环境的机器 :)

**Comment by rengui** [comment]
@altairwei 
不好意思，最近很少用电脑哈，现在基本正常了 :)
用最新的构建还是会偶发这个bug，但是说不上规律哈。上面复现步骤不一定出现。但是如果出现了，避免方法还是能管用。

**Comment by GerrieWell** [comment]
奔溃...我mac版也突然这样. 外部编辑器不管用了. 本来用的好好的. mweb/typora都不行.
版本: 2.8.0/2.8.1

**Comment by altairwei** [comment]
> 奔溃...我mac版也突然这样. 外部编辑器不管用了. 本来用的好好的. mweb/typora都不行.
> 版本: 2.8.0/2.8.1

这个 issue 提出的问题并不是 “外部编辑器完全不能用” 。

你把你的外部编辑器的配置截图给我看看。

**Comment by GerrieWell** [comment]
> > 奔溃...我mac版也突然这样. 外部编辑器不管用了. 本来用的好好的. mweb/typora都不行.
> > 版本: 2.8.0/2.8.1
> 
> 这个 issue 提出的问题并不是 “外部编辑器完全不能用” 。
> 
> 你把你的外部编辑器的配置截图给我看看。

@altairwei 
外部编辑器是可以打开的. 是修改保存后, wiznote那边不发生改变.
```
应用名称:
/usr/bin/open 
参数:
%1 -a MWeb
```

**Comment by altairwei** [comment]
> @altairwei
> 外部编辑器是可以打开的. 是修改保存后, wiznote那边不发生改变.
> 
> ```
> 应用名称:
> /usr/bin/open 
> 参数:
> %1 -a MWeb
> ```

你的 Mac 操作系统什么版本？

**Comment by GerrieWell** [comment]
> > @altairwei
> > 外部编辑器是可以打开的. 是修改保存后, wiznote那边不发生改变.
> > ```
> > 应用名称:
> > /usr/bin/open 
> > 参数:
> > %1 -a MWeb
> > ```
> 
> 你的 Mac 操作系统什么版本？

10.15.1

**Comment by YuanfengZhang** [comment]
这回问题发生在了我的电脑上，一天的工作结果全没了。

**Comment by ChloemoShaw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢来信。我将尽快给您回复。

**Comment by altairwei** [comment]
> 这回问题发生在了我的电脑上，一天的工作结果全没了。

先别关闭 WizNotePlus，右键点击文旦该页面，在菜单中选择”打开临时文件夹“，看看有没有 .md 后缀的临时文件。
