### ISSUE TITLE
希望增加笔记右键定位功能

### ISSUE THREAD

**Issue by hzmming** [altairwei/WizNotePlus#89]
希望能在已打开的笔记上，＂右键－定位＂，侧边栏回到笔记所在的文件夹

**Comment by hzmming** [comment]
如果能新增个＂配置项＂：设置切换打开的笔记时，是否自动定位到笔记所在的文件夹就更好了
（就跟很多开发工具一样，如IDEA的auto scroll to source之类的）

**Comment by altairwei** [comment]
点击笔记标题栏右侧第五个按钮，在弹出窗口中有 “定位” 功能。

**Comment by EngineerKevin2468** [comment]
迫切需要这个功能

**Comment by altairwei** [comment]
已实现，请等待 v2.8.2 发布。
