### ISSUE TITLE
[20181031] [BUG] [fedora28] [x86_64] wizNotePlus无法同步笔记本

### ISSUE THREAD

**Issue by shuchaoma** [altairwei/WizNotePlus#9]
环境描述：
    Thinkpad X270
    X86_64
    fedoa 28
基于Qt5.11.2版本构建打包的appimage。

问题描述：
现象一、打开wiz之后，新增笔记，然后点击“同步”按钮，在terminal显示如下信息：
![image](https://user-images.githubusercontent.com/6086958/47786984-74b1e700-dd48-11e8-9030-ca1a71ab5a42.png)
现象二、在wizNotePlus的图形界面中无法看到“同步按钮”动态旋转同步的效果（或者说无任何反映）。

**Comment by shuchaoma** [comment]
1. 代理没有开启。无论是系统层面的，还是为知笔记本身；
2。 完整LOG如下：
[WARNING]: QWidget::setLayout: Attempting to set QLayout "" on QMainWindow "", which already has a layout ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (-5) ((null):0, (null))
[WARNING]: WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed. ((null):0, (null))
[INFO] 本地版本是最新版
[WARNING]: QSslSocket: cannot resolve CRYPTO_num_locks ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve CRYPTO_set_id_callback ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve CRYPTO_set_locking_callback ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve ERR_free_strings ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve EVP_CIPHER_CTX_init ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve sk_new_null ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve sk_push ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve sk_free ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve sk_num ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve sk_pop_free ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve sk_value ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve SSL_library_init ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve SSL_load_error_strings ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve SSL_get_ex_new_index ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve SSLv23_client_method ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve SSLv23_server_method ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve X509_STORE_CTX_get_chain ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve SSLeay ((null):0, (null))
[WARNING]: Incompatible version of OpenSSL ((null):0, (null))
[INFO] Failed to exec json request, network error=99, message=, url=https://as.wiz.cn/as/user/login?clientType=macos&clientVersion=2.6.1&apiVersion=10&srcHost=as.wiz.cn
[DEBUG] new server ""
[DEBUG] "web channel opened"
[DEBUG] [Sync] syncing all started, thread: 0x7f5fe2dea700
[INFO] client version: QTLINUX(2.6.1)
[DEBUG] [Sync] Syncing all notes...
[INFO] Failed to exec json request, network error=99, message=, url=https://as.wiz.cn/as/user/login?clientType=macos&clientVersion=2.6.1&apiVersion=10&srcHost=as.wiz.cn
[DEBUG] new server ""
[DEBUG] [Sync] syncing all started, thread: 0x7f5fe2dea700
[INFO] client version: QTLINUX(2.6.1)
[DEBUG] [Sync] Syncing all notes...
[INFO] Failed to exec json request, network error=99, message=, url=https://as.wiz.cn/as/user/login?clientType=macos&clientVersion=2.6.1&apiVersion=10&srcHost=as.wiz.cn
[DEBUG] new server ""
[DEBUG] oldSize:  QSize(-1, -1) , newSize:  QSize(707, 551)
[DEBUG] [Console]line:  1 ,  "Uncaught ReferenceError: WizEditor is not defined"
[INFO] Failed to exec json request, network error=99, message=, url=https://as.wiz.cn/as/user/login?clientType=macos&clientVersion=2.6.1&apiVersion=10&srcHost=as.wiz.cn
[DEBUG] new server ""
[DEBUG] "WizEditorInit(\"/tmp/.mount_WizNotSU9nVA/WizNote/share/wiznote/files/wizeditor/\", \"zh-cn\", \"220c2ceb-5827-4ca0-892f-7b9f9962150b\", \"伯龙\", false, \"common\");"
[DEBUG] "WizEditorInit(\"/tmp/.mount_WizNotSU9nVA/WizNote/share/wiznote/files/wizeditor/\", \"zh-cn\", \"220c2ceb-5827-4ca0-892f-7b9f9962150b\", \"伯龙\", false, \"common\");WizEditor.off();"
[DEBUG] [Console]line:  19 ,  "web channel opened"

3. 之前提供的log时点击“同步按钮“之后产生的log内容。
====================
这应该时最后一个真正阻止我用起来的问题了吧。

**Comment by altairwei** [comment]
看你提供的 Log 像是 OpenSSL 版本问题，但奇怪的是你又能正常登录？

检查你构建时的 `build-WizNotePlus/lib/` 或者 `package-WizNotePlus/WizNote/lib/` 目录下有没有 `libcrypto.so` 、`libcrypto.so.1.0.0`、`libssl.so` 以及 `libssl.so.1.0.0` 等动态库？

运行 `package.cmake` 脚本时有没有提示 Conan 相关的错误？

**Comment by shuchaoma** [comment]
> 看你提供的 Log 像是 OpenSSL 版本问题，但奇怪的是你又能正常登录？
> 
> 检查你构建时的 `build-WizNotePlus/lib/` 或者 `package-WizNotePlus/WizNote/lib/` 目录下有没有 `libcrypto.so` 、`libcrypto.so.1.0.0`、`libssl.so` 以及 `libssl.so.1.0.0` 等动态库？
> 
> 运行 `package.cmake` 脚本时有没有提示 Conan 相关的错误？

一、在build-WizNotePlus/lib/中存在 libcryptopp库，但是不存在libcrypto库、ssl库。如下图： 
![image](https://user-images.githubusercontent.com/6086958/47851293-2c133000-de13-11e8-8739-4dab5d1c036b.png)

二、在package-WizNotePlus/WizNote/lib/lib中找到了ssl的静态库。如图：
![image](https://user-images.githubusercontent.com/6086958/47851447-9fb53d00-de13-11e8-9097-6930c5ea742a.png)

三、再一开始构建时的确遇到了conna相关的错误，不过根据你提供的构建手册解决了ssl相关的依赖问题。印象中会自动下载了ssl相关的库


挺纳闷的

**Comment by altairwei** [comment]
周末我装个fedora28来检测一下究竟是什么问题。

**Comment by shuchaoma** [comment]
> 周末我装个fedora28虚拟机来检测一下究竟是什么问题。

太感谢了。
请问你是使用什么发行版，还是mac？
我在北京海淀；如果方便的话，甚至可以约线下一起联调；后面我阅读以下代码，对GUI类程序开发经验不多，得多熟悉一段时间

**Comment by altairwei** [comment]
> > 周末我装个fedora28虚拟机来检测一下究竟是什么问题。
> 
> 太感谢了。
> 请问你是使用什么发行版，还是mac？
> 我在北京海淀；如果方便的话，甚至可以约线下一起联调；后面我阅读以下代码，对GUI类程序开发经验不多，得多熟悉一段时间

你是否有可用WizNote的其他电脑？如果有的话可以邮件我你Wiz账号ID，我把你加入WizNotePlus开发组，没有的话可以通过邮件联系。

**Comment by altairwei** [comment]
@shuchaoma 
我在 fedora 28 虚拟机上能正常运行 release 页面的 AppImage ，无法复现你的问题。

**Comment by shuchaoma** [comment]
> > > 周末我装个fedora28虚拟机来检测一下究竟是什么问题。
> > 
> > 
> > 太感谢了。
> > 请问你是使用什么发行版，还是mac？
> > 我在北京海淀；如果方便的话，甚至可以约线下一起联调；后面我阅读以下代码，对GUI类程序开发经验不多，得多熟悉一段时间
> 
> 你是否有可用WizNote的其他电脑？如果有的话可以邮件我你Wiz账号ID，我把你加入WizNotePlus开发组，没有的话可以通过邮件联系。

我现在虚拟机运行Wiz；之前发过邮件的：如下（我的wiz ID 就是邮件名）。
![image](https://user-images.githubusercontent.com/6086958/47911087-8d98d480-decf-11e8-805e-79a0e6e7c82a.png)
#####################################

太遗憾了；竟然没有浮现我的问题。我再继续排查吧

**Comment by altairwei** [comment]
> > > > 周末我装个fedora28虚拟机来检测一下究竟是什么问题。
> > > 
> > > 
> > > 太感谢了。
> > > 请问你是使用什么发行版，还是mac？
> > > 我在北京海淀；如果方便的话，甚至可以约线下一起联调；后面我阅读以下代码，对GUI类程序开发经验不多，得多熟悉一段时间
> > 
> > 
> > 你是否有可用WizNote的其他电脑？如果有的话可以邮件我你Wiz账号ID，我把你加入WizNotePlus开发组，没有的话可以通过邮件联系。
> 
> 我现在虚拟机运行Wiz；之前发过邮件的：如下（我的wiz ID 就是邮件名）。
> ![image](https://user-images.githubusercontent.com/6086958/47911087-8d98d480-decf-11e8-805e-79a0e6e7c82a.png)
> #####################################
> 
> 太遗憾了；竟然没有浮现我的问题。我再继续排查吧

真尴尬，你邮件被outlook.com自动收入垃圾邮箱了。你先自己排查排查，或者再提供跟完整的信息。有可能是你目前 fedora 28 的某些依赖与 WizNote 不匹配。我把你加入 WizNotePlus 开发组。

**Comment by shuchaoma** [comment]
中午抽出时间研究了一下这个问题，初步结论是：系统内置的openssl版本是1.1.0，这个版本丢弃了一些接口（如SSLv23_client_method），而安装的Qt5.11.2的QSslSocket是的基于低版本openssl构建的。


相关资料如下：
![image](https://user-images.githubusercontent.com/6086958/47981633-9b389f00-e107-11e8-9030-71a9c02bbaea.png)
![image](https://user-images.githubusercontent.com/6086958/47981671-c0c5a880-e107-11e8-8dc9-de699b2b4d3f.png)

以及网上同样有人遇到类似问题：https://blog.csdn.net/owen157/article/details/75043792
——————————————————————————————————

结论待验证。先工作了～

**Comment by altairwei** [comment]
> 中午抽出时间研究了一下这个问题，初步结论是：系统内置的openssl版本是1.1.0，这个版本丢弃了一些接口（如SSLv23_client_method），而安装的Qt5.11.2的QSslSocket是的基于低版本openssl构建的。
> 
> 相关资料如下：
> 【 [https://www.openssl.org/news/cl110.txt】](https://www.openssl.org/news/cl110.txt%E3%80%91)
> 
> ![image](https://user-images.githubusercontent.com/6086958/47981633-9b389f00-e107-11e8-9030-71a9c02bbaea.png)
> ![image](https://user-images.githubusercontent.com/6086958/47981671-c0c5a880-e107-11e8-8dc9-de699b2b4d3f.png)
> 
> 以及网上同样有人遇到类似问题：https://blog.csdn.net/owen157/article/details/75043792
> ——————————————————————————————————
> 
> 一、结论待验证。先工作了～
> 二、作者曾经在虚拟机fedora28上做过复现，但是没有复现同样问题。难道openssl版本进行了专门设置？

发行版自带的 OpenSSL 应该不会影响到我打包的 AppImage ，因为我已经把 OpenSSL v1.0.2p 一起打包了。你在编译过程中执行的 Conan 步骤，就是将预编译好的 OpenSSL v1.0.2p 取回本地并一起打包。所以，我之前让你检查 Conan 这一步就是基于这个理由。

**Comment by altairwei** [comment]
如果你没有其他程序依赖新版 OpenSSL 的话，你可以试试用包管理器安装 `openssl1.0` 和 `libssl1.0-dev` 。

**Comment by shuchaoma** [comment]
> 如果你没有其他程序依赖新版 OpenSSL 的话，你可以试试用包管理器安装 `openssl1.0` 和 `libssl1.0-dev` 。
> 
> 我在 fedora 28 上试了一下，yum 好像没有这两个包。

验证完成！结论：
推测完全正确，为openssl版本所致。写在系统openssl，然后重新编译打包后，程序的同步功能完美解决。

想法：或许我们可以优化打包方案。
比如openssl依赖的版本也包含入appimage；
比如linux当前流行的faltpak打包方案似乎被多个linux发行版都支持，也更general
