### ISSUE TITLE
请问最近有更新计划吗？

### ISSUE THREAD

**Issue by tttwwy** [altairwei/WizNotePlus#91]
请问最近有版本更新计划吗？ 非常感谢

**Comment by altairwei** [comment]
过年期间更新一波

**Comment by tttwwy** [comment]
非常期待！

**Comment by altairwei** [comment]
可以先去本仓库  Action 页面找找成功的构建，里面有 Windows 和 Linux 平台的预编译版本。

**Comment by tttwwy** [comment]
@altairwei 只能找到源码？ 找不到可以在mac上直接运行的版本 ？

**Comment by altairwei** [comment]
见下图：

![Snipaste_2020-03-03_14-55-12](https://user-images.githubusercontent.com/30854075/75750368-0081bc00-5d5f-11ea-82bb-1f2ee548e573.png)

点击进入任一成功的构建，找到 MacOS_Dist 下载。

不过目前 MacOS 构建有点兼容性问题，不能在太旧的 MacOS 比如 10.13 上运行。我周末修复这个问题后，在测试测试就会发布到 Release 。

**Comment by altairwei** [comment]
@tttwwy 已更新，见 Release

**Comment by tttwwy** [comment]
赞
