### ISSUE TITLE
用外部编辑器typora自动导入的图片，在另一台设备无法同步成功

### ISSUE THREAD

**Issue by wenglihong** [altairwei/WizNotePlus#92]
![[公式]](index_files/equation-1579589744044.svg)
文件路径同步过来了，但是貌似本地没有这个路径？
我是在ubuntu编辑的笔记，用mac os客户端打开

**Comment by altairwei** [comment]
按照下图配置 Typora：
![](https://github.com/altairwei/WizNotePlus/wiki/images/Typora_Import_Images.png)
