### ISSUE TITLE
笔记内链接跳转问题

### ISSUE THREAD

**Issue by wilson1987** [altairwei/WizNotePlus#94]
用自带的编辑器插入笔记内链时，跳转会出现问题
![image](https://user-images.githubusercontent.com/13399208/73593402-c85c4300-453e-11ea-9223-2e0d420bdb89.png)

**Comment by altairwei** [comment]
问题已经修复，等待发布新版本吧。

**Comment by wilson1987** [comment]
> 问题已经修复，等待发布新版本吧。

谢谢，期待新版本。

**Comment by altairwei** [comment]
@wilson1987 新版本已发布，问题已修复
