### ISSUE TITLE
执行“conan install ../WizNotePlus”出现如下错误

### ISSUE THREAD

**Issue by wenglihong** [altairwei/WizNotePlus#95]
ERROR: qt/5.12.6@bincrafters/stable: Error in requirements() method, line 263
	if self.settings.os == "Linux" and not tools.cross_building(self.settings, skip_x64_x86=True):
	TypeError: cross_building() got an unexpected keyword argument 'skip_x64_x86'

**Comment by altairwei** [comment]
你先去 Action 页面找一找有没有可用的预编译包。最近会重新更新编译流程。

**Comment by altairwei** [comment]
请参考 Wiki 最新的编译教程，然后选择 release-2.8.0 分支编译。
