### ISSUE TITLE
重复弹出升级提醒

### ISSUE THREAD

**Issue by eegod** [altairwei/WizNotePlus#96]
2.8.0-beta.2
选择“以后再说”下次启动还是会弹出

**Comment by altairwei** [comment]
感谢报告问题！

**Comment by altairwei** [comment]
问题发生的原因主要是我忘了更新 WizNotePlus 的版本号。本身 UpgradeChecker 的行为是正常的，如果不想要自动更新检查，可以去设置页面取消自动更新检查。

**Comment by altairwei** [comment]
下载 https://github.com/altairwei/WizNotePlus/actions/runs/51708503 中的对应 XXX_Dist ，然后试用看看是否还会重复弹出？

**Comment by altairwei** [comment]
见 beta.3
