### ISSUE TITLE
 beta.2 mac 安装包无法安装

### ISSUE THREAD

**Issue by ZhenshengLee** [altairwei/WizNotePlus#97]
mac 10.15.3, beta.2
![image](https://user-images.githubusercontent.com/17764118/76165355-5dcba200-6191-11ea-8344-01ac48897ff6.png)

**Comment by altairwei** [comment]
在 “安全与隐私” 设置里，允许任何来源的应用。

我没有 Apple 的开发者证书，所以无法 code sign 。

**Comment by ZhenshengLee** [comment]
> 在 “安全与隐私” 设置里，允许任何来源的应用。
> 
> 我没有 Apple 的开发者证书，所以无法 code sign 。

已经这么设置了。
beta.1是可以安装的

**Comment by altairwei** [comment]
按照 Apple 官方说明来做吧：https://support.apple.com/zh-cn/guide/mac-help/mh40616/mac
