### ISSUE TITLE
archlinux: failed to open web socket server. ((null):0, (null)

### ISSUE THREAD

**Issue by activeion** [altairwei/WizNotePlus#98]
makepkg编译arch软件包，正常。pacman -U 安装正常。运行出错，输出如下：

jizh➜~» wiz                                                                            [13:35:32]
QtWebEngine::initialize() called with QCoreApplication object already created and should be call before. This is depreciated and may fail in the future.
[DEBUG] set server :  "http://api.wiz.cn/"
[DEBUG] set user id for token ;  "15901356163"
[WARNING]: QWidget::setLayout: Attempting to set QLayout "" on QMainWindow "", which already has a layout ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (-5) ((null):0, (null))
[FATAL]: Failed to open web socket server. ((null):0, (null))
[1]    24667 abort (core dumped)  WizNote

**Comment by activeion** [comment]
only because I  login wiznote webpage.

**Comment by altairwei** [comment]
有可能是因为上一次 WizNotePlus 没有正常退出，导致 8848 端口被占用。下次出现这个问题，你检查下这个端口。
